// Bershka_Orders_Market_MICRO
let
    Source = Table.Combine({Bershka_Orders_Market_MICRO_BF2019,Bershka_Orders_Market_MICRO_BF2020}),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_FECHA", type date}, {"PEDIDOS", Int64.Type}, {"UNIDADES", Int64.Type}, {"PAIS", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ID_FECHA", "Date"}, {"PEDIDOS", "Orders"}, {"UNIDADES", "Units"}, {"AMOUNT_EUROS", "Amount (€)"}, {"MARKET_ENGLISH", "Market English"},  {"LOCAL_AMOUNT", "Local Amount"}, {"PAIS", "ID Country"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns",",","",Replacer.ReplaceText,{"Market English"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Replaced Value",{"Date", "ID Country", "Market English", "Orders", "Units", "Amount (€)", "Local Amount"})
in
    #"Reordered Columns"