// Bershka_Store_Status
let
    Source = DB2.Database("ieecdb2v1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="-- IBM DB2 - SEGUNDO TRAMO DE RÉPLICA - ENTORNO PRO - OMNICHANNEL - BERSHKA - SINT - FY2019#(lf)SELECT#(lf)#(tab)pa.ID_PAIS AS COUNTRY,#(lf)#(tab)pa.DESCRIPCION AS COUNTRY_DESCRIPTION,#(lf)#(tab)os.NOMBRE AS STORE_DESCRIPTION,#(lf)#(tab)os.ID_LOCALIZACION AS PHYSICAL_STORE_ID,#(lf)#(tab)tgdos.DESCRIPCION AS RELATIONSHIP_TYPE,#(lf)#(tab)CASE os.ID_ESTADO_ORIGEN_STOCK #(lf)#(tab)#(tab)WHEN 1 THEN CASE #(lf)#(tab)#(tab)#(tab)WHEN NOT gdosc.ID_GRUPO_DISTRIBUCION_ORIGEN_STOCK IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)AND gdosc.PEDIDOS_REASIGNADOS >= MAXIMO_PEDIDOS_REASIGNADOS THEN 'Capacidad Topeada' #(lf)#(tab)#(tab)#(tab)ELSE CASE gdos.HABILITADO #(lf)#(tab)#(tab)#(tab)#(tab)WHEN 1 THEN 'Relación Activa'#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 2 THEN 'Relación Pausada'#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 3 THEN 'Relación Contingencia'#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 4 THEN 'Relación Pausada Parcial'#(lf)#(tab)#(tab)#(tab)ELSE#(tab)'Relación Inactiva'#(lf)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)END#(lf)#(tab)ELSE 'Origen Inactivo'#(lf)#(tab)END AS STATUS,#(lf)#(tab)COALESCE(d.POBLACION, 'Nulo') AS CITY,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(tab) = 3 THEN gdosc.PEDIDOS_REASIGNADOS#(lf)#(tab)#(tab)ELSE#(tab)osc.UMBRAL_MINIMO #(lf)#(tab)END AS MIN_THRESHOLD,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(tab) = 3 THEN gdosc.PEDIDOS_REASIGNADOS#(lf)#(tab)#(tab)ELSE#(tab)osc.TOTAL_PEDIDOS_VIVOS#(lf)#(tab)END AS CURRENT_LIVE_ORDERS,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(tab) = 3 THEN gdosc.MAXIMO_PEDIDOS_REASIGNADOS#(lf)#(tab)#(tab)ELSE#(tab)osc.UMBRAL_MAXIMO#(lf)#(tab)END AS MAX_THRESHOLD,#(lf)#(tab)CASE os.ID_ESTADO_ORIGEN_STOCK #(lf)#(tab)#(tab)WHEN 1 THEN CASE #(lf)#(tab)#(tab)#(tab)WHEN NOT gdosc.ID_GRUPO_DISTRIBUCION_ORIGEN_STOCK IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)AND gdosc.PEDIDOS_REASIGNADOS >= MAXIMO_PEDIDOS_REASIGNADOS THEN 0 #(lf)#(tab)#(tab)#(tab)ELSE CASE gdos.HABILITADO #(lf)#(tab)#(tab)#(tab)#(tab)WHEN 1 THEN 1#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 2 THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 3 THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 4 THEN 0#(lf)#(tab)#(tab)#(tab)ELSE#(tab)0#(lf)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)END#(lf)#(tab)ELSE 0#(lf)#(tab)END AS BOOLEAN_STATUS#(lf)FROM#(tab)INDOM_ITX.GRUPO_DISTRIBUCION gd#(lf)INNER JOIN INDOM_ITX.ENTIDAD_ECOMMERCE ee#(lf)#(tab)ON ee.ID_GRUPO_DISTRIBUCION = gd.ID_GRUPO_DISTRIBUCION#(lf)INNER JOIN INDOM_ITX.GRUPO_DISTRIBUCION_ORIGEN_STOCK gdos#(lf)#(tab)ON gdos.ID_GRUPO_DISTRIBUCION = gd.ID_GRUPO_DISTRIBUCION#(lf)INNER JOIN INDOM_ITX.ORIGEN_STOCK os#(lf)#(tab)ON os.ID_ORIGEN_STOCK = gdos.ID_ORIGEN_STOCK#(lf)#(tab)#(tab)AND os.COD_ORIGEN_STOCK_WCS LIKE '%PST%' -- ORIGEN STOCK TIENDA FÍSICA#(lf)#(tab)#(tab)#(tab)AND os.ID_CADENA = 4 -- BERSHKA#(lf)INNER JOIN INDOM_ITX.TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK tgdos#(lf)#(tab)ON tgdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK = gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(lf)LEFT JOIN INDOM_ITX.GRUPO_DISTRIBUCION_ORIGEN_STOCK_CAPACIDAD gdosc#(lf)#(tab)ON gdosc.ID_GRUPO_DISTRIBUCION_ORIGEN_STOCK = gdos.ID_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(lf)LEFT JOIN INDOM_ITX.ORIGEN_STOCK_CARGA osc#(lf)#(tab)ON osc.ID_ORIGEN_STOCK = os.ID_ORIGEN_STOCK#(lf)INNER JOIN MAESTROS.LOCALIZACION l#(lf)#(tab)ON l.ID_LOCALIZACION = os.ID_LOCALIZACION#(lf)INNER JOIN MAESTROS.DIRECCION d#(lf)#(tab)ON d.ID_DIRECCION = l.ID_DIRECCION#(lf)INNER JOIN MAESTROS.PAIS pa#(lf)#(tab)ON pa.ID_PAIS = os.ID_PAIS#(lf)WHERE#(lf)#(tab)ee.DESCRIPCION NOT LIKE '%TEST%'#(lf)#(tab)#(tab)AND ee.DESCRIPCION NOT LIKE '%Test%'#(lf)#(tab)#(tab)#(tab)AND gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK IN (1, 2, 3)#(lf)#(tab)#(tab)#(tab)#(tab)AND #(lf)#(tab)#(tab)#(tab)#(tab)(tgdos.DESCRIPCION = 'Capacidad' #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)OR #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)(tgdos.DESCRIPCION = 'Disponible'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AND gdos.HABILITADO IN (1, 4)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)#(tab))#(lf)WITH UR;", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"COUNTRY", Int64.Type}, {"BOOLEAN_STATUS", type text}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"COUNTRY", "Country"}, {"COUNTRY_DESCRIPTION", "Country Description"}, {"STORE_DESCRIPTION", "Store"}, {"PHYSICAL_STORE_ID", "Store ID"}, {"RELATIONSHIP_TYPE", "Relationship Type"}, {"STATUS", "Status"}, {"CITY", "City"}, {"MIN_THRESHOLD", "Min Threshold"}, {"CURRENT_LIVE_ORDERS", "Current Orders"}, {"MAX_THRESHOLD", "Max Threshold"}, {"BOOLEAN_STATUS", "Boolean Status"}}),
    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "Store Description", each Text.PadStart(Text.BeforeDelimiter(Number.ToText([Store ID]), " -"), 5, "0") & " - " & [Store], type text),
    #"Personalizada agregada2" = Table.AddColumn(#"Personalizada agregada", "ID Country-Store", each Number.ToText([Country]) & "-" & Text.PadStart(Text.BeforeDelimiter(Number.ToText([Store ID]), " -"), 5, "0"), type text),
    #"Valor reemplazado" = Table.ReplaceValue(#"Personalizada agregada2","1","Yes",Replacer.ReplaceText,{"Boolean Status"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","0","No",Replacer.ReplaceText,{"Boolean Status"}),
    #"Consultas combinadas" = Table.NestedJoin(#"Valor reemplazado1", {"Country"}, Countries, {"Country"}, "Countries", JoinKind.LeftOuter),
    #"Se expandió Countries" = Table.ExpandTableColumn(#"Consultas combinadas", "Countries", {"English Description"}, {"English Description"}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Se expandió Countries",{"ID Country-Store", "Country", "Country Description", "English Description", "Store", "Store ID", "Relationship Type", "Status", "City", "Min Threshold", "Current Orders", "Max Threshold", "Boolean Status", "Store Description"}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Columnas reordenadas",{"Country", "Country Description", "Store", "Store ID", "City"})
in
    #"Columnas quitadas"