// Bershka_SINT
let
    Source = Table.Combine({Bershka_SINT_FY2019, Bershka_SINT_FY2020}),
    #"Removed Columns" = Table.RemoveColumns(Source,{"STATUS_EQUIVALENTE", "ID_TIPO_OPERATIVA_PEDIDO"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"COD_PAIS", Int64.Type}, {"UNITS", Int64.Type}, {"STORE_CODE", type text}, {"TOTAL_IMPORT", Currency.Type}, {"ORDER_CODE", type text}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"ORDER_CODE", "COD_PAIS", "STORE_CODE", "STORE", "UNITS", "LOCAL_PURCHASE_DATE", "LOCAL_RECEPTION_DATE", "LOCAL_PICKING_START_DATE", "LOCAL_PICKING_END_DATE", "LOCAL_PACKING_DATE", "LOCAL_EXPEDITION_DATE", "LOCAL_REJECTION_DATE", "LOCAL_CANCELLATION_DATE", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO", "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY"}),
    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns","","No informado",Replacer.ReplaceValue,{"CANCEL_REASON"}),
    #"Merged Queries" = Table.NestedJoin(#"Replaced Value",{"COD_PAIS"},Countries,{"Country"},"Countries",JoinKind.LeftOuter),
    #"Expanded Countries" = Table.ExpandTableColumn(#"Merged Queries", "Countries", {"English Description"}, {"English Description"}),
    #"Added Custom" = Table.AddColumn(#"Expanded Countries", "Store Location", each Text.PadStart([STORE_CODE], 5, "0"), type text),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Store Description", each [Store Location] & " - " & [STORE], type text),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "ID Country-Store", each Text.Combine({Text.From([COD_PAIS], "es-ES"), "-", [Store Location]}), type text),
    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom2",{"STORE", "STORE_CODE"}),
    #"Added Custom Diff Date Total Preparation" = Table.AddColumn(#"Removed Columns1", "Diff Date Total Preparation", each Duration.TotalDays([LOCAL_EXPEDITION_DATE] - [LOCAL_PURCHASE_DATE]), Int64.Type),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom Diff Date Total Preparation",{{"Diff Date Total Preparation", type number}}),
    #"Rounded Off" = Table.TransformColumns(#"Changed Type1",{{"Diff Date Total Preparation", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Reception" = Table.AddColumn(#"Rounded Off", "Diff Date Reception", each Duration.TotalDays([LOCAL_RECEPTION_DATE] - [LOCAL_PURCHASE_DATE]), Int64.Type),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom Diff Date Reception",{{"Diff Date Reception", type number}}),
    #"Rounded Off1" = Table.TransformColumns(#"Changed Type2",{{"Diff Date Reception", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Picking" = Table.AddColumn(#"Rounded Off1", "Diff Date Picking", each Duration.TotalDays([LOCAL_PICKING_END_DATE] - [LOCAL_RECEPTION_DATE]), Int64.Type),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom Diff Date Picking",{{"Diff Date Picking", type number}}),
    #"Rounded Off2" = Table.TransformColumns(#"Changed Type3",{{"Diff Date Picking", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Packing" = Table.AddColumn(#"Rounded Off2", "Diff Date Packing", each Duration.TotalDays([LOCAL_PACKING_DATE] - [LOCAL_PICKING_END_DATE]), Int64.Type),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom Diff Date Packing",{{"Diff Date Packing", type number}}),
    #"Rounded Off3" = Table.TransformColumns(#"Changed Type4",{{"Diff Date Packing", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Expedition" = Table.AddColumn(#"Rounded Off3", "Diff Date Expedition", each Duration.TotalDays([LOCAL_EXPEDITION_DATE] - [LOCAL_PACKING_DATE]), Int64.Type),
    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom Diff Date Expedition",{{"Diff Date Expedition", type number}}),
    #"Rounded Off4" = Table.TransformColumns(#"Changed Type5",{{"Diff Date Expedition", each Number.Round(_, 2), type number}}),
    #"Personalizada agregada" = Table.AddColumn(#"Rounded Off4", "Diff Date Total Rejection", each Duration.TotalDays([LOCAL_REJECTION_DATE] - [LOCAL_RECEPTION_DATE])),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Diff Date Total Rejection", type number}, {"BLOQUEO_PEDIDO_TRANSPORTISTA", type logical}, {"BLOQUEO_DOCUMENTACION", type logical}}),
    #"Redondeado" = Table.TransformColumns(#"Tipo cambiado",{{"Diff Date Total Rejection", each Number.Round(_, 2), type number}}),
    #"Inserted Date" = Table.AddColumn(#"Redondeado", "Date", each DateTime.Date([LOCAL_PURCHASE_DATE]), type date),
    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "Time", each DateTime.Time([LOCAL_PURCHASE_DATE]), type time),
    #"Reordered Columns1" = Table.ReorderColumns(#"Inserted Time",{"ORDER_CODE", "COD_PAIS", "UNITS", "LOCAL_PURCHASE_DATE", "Date", "Time", "LOCAL_RECEPTION_DATE", "LOCAL_PICKING_START_DATE", "LOCAL_PICKING_END_DATE", "LOCAL_PACKING_DATE", "LOCAL_EXPEDITION_DATE", "LOCAL_CURRENT_DATETIME", "LOCAL_REJECTION_DATE", "LOCAL_CANCELLATION_DATE", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO", "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "BLOQUEO_PEDIDO_TRANSPORTISTA", "BLOQUEO_DOCUMENTACION"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns1",{{"Date", "Local Purchase Date"}, {"Time", "Local Purchase Time"}, {"BLOQUEO_PEDIDO_TRANSPORTISTA", "Courier Lock"}, {"BLOQUEO_DOCUMENTACION", "Documentation Lock"}, {"OPERATION_TYPE", "Operation Type"}}),
    #"Removed Columns3" = Table.RemoveColumns(#"Renamed Columns",{"LOCAL_PURCHASE_DATE"}),
    #"Inserted Date1" = Table.AddColumn(#"Removed Columns3", "Date", each DateTime.Date([LOCAL_RECEPTION_DATE]), type date),
    #"Inserted Time1" = Table.AddColumn(#"Inserted Date1", "Time", each DateTime.Time([LOCAL_RECEPTION_DATE]), type time),
    #"Reordered Columns2" = Table.ReorderColumns(#"Inserted Time1",{"ORDER_CODE", "COD_PAIS", "UNITS", "Local Purchase Date", "Local Purchase Time", "LOCAL_RECEPTION_DATE", "Date", "Time", "LOCAL_PICKING_START_DATE", "LOCAL_PICKING_END_DATE", "LOCAL_CURRENT_DATETIME", "LOCAL_PACKING_DATE", "LOCAL_EXPEDITION_DATE", "LOCAL_REJECTION_DATE", "LOCAL_CANCELLATION_DATE", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO", "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Courier Lock", "Documentation Lock"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns2",{{"Date", "Local Reception Date"}, {"Time", "Local Reception Time"}}),
    #"Removed Columns4" = Table.RemoveColumns(#"Renamed Columns1",{"LOCAL_RECEPTION_DATE"}),
    #"Inserted Date2" = Table.AddColumn(#"Removed Columns4", "Date", each DateTime.Date([LOCAL_PICKING_START_DATE]), type date),
    #"Inserted Time2" = Table.AddColumn(#"Inserted Date2", "Time", each DateTime.Time([LOCAL_PICKING_START_DATE]), type time),
    #"Reordered Columns3" = Table.ReorderColumns(#"Inserted Time2",{"ORDER_CODE", "COD_PAIS", "UNITS", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "LOCAL_PICKING_START_DATE", "Date", "LOCAL_CURRENT_DATETIME", "Time", "LOCAL_PICKING_END_DATE", "LOCAL_PACKING_DATE", "LOCAL_EXPEDITION_DATE", "LOCAL_REJECTION_DATE", "LOCAL_CANCELLATION_DATE", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO", "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Courier Lock", "Documentation Lock"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns3",{{"Date", "Local Picking Start Date"}, {"Time", "Local Picking Start Time"}}),
    #"Removed Columns5" = Table.RemoveColumns(#"Renamed Columns2",{"LOCAL_PICKING_START_DATE"}),
    #"Inserted Date3" = Table.AddColumn(#"Removed Columns5", "Date", each DateTime.Date([LOCAL_PICKING_END_DATE]), type date),
    #"Inserted Time3" = Table.AddColumn(#"Inserted Date3", "Time", each DateTime.Time([LOCAL_PICKING_END_DATE]), type time),
    #"Reordered Columns4" = Table.ReorderColumns(#"Inserted Time3",{"ORDER_CODE", "COD_PAIS", "UNITS", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "LOCAL_CURRENT_DATETIME", "Local Picking Start Time", "LOCAL_PICKING_END_DATE", "Date", "Time", "LOCAL_PACKING_DATE", "LOCAL_EXPEDITION_DATE", "LOCAL_REJECTION_DATE", "LOCAL_CANCELLATION_DATE", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO", "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Courier Lock", "Documentation Lock"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns4",{{"Date", "Local Picking End Date"}, {"Time", "Local Picking End Time"}}),
    #"Removed Columns6" = Table.RemoveColumns(#"Renamed Columns3",{"LOCAL_PICKING_END_DATE"}),
    #"Inserted Date4" = Table.AddColumn(#"Removed Columns6", "Date", each DateTime.Date([LOCAL_PACKING_DATE]), type date),
    #"Inserted Time4" = Table.AddColumn(#"Inserted Date4", "Time", each DateTime.Time([LOCAL_PACKING_DATE]), type time),
    #"Reordered Columns5" = Table.ReorderColumns(#"Inserted Time4",{"ORDER_CODE", "COD_PAIS", "UNITS", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "LOCAL_CURRENT_DATETIME", "Local Picking Start Time", "Local Picking End Date", "Local Picking End Time", "LOCAL_PACKING_DATE", "Date", "Time", "LOCAL_EXPEDITION_DATE", "LOCAL_REJECTION_DATE", "LOCAL_CANCELLATION_DATE", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO",  "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Courier Lock", "Documentation Lock"}),
    #"Renamed Columns4" = Table.RenameColumns(#"Reordered Columns5",{{"Date", "Local Packing Date"}, {"Time", "Local Packing Time"}, {"LOCAL_PACKING_DATE", "Local Packing DateTime"}}),
    #"Inserted Date5" = Table.AddColumn(#"Renamed Columns4", "Date", each DateTime.Date([LOCAL_EXPEDITION_DATE]), type date),
    #"Inserted Time5" = Table.AddColumn(#"Inserted Date5", "Time", each DateTime.Time([LOCAL_EXPEDITION_DATE]), type time),
    #"Reordered Columns6" = Table.ReorderColumns(#"Inserted Time5",{"ORDER_CODE", "COD_PAIS", "UNITS", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "LOCAL_CURRENT_DATETIME", "Local Picking Start Time", "Local Picking End Date", "Local Picking End Time", "Local Packing DateTime", "Local Packing Date", "Local Packing Time", "LOCAL_EXPEDITION_DATE", "Date", "Time", "LOCAL_REJECTION_DATE", "LOCAL_CANCELLATION_DATE", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO", "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Courier Lock", "Documentation Lock"}),
    #"Renamed Columns5" = Table.RenameColumns(#"Reordered Columns6",{{"Date", "Local Expedition Date"}, {"Time", "Local Expedition Time"}}),
    #"Removed Columns7" = Table.RemoveColumns(#"Renamed Columns5",{"LOCAL_EXPEDITION_DATE"}),
    #"Inserted Date6" = Table.AddColumn(#"Removed Columns7", "Date", each DateTime.Date([LOCAL_REJECTION_DATE]), type date),
    #"Inserted Time6" = Table.AddColumn(#"Inserted Date6", "Time", each DateTime.Time([LOCAL_REJECTION_DATE]), type time),
    #"Reordered Columns7" = Table.ReorderColumns(#"Inserted Time6",{"ORDER_CODE", "COD_PAIS", "UNITS", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "LOCAL_CURRENT_DATETIME", "Local Picking Start Time", "Local Picking End Date", "Local Picking End Time", "Local Packing DateTime", "Local Packing Date", "Local Packing Time", "Local Expedition Date", "Local Expedition Time", "LOCAL_REJECTION_DATE", "Date", "Time", "LOCAL_CANCELLATION_DATE", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO", "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Courier Lock", "Documentation Lock"}),
    #"Renamed Columns6" = Table.RenameColumns(#"Reordered Columns7",{{"Date", "Local Rejection Date"}, {"Time", "Local Rejection Time"}}),
    #"Removed Columns8" = Table.RemoveColumns(#"Renamed Columns6",{"LOCAL_REJECTION_DATE"}),
    #"Inserted Date7" = Table.AddColumn(#"Removed Columns8", "Date", each DateTime.Date([LOCAL_CANCELLATION_DATE]), type date),
    #"Inserted Time7" = Table.AddColumn(#"Inserted Date7", "Time", each DateTime.Time([LOCAL_CANCELLATION_DATE]), type time),
    #"Reordered Columns8" = Table.ReorderColumns(#"Inserted Time7",{"ORDER_CODE", "COD_PAIS", "UNITS", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "LOCAL_CURRENT_DATETIME", "Local Picking Start Time", "Local Picking End Date", "Local Picking End Time", "Local Packing DateTime", "Local Packing Date", "Local Packing Time", "Local Expedition Date", "Local Expedition Time", "Local Rejection Date", "Local Rejection Time", "LOCAL_CANCELLATION_DATE", "Date", "Time", "FECHA_HORA_MAXIMA_PREPARACION", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO",  "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Courier Lock", "Documentation Lock"}),
    #"Renamed Columns7" = Table.RenameColumns(#"Reordered Columns8",{{"Date", "Local Cancellation Date"}, {"Time", "Local Cancellation Time"}}),
    #"Removed Columns9" = Table.RemoveColumns(#"Renamed Columns7",{"LOCAL_CANCELLATION_DATE"}),
    #"Reordered Columns9" = Table.ReorderColumns(#"Removed Columns9",{"ORDER_CODE", "COD_PAIS", "UNITS", "STATUS", "CANCEL_REASON", "COURIER", "TIPO_ENVIO", "BUNDLES", "BUNDLES_SIZE", "TOTAL_IMPORT", "CURRENCY", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "Local Picking Start Time", "Local Picking End Date", "Local Picking End Time", "Local Packing DateTime", "Local Packing Date", "Local Packing Time", "Local Expedition Date", "Local Expedition Time", "Local Rejection Date", "Local Rejection Time", "Local Cancellation Date", "Local Cancellation Time", "FECHA_HORA_MAXIMA_PREPARACION", "LOCAL_CURRENT_DATETIME", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition"}),
    #"Renamed Columns8" = Table.RenameColumns(#"Reordered Columns9",{{"COD_PAIS", "Country"}, {"ORDER_CODE", "Order Code"}, {"UNITS", "Units"}, {"FECHA_HORA_MAXIMA_PREPARACION", "Max Preparation DateTime"}, {"STATUS", "Status"}, {"CANCEL_REASON", "Cancel Reason"}, {"COURIER", "Courier"}, {"BUNDLES", "Bundles"}, {"BUNDLES_SIZE", "Bundles Size"}, {"TOTAL_IMPORT", "Total Import"}, {"CURRENCY", "Currency"}, {"TIPO_ENVIO", "Tipo Envío"}, {"LOCAL_CURRENT_DATETIME", "Local DateTime"}}),
    #"Personalizada agregada2" = Table.AddColumn(#"Renamed Columns8", "Equivalent Status", each if ([Status] = "EXPEDITED" or [Status] = "TRANSFERRED") then "Shipped" else if ([Status] = "PACKED" or [Status] = "READY_FOR_TRANSFER") then "Packed" else if ([Status] = "RECEIVED" or [Status] = "RESERVED") then "Received" else if ([Status] = "ANNULED" and [Cancel Reason] = "Anulación Cliente") then "Customer Canceled" else if [Status] = "ANNULED" then "Rejected" else if ([Status] = "INCOMPLETE" or [Status] = "READY_FOR_PACKING" or [Status] = "IN PICKING" or [Status] = "ITEMS_COLLECTED" or [Status] = "PICKING_COMPLETE" or [Status] = "PARTIALLY_PICKED") then "Picking Process" else "DESCONOCIDO"),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Personalizada agregada2",{{"Equivalent Status", type text}}),
    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado2", "Packing Date Pending", each if [Local Packing Date] = null then "Pending to Pack" else [Local Packing Date]),
    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"Packing Date Pending", type text}}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Tipo cambiado3",{"Order Code", "Country", "Units", "Status", "Cancel Reason", "Courier", "Tipo Envío", "Bundles", "Bundles Size", "Total Import", "Currency", "English Description", "Store Location", "Store Description", "ID Country-Store", "Operation Type", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "Local Picking Start Time", "Local Picking End Date", "Local Picking End Time", "Local Packing DateTime", "Local Packing Date", "Local Packing Time", "Local Expedition Date", "Local Expedition Time", "Local Rejection Date", "Local Rejection Time", "Local Cancellation Date", "Local Cancellation Time", "Max Preparation DateTime", "Local DateTime", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Equivalent Status", "Packing Date Pending", "Courier Lock", "Documentation Lock"})
in
    #"Columnas reordenadas"