// Store Capacity
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZVxLtiwhCtzLG/dARFHW0qf3v40mJSsl4s5Ky/SDiHwC//vff23sof/+809Ga//+95+oUNUZFfsrS7co9/ErtyXPB/JrILo6VEQLqpDmVGErKvwrd29QnoZlGQ7lqKByr2UZ5/tVJoDjyZ5YngLtgyr0PdDA++n/0kTManvvA79Xwf6lK5TnWPi9QXsZ02G8sTv937F/LuuGcm+G5TWwP2F6wHzNBtDX+qHnbe+tY3t1Wu+G9czDU7esRu1Fif4d2y8cf3Sav+B4QvtrDfYz1o/9W5s0/2d+s8wP6T0PPev3MJ65434L7n+sB/dDaD1xlIjfYH9iu5ToO3E/GtJ32DOelTLxp+D/spF/5sTzoNS/nfN3/1+j0kv62iBzYj1P2ebl3wX0bq6n/JHjsM9XHk2huQt8bmPU/0XtbN8tbxccbm8o2zm+erfvbNe40z/b9StLnK9J4+H89iFXv+VptX/Ruev/cXpr/4/Ahf9D3Cwq0/9HPN3NxdFnb1jG0W2czfrK3vJwltUarN5gdJF1xhu3v8OstzX0HrwhRBv4f2x7R//xkhxZKR/1QlgBs652Dvso5br7T1mpPKg86fuNZYXdW+2M30t54f8G3CQdhEtcXQrzFRVob2NtnN+i+WzH/x0Oc7Sn8ib6HO4v812O8zmX0bffMgfQJ4Y76y/sfAggl//lJ95vxTMlKRf0ohYh0uq2PyLrGVWu3jLWgmHjEjsVVwuZ/kxMbh96zm2psG4wynDSlkIwnT4uv47T6ZU1yc9Fv9qHfHdabQM7tOzxTjN6FFjII99wZXKu169CxPXQb5VPDCpCY9m1QsS8U4sjY0uL1R1b7CRXUSN8wifdFrWIm5U6xVHac/dRxd48LC4ubuNOn9BavA2aRxPsw0NG4saODWpuzPQInqLE7qM0vqVpE/Z9mk3gg7HgVFiqVPd/P+sup05AJYjyxjKqBFHuVB5UhvlE2bCsHaXAkcq1vKlMUuUwZfn/kLxKQZKqg+YzBdc/SSqj3I8yzX+S1Js0v6MyVqnLUpPmu+6t9JRototGPwpl+frckbVMMt9pNMfVyrmj7h3QV9Vg4rRO0Ci6DZRcMcFFFcYtjg1TKyZXnIsIKgZXdKpQHla5084txLhiQkXr54L5JHusBIgfEpQN0HO2dikPvCzkMEuxcdO+KjfSIU5pcO5MvQ06qpTaj0Z8P9BcxG2gR57U6wnn6IIjutHl5AYCIZTYVT+I8sbyggE91ZKqY+OaPXkMKjZ+cW6uUva6L8GUbUJ5wQwk7uYNRAwWnHDVxeIcNiq45VwPVewI3LdRcQhdBQ3eF8HXCuyxkj0+WR8q5sDNCpVm3sOvpCBqnpzCLI7W0HLkeZdzc/5GS+uiNJ8gOaOMw61drZGQBY7WiCvICtkT/o/lwXSD0er/oTA3Hs+xPWo0cbmC/hfGxPhXra91xvvKMX6HHVJfKEZCKQBBI33mnX8pmNK8tJAxqQXJN311oDJsQ8mji2RTqJ3UqZw+Po5faUiWU25wpiztXv2UhrD0Dm2K8fMzru7KBM6Atw7KXByzY49IOclJrrsDtl/+/QmjJrVs6qDRe8rxqjzv/Q+NKIdphgXaBT/ZTn5D6aTVvxplL31obRHUOZxSKtIUlWJrzoGdyrnG7yd9bzT3gjE2bXNnNX+g6B0b7zlPiXEbzIXunX5O5HdiQ1VD4oQ2J7BlTX5W7VexUdjGvDtQXPaR16VFXyil4uLECku3ZxmlzVftuKOQtazb6ZOj990tiMUcZrmr7UngMrF075bVbuSeni3qPLYhb2zny+dIxfJJT5lwR0knbK1wg09CBXc4WyGLGtG0A49Gg45Hw/9QPVW/SvVFi+uO7OCv9VoFHm/l0c6lsJSi5RnqvvO+dBz2vU3LIcZTHZ2mCdPLKE5beQSaSmEHPBvBySBF49YftFGpO5WK52wC1Vn+tBQ3UjYqzfvCUo7Cu6XXolI91dfrF0nWLp2aE693Q0Fqg8Re2MB0smXQEUvFr2qrjpvdUgWGo77ovKToLPtiRPXeNywu9KJO9HDFrZS8BC5LvXpQGWWgRdvSCrn0aKkalIoueF6ChKys51Ze5aqjkG/ttQDKWlJBKBLGiB5kVjw+RrwTW5qzdS3Mlr3TAeo+aGKzUx+TpHZDcRE/ztmvU1fa/a6bCLSFKg6vf33Eyf/DY2ki1W1YVLGpYh6G8bIUocViyCwksjJ5SCS9esiVL2OxfHGmxuB5HrFWZTYfsPRewkEnMS9KLCekT7bUtyuJSfWLPhrPFP0/7XWQlXkI97GZ9Q3t1E5mRTRQ6lOJF1pDJSpOIG9LM6pQtOPik0Hiliea4cxakaJBC0n5Sj9GR93JxpKgUQthESV/JIFgKDkEEN82jabeeGvFaZQMvvwY+xHh9MWrhpaJ8t6nBxxGRTO0tcEkTflTLvBJnaYGXVfPV1pGbaGC7jjZfOcLBLLbaxpcV2ifvNXLePV0TaavCvRMulo62lqPJCDZ+kb8KwWF19aIf/66fVhbWXxNDmZKsuhaOjnqajdf6CbUqbDAZqbsGwzq1tCV215TtF6jJIzR4m79z70rfFLONhZpbQPLC6V5WoBfOSyDhTNAwzboZFhG71QwL/4vm6XjWDjgJObus8QcbRxh+paUlYhQqY0rqv80uOtntvz+P9pPGX4APcIWJa+jO7iLVcGbFjzQwR1vGSEvZYEoTqg5GDHXhuVNrtPhHSEp3mBH5bVuviV3/blA3g+W1xmGnDtBtLsid8MZdwjThZisKwoWFcT9bAEzL2juUiewMu57P1gT9kC3kd+ngYszTB6BTY0ZYQe+ydTI2G/dFMVN+wm7/N/3zwD6LVEhMh1MXk/B8/8q3z/9dSR5o1i0w/9PKB22ICPlZUvASfz0XyPnzxbBlvSELd0tWgp+h2Bi/wewjQFXXx+KnsW90CX2eIqAwg/JyhfyWjc3oDcMKGyJtPCyIuDqnnGT4pROo6TwhOK5Wwt0KDXBJXVCvuzNJEIkTcp7LwuaMOG1avtYgOCxk03XQWwiCKtHVFRR8nRJ56IN4BrtHWnicDuoI15AO4G3MF7/jI/+2PSqFX9yR8GQPskS21gOJB7DoJxgtQLOAwUr5jdAB/HUyMoVq4cA5YpVA65o6ZC7M04z6ytLBh7G/vg8/Zm/smc09/6/cs/KwWqoWekQmNLjo8Yh3PHoriOr7PaI0ZQHcla/b+lyhTWfOfaPaocoah9XZBCh3zVXyFrsyl5Qfh0AhWg4QEsM3Ye5akpWkibOpXTAloXimiU3uviAW3qL7PvgnITfGp7wPym06gicSp2vUu3cCJdIBlAazSD2nWLwtsCIg8geIg8Xqcesu2QXYLUHvIKHtx9NpFCVZ7wr3zwTkNJ/7GJ+//HVHoiEmz6QhKt+/7gfjY7GAAqll6dAwRzbb4MrwpNt6ngNKaxInwQLlf8dAtlPhAP+Hw5h9pYRErn0mlQ+iqUWrgWYgaZnsIoCjLO2CcIwWA5OgRN6OYTtAvqqNJzvhP9j+rSe6Th/R3T0oNCAnfLdr4yYF3oJ7FdLJOtdv29s73PjfBTpny6reuTOAq7csa1IUCUxYXhbbOEFgyKsMhDqmgGuS8DEl19obUaZy+0kKHjTULzzGxtFgLnW+cTt06E8NxJET+y/MhzCr1ZDhuuKctk6xM4eOCQKiMTtFJEl1H8VGM95AYWl04HRhTgXUwed09OdesvaQMftvlB7GE4i0xuZ1Ynfk6qgbGpBUZJQAbAPf13JRe52owqUzI9y6zSsknmvAMMNzpk4L03MUolcD4h8P6cL/hfFMuF8X69yad8R5r03jmcNI+PpuC1AgWH0PY5viKEKtWjgfBAJ8OwMtHej9W4Epeik+XmjMmLUrIE9EmcTkcCu+P/r4SsGUqpV1WKCRA7P01cSNzr8b4klqJkioIw+GkOFtcXtTUh0m5RJ4qA8ezqPK/Iev9+Y6aDLMPTri+0LLGdkr2ATN9oXC+2X3jAzQhLGesudMiEWrCf6U8oEQBigJvy0bjmBR8Zr5b/fv5GWDzrwwmrLfdDQf6hKoYdQOdA+cKE937ClcWrAfpBOyUF54/RKY8WKNOpKhZ4uSoWlMlz2Wd+UgW+j0rYvAitzForQy1EK+yMIsOWoBUbUGRKRQReoUKrQyRVOFeOCiZ77ftPfh2G/Ernc47bA6HUoWAXFqq8Tv+DaGg2fCu+9CApKMuRZ9ertM9RlNKSFcQzcxpnrx4gNJ+op7H98n9d8wYHYJtK+YbUrSrQDIFyCa2htUxsTByHjnvGIW2HJzMUmUqdObeDEXDrteWe0u+baS0V6lMuZMcLF2MYIehioizvFCudwjL4xnrLXjUaZlKe3DFwXkke1Sl8UBal9lw7T3wSgIRwyBD6GTXSR+HDexdXRXzIVk702eF4fEYoiM9WOuuqOI/gbBq5DgoiTTtfcZG9wo/y0SXSZigmKo2FC48YENk8t/K7JaMD0vn/9DUf/uKQHvo6HRF6drjGtC3gEHSworiEMxwdRN1akO7pc7EoXcceLLX2hRaJD+weGgiRVSoG0hTNORGFxJC70cqVeXcaHi/hJM0IuGwQCtY2sb9hf7Ahf7Idi1xCYk3JI8QMjzUcyXl/Y3pUIhlu8OcfTKSdyIsEXLtjTW18XxJoY5cQ65RxiSCvOCI2Pmpa3yQxCG6y4HgHn+OMZxu8HKft9AmRfdaBnxBh12eEMStuIGjRDRHeIbPjf2+IyJUE2iE7014IqsnJRRkpPv2fxnkDSiBzdpXoHPAGr1R9PSABhkMfYCzKv4iQhul7EB6IfNUFTdV4Kho6/QKxy85DIDSUT5Ie0jJd95b5QsXkiBSBgLHOAq4hD42VsBT+4zIlgX9vo+dBE9RVXRSY61kuZVUilirVQp/RGEM7oA+mviam5FaaI+3v6mPWmD85Ryo17s66uW/CFiBQ/IQISH78b+5sXwpb6CyK5MOMXWVB8FxNj7f7iKmocl9wG1rgPwsqFzU1+hOUYblBGJ3gGIqs/g7IKwnAmhMMyyqZArI+le74eXvg/qILMtAxzKcTh8D/6LPbfMT1kNaP5YFBnQW7G45aC8XRA3K090gX+bwQ41BdZUiUFXljecMqhRgHJni6ojLgKbeR7993wg8VrwPZCaT/6Q1d9MmRCueGeasJtSv88Yer/Be0WqQbBUe2YZRT0oHAxZvBoYptqDhHlFE1KEcKUIssbrfp+kUliQhTccMpJUi53KhOTIUFEObLYsTwhXv8QlFQQ1NyfO/gfOi8wuCGNdTzUCTf23wQyn59kDBz/hRCv+Tv1dqIX/ea2JM5GtZAQMcVh7lFuhXX6ZDbEA3tiD2unmZG/bkpNXrHlhQOFiYVJmXfPrUi/b+kj9bU6j7O7t1PRlOj3kzeLsa6WL6NjMUMLoz7YmuqE9Ne0Q8viMsZf+sgcj7KWmUkKdXGUntKc7lHl4OVc1EdCmEpFpnWUxaUuVFokwKJWpHO9VEzgj2dfjNZCWRy6hHAzqcnM74uEmZRB3nznQlI23H/53/eTRRZnqsfVecXk2EpXQh+kkGaiJqRc8Ses13XKsNdNoNmgMenl6XX7pmUDImKabiSpFYQ5kUXuwpn2/FWYlpKrbyoim3Ubrt3SQq9JRI3zkBAz92AOEFyjmPI9Nr4KI2QBuii+yiPwqsojVxp+j68iRXPsL0F/dT5gMbVURYvFieNHf5wHiU6BhiZ9c/LdD7AAQzMnC8/xVSVv+OqOSycLsqO08kRNFmZbhNYPSYNSQjIcWMU5H9dNaP0wlNl2GcQJG+GND+IfM+MkHxj63PCSxv6NGm521W0+WKms9GrqgWc/LjsUGjKsAgQffQ4lQuy/4yz956P9ltFhiI2riJPbavu2CZhuneRWXKaQ2ehiBuWED3zllWoyHEvAeTpDTcPqQ6vOf5T9MeXgc+0MCCMQXegICHvxjGjUSWyiNCpuakR6G/vPLCaPAdhB8R8pf7QfWHaAjz4CbeKc6HEUyTfCLksOabx5gByQgUgCz8yFAqniFF6ONUiCbmuiMKHIQ2VBmdqccq8f4BTSdgq3WDSPF7pfJ4ZBsS9K8tGOnNaJCK9LJzTZYGwubIZkruMopMX/M6OuWNoEUY9Lk1Jahfj+wRPj9g2Dw+uJvSoMAjDHx4dNhE3MdXn3Z0EH3tB/EtcbyDRxyvXQyfrFxuBA6OdKMZ5FQR9LN3FN/jeIkY/UaorKYvTak/E7IjjrRW+BpYutvjPCL4MgnuUle/FnbIodkN/KKCNIdFPIu6Gjty/skPxcbfNjigsGNNuQiPwgeDgGjnpBxmcLVpIeNOj4mIp2dr2TZ3bga3gxHsfMEQA7BTBxMhDr70airoOgegCveCUYPHD1KHJ4Ggc+0OWZRln/J1i4kZs2HzS5FZYPvpXXiDqllMibHPPx0XiVjPIsmIB/JkQjvpTxQEhRMZYErV5DbE6D8v5llr0d5Mbe8p83pBY5fj2jHuXAeic8NgaqdMD/z+kgPIji9xjYei4tABN45niW7wFv/kgUjFNJJwHinSKtnhDJkjsz0YuyG7ptKA4QSihGlgZh7hs8rhkkwodgQiCgmrwRAi9DUG1WLMcmkReEAimL8Od/IPb0eKXT64kCKKMHAgOvLYrjy1Da8S2kYBGAWcRFhf3nDlVgAb2dtNGLpBNef+z54O0tz4b5yULn5Em1oVjdprdGhjc0QuPyIyPU158WZLfuyS069rFeP3Z9NOwFO/76yAcgrkdL8qnJmoKCLrpGUa8E8/9YOyEUX9sGz0gagd1A54lJopIkP725bATldiyGuJtRSvur/hXR7wRGWvy88Sb1T5XSVEP2YqByLkKICkZTJJPnoAIzIGTQqxKSIYlagU9mPFGdXnfugcfQyxT5zHLxI+bLFLWCniJwYaMwH8K9o7iQAexCABfPZPTqvvy9NnoryO7WDqOIvO/tFpnQ6e0KFSTQ2D//3Y8cbUHZfsDxW3Fcgk+i3ltxrNHxINJ/LV5e/yryJaZQB34Njm53e0gweFwhv/bpIBzf/3n8bvsjGeVX/Jm7//73v/8D", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"COD STORE" = _t, Capacity = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"COD STORE", type text}, {"Capacity", Int64.Type}})
in
    #"Changed Type"