// WCS_Pedidos
let
    Source = Table.Combine({WCS_Pedidos_Irlanda_1, WCS_Pedidos_Irlanda_2, WCS_Pedidos_Irlanda_3, WCS_Pedidos_Irlanda_4, WCS_Pedidos_Irlanda_5, WCS_Pedidos_Irlanda_6, WCS_Pedidos_Irlanda_7, WCS_Pedidos_Irlanda_8, WCS_Pedidos_Irlanda_9, WCS_Pedidos_Irlanda_10, WCS_Pedidos_Irlanda_11, WCS_Pedidos_Irlanda_12, WCS_Pedidos_Irlanda_13, WCS_Pedidos_Irlanda_14, WCS_Pedidos_Irlanda_15, WCS_Pedidos_Irlanda_16, WCS_Pedidos_Irlanda_17, WCS_Pedidos_Irlanda_18, WCS_Pedidos_Irlanda_19, WCS_Pedidos_Irlanda_20, WCS_Pedidos_Irlanda_21, WCS_Pedidos_Irlanda_22, WCS_Pedidos_Irlanda_23, WCS_Pedidos_Irlanda_24, WCS_Pedidos_Irlanda_25, WCS_Pedidos_Irlanda_26, WCS_Pedidos_Irlanda_27, WCS_Pedidos_Irlanda_28, WCS_Pedidos_Irlanda_29, WCS_Pedidos_Irlanda_30, WCS_Pedidos_China_1, WCS_Pedidos_China_2}),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"PEDIDO", type text}, {"CANTIDAD", Int64.Type}, {"PRECIO", Currency.Type}, {"SUBPEDIDO", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"PEDIDO", "Pedido"}, {"ESTADO_PEDIDO", "Estado Pedido"}, {"FECHA_PEDIDO", "Fecha Hora Pedido"}, {"FECHA_ULTIMA_ACTUALIZACION", "Fecha Hora Última Actualización"}, {"STOREENT_ID", "ID StoreEnt"}, {"TIENDA_ONLINE", "Tienda Online"}, {"ID_XBLOCKED_STATUS_TYPE", "ID Xblocked Status Type"}, {"PARTNUMBER", "Partnumber"}, {"CANTIDAD", "Cantidad"}, {"ESTADO_SUBPEDIDO", "Estado Subpedido"}, {"PRECIO", "Precio"}, {"SUBPEDIDO", "Subpedido"}, {"ORIGEN_STOCK", "Origen Stock"}, {"FECHA_ACTUAL", "Fecha Hora Actual"}, {"PAYMENTSYSTEMNAME", "Sistema Pago"}}),
    #"Inserted Date" = Table.AddColumn(#"Renamed Columns", "Date", each DateTime.Date([Fecha Hora Pedido]), type date),
    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "Time", each DateTime.Time([Fecha Hora Pedido]), type time),
    #"Reordered Columns" = Table.ReorderColumns(#"Inserted Time",{"Fecha Hora Pedido", "Date", "Time", "Pedido", "Fecha Hora Actual", "Estado Pedido", "Fecha Hora Última Actualización", "ID StoreEnt", "Tienda Online", "ID Xblocked Status Type", "Partnumber", "Cantidad", "Estado Subpedido", "Precio", "Subpedido", "Origen Stock", "Sistema Pago"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns",{{"Date", "Fecha Pedido"}, {"Time", "Hora Pedido"}}),
    #"Inserted Date1" = Table.AddColumn(#"Renamed Columns1", "Date", each DateTime.Date([Fecha Hora Última Actualización]), type date),
    #"Inserted Time1" = Table.AddColumn(#"Inserted Date1", "Time", each DateTime.Time([Fecha Hora Última Actualización]), type time),
    #"Reordered Columns1" = Table.ReorderColumns(#"Inserted Time1",{"Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Última Actualización", "Date", "Time", "Fecha Hora Actual", "Pedido", "Estado Pedido", "ID StoreEnt", "Tienda Online", "ID Xblocked Status Type", "Partnumber", "Cantidad", "Estado Subpedido", "Precio", "Subpedido", "Origen Stock", "Sistema Pago"}),
    #"Renamed Columns2" = Table.RenameColumns(#"Reordered Columns1",{{"Date", "Fecha Última Actualización"}, {"Time", "Hora Última Actualización"}}),
    #"Inserted Date2" = Table.AddColumn(#"Renamed Columns2", "Date", each DateTime.Date([Fecha Hora Actual]), type date),
    #"Inserted Time2" = Table.AddColumn(#"Inserted Date2", "Time", each DateTime.Time([Fecha Hora Actual]), type time),
    #"Reordered Columns2" = Table.ReorderColumns(#"Inserted Time2",{"Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Última Actualización", "Fecha Última Actualización", "Hora Última Actualización", "Fecha Hora Actual", "Date", "Time", "Pedido", "Estado Pedido", "ID StoreEnt", "Tienda Online", "ID Xblocked Status Type", "Partnumber", "Cantidad", "Estado Subpedido", "Precio", "Subpedido", "Origen Stock", "Sistema Pago"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Reordered Columns2",{{"Date", "Fecha Actual"}, {"Time", "Hora Actual"}}),
    #"Inserted Time Subtraction" = Table.AddColumn(#"Renamed Columns3", "Tiempo Último Estado", each [Fecha Hora Actual] - [Fecha Hora Última Actualización], type duration),
    #"Resta de hora insertada" = Table.AddColumn(#"Inserted Time Subtraction", "Tiempo Vida Pedido", each [Fecha Hora Actual] - [Fecha Hora Pedido], type duration),
    #"Reordered Columns3" = Table.ReorderColumns(#"Resta de hora insertada",{"Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Última Actualización", "Fecha Última Actualización", "Hora Última Actualización", "Fecha Hora Actual", "Fecha Actual", "Hora Actual", "ID StoreEnt", "Tienda Online", "Origen Stock", "ID Xblocked Status Type", "Pedido", "Estado Pedido", "Subpedido", "Estado Subpedido", "Partnumber", "Cantidad", "Precio", "Sistema Pago", "Tiempo Vida Pedido", "Tiempo Último Estado"}),
    #"Inserted Total Seconds" = Table.AddColumn(#"Reordered Columns3", "Total Seconds", each Duration.TotalSeconds([Tiempo Último Estado]), type number),
    #"Inserted Round Down" = Table.AddColumn(#"Inserted Total Seconds", "Round Down", each Number.RoundDown([Total Seconds]), Int64.Type),
    #"Removed Columns" = Table.RemoveColumns(#"Inserted Round Down",{"Total Seconds"}),
    #"Renamed Columns4" = Table.RenameColumns(#"Removed Columns",{{"Round Down", "Segundos Último Estado"}}),
    #"Total de segundos insertados" = Table.AddColumn(#"Renamed Columns4", "Total de segundos", each Duration.TotalSeconds([Tiempo Vida Pedido]), type number),
    #"Redondeo hacia abajo insertado" = Table.AddColumn(#"Total de segundos insertados", "Redondear a la baja", each Number.RoundDown([Total de segundos]), Int64.Type),
    #"Columnas quitadas" = Table.RemoveColumns(#"Redondeo hacia abajo insertado",{"Total de segundos"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"Redondear a la baja", "Segundos Tiempo Vida Pedido"}}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Columnas con nombre cambiado",{"Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Última Actualización", "Fecha Última Actualización", "Hora Última Actualización", "Fecha Hora Actual", "Fecha Actual", "Hora Actual", "ID StoreEnt", "Tienda Online", "Origen Stock", "ID Xblocked Status Type", "Pedido", "Estado Pedido", "Subpedido", "Estado Subpedido", "Partnumber", "Precio", "Sistema Pago", "Tiempo Vida Pedido", "Tiempo Último Estado", "Segundos Tiempo Vida Pedido", "Segundos Último Estado"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns4", "Fulfillment", each if Text.Contains([Tienda Online], "XZ") then "Zalando Fulfillment" else "Inditex Fulfillment"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Fulfillment", type text}}),
    #"Reordered Columns5" = Table.ReorderColumns(#"Changed Type1",{"Fecha Pedido", "Hora Pedido", "Fecha Última Actualización", "Hora Última Actualización", "Fecha Actual", "Hora Actual", "ID StoreEnt", "Tienda Online", "Origen Stock", "ID Xblocked Status Type", "Pedido", "Estado Pedido", "Subpedido", "Estado Subpedido", "Partnumber", "Precio", "Tiempo Último Estado", "Fulfillment"}),
    #"Columna condicional agregada" = Table.AddColumn(#"Reordered Columns5", "Tipo Tienda Online", each if Text.Contains([Tienda Online], "UterqueX") then "Marketplace" else "No Marketplace"),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"Tipo Tienda Online", type text}}),
    #"Columna condicional agregada1" = Table.AddColumn(#"Tipo cambiado", "Estado Pedido Mapeado", each if [Estado Pedido] = "M" then "Creado" else if [Estado Pedido] = "F" then "Creado" else if [Estado Pedido] = "G" then "En almacén" else if [Estado Pedido] = "R" then "Expedido" else if [Estado Pedido] = "S" then "Expedido" else if [Estado Pedido] = "D" then "Expedido" else if [Estado Pedido] = "U" then "Expedido" else if [Estado Pedido] = "K" then "Entregado" else if [Estado Pedido] = "O" then "Entregado" else if [Estado Pedido] = "X" then "Cancelado" else if [Estado Pedido] = "N" then "Cancelado" else if [Estado Pedido] = "E" then "Bloqueado" else if [Estado Pedido] = "L" then "Inventario insuficiente" else if [Estado Pedido] = "T" then "Rechazado" else if [Estado Pedido] = "PQ" then "Pendiende confirmación de pago" else if [Estado Pedido] = "A" then "Fraude" else "DESCONOCIDO"),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columna condicional agregada1",{{"Estado Pedido Mapeado", type text}}),
    #"Columna condicional agregada2" = Table.AddColumn(#"Tipo cambiado1", "Estado Subpedido Mapeado", each if [Estado Subpedido] = "M" then "Creado" else if [Estado Subpedido] = "F" then "Creado" else if [Estado Subpedido] = "G" then "En almacén" else if [Estado Subpedido] = "R" then "Expedido" else if [Estado Subpedido] = "S" then "Expedido" else if [Estado Subpedido] = "D" then "Expedido" else if [Estado Subpedido] = "U" then "Expedido" else if [Estado Subpedido] = "K" then "Entregado" else if [Estado Subpedido] = "O" then "Entregado" else if [Estado Subpedido] = "X" then "Cancelado" else if [Estado Subpedido] = "N" then "Cancelado" else if [Estado Subpedido] = "E" then "Bloqueado" else if [Estado Subpedido] = "L" then "Inventario insuficiente" else if [Estado Subpedido] = "T" then "Rechazado" else if [Estado Subpedido] = "A" then "Fraude" else "DESCONOCIDO"),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columna condicional agregada2",{{"Estado Subpedido Mapeado", type text}}),
    #"Columnas quitadas1" = Table.RemoveColumns(#"Tipo cambiado2",{"Tipo Tienda Online"})
in
    #"Columnas quitadas1"