// Store_Stock_Marketplaces_Irlanda
let
    Origen = Oracle.Database("PTR", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - PTR - STOCK DISPONIBLE - STORE STOCK MARKETPLACES - BERSHKA - IRLANDA#(lf)SELECT#(lf)  MERCADO_VENTA,#(lf)  COD_TIENDA AS TIENDA,#(lf)  ID_CADENA AS CADENA,#(lf)  SKU,#(lf)  UNIDADES,#(lf)  UNIDADES_RESERVADA,#(lf)  DESCRIPCION_CAMPANA || ANO_CAMPANA AS CAMPANA,#(lf)  ID_TIPO_SECCION ||' - '||DESCRIPCION_SECCION AS SECCION,#(lf)  ID_PRODUCTO ||' - '||DESCRIPCION_PRODUCTO AS PRODUCTO,#(lf)  COD_SUBFAMILIA ||' - '||DESCRIPCION_SUBFAMILIA AS SUBFAMILIA,#(lf)  UBICACION_STOCK,#(lf)  RELACION,#(lf)  ESTADO,#(lf)  FILTRO_CIS,#(lf)  FILTRO_INDOM,#(lf)  BLOQUEO_INSUFICIENTE,#(lf)  TIPO_ORIGEN_STOCK,#(lf)  DESCRIPCION,#(lf)  PAIS#(lf)FROM AAP_INDOM_ITX.STOCK_TIENDA_MARKETPLACES#(lf)WHERE#(lf)  ID_CADENA = 4 -- BERSHKA", CommandTimeout=#duration(0, 4, 0, 0)]),
    #"Columna condicional agregada" = Table.AddColumn(Origen, "Tipo Origen Stock", each if [TIPO_ORIGEN_STOCK] = "Almacen" then "Almacén" else if [TIPO_ORIGEN_STOCK] = "Plataforma Consolidacion" then "Plataforma consolidación" else if [TIPO_ORIGEN_STOCK] = "Almacen parcial" then "Almacén parcial" else if [TIPO_ORIGEN_STOCK] = "Caja Stock Unificado" then "Caja de stock unificado" else [TIPO_ORIGEN_STOCK]),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"Tipo Origen Stock", type text}, {"CADENA", Int64.Type}, {"UNIDADES", Int64.Type}, {"UNIDADES_RESERVADA", Int64.Type}}),
    #"Personalizada agregada" = Table.AddColumn(#"Tipo cambiado", "Localización", each if Text.Contains([TIENDA], "CAJA") then [TIENDA] else [TIENDA] & " " & Text.AfterDelimiter([DESCRIPCION],"Uterqüe ")),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Localización", type text}}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado1",{"TIPO_ORIGEN_STOCK", "DESCRIPCION", "CADENA"}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas quitadas",{"SKU", "UNIDADES", "UNIDADES_RESERVADA", "CAMPANA", "SECCION", "PRODUCTO", "SUBFAMILIA", "ESTADO", "RELACION", "FILTRO_INDOM", "FILTRO_CIS", "BLOQUEO_INSUFICIENTE", "Tipo Origen Stock", "UBICACION_STOCK", "TIENDA", "Localización", "PAIS"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"UNIDADES", "Unidades Ofertables"}, {"UNIDADES_RESERVADA", "Unidades Reservadas"}, {"CAMPANA", "Campaña"}, {"SECCION", "Sección"}, {"PRODUCTO", "Producto"}, {"SUBFAMILIA", "Subfamilia"}, {"ESTADO", "Estado"}, {"RELACION", "Relación"}, {"FILTRO_INDOM", "Filtro INDOM"}, {"FILTRO_CIS", "Filtro CIS"}, {"BLOQUEO_INSUFICIENTE", "Bloqueo Stock Insuficiente"}, {"UBICACION_STOCK", "Estado del Inventario"}, {"TIENDA", "Código Origen Stock WCS"}, {"PAIS", "Mercado Localización"}, {"MERCADO_VENTA", "Mercado Disponible"}})
in
    #"Columnas con nombre cambiado"