// Equivalences_Payment_Type
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rVzBbuPIEf2VxpzX1mIRIGeKom2OJJKQKNnryRxoqW0xQ5FeinLWe84PLJLFIkCQZLEBgj3vJ/iub0qTFKWuZlNVpHzx2J73Hpvd1VXV1SV/+vRhGsZsyR/DOEw/fFX8FMaPSboOFuHb73H3X33+6tMHY2zd6eFmkC6CTSC+84P0zzwLWI+ZK/7dljPxu4JXCDzmA8teO4lU3EIoCp+DBhkveEpY6CVL8b0V8UWWJnG4SHKJkpULmO4AZ5eg/GtOGYSbRfLCG6b19OAP3FzoOnzMBHzZRejAzYU+mv0uGjktp4+DTcbTriOR2LmYF7x6QdR2RQTrWbBygbk9NbqMo+AVI/jmD134OS2nD6MgjYMuCntmaSMxTzdmtH3oZiUHdi42i8Mk9prM/LTUgZsL3fLFKsjars0tN3NWMbXu1PYbtv6p/9N6kQPBuLqyHdv/VhbR7vwKB9mlMzrNrBwPYDHjzp5SqCWwznfjSKwUSWEPBRr9RLjoP22//vqbPwb7hTkpVMMDNTNYP4QJ8y8n/CmIEkxMhStaacZZP+Jb9O1kqEbDjpdhxr+nqVRgRWezkunWozDO8CWRv4WEQhV9YokCzIHtWBPUIvYoyDzGhNNc2f8fX2k8J9niAVdjTw1nykzX8Q3Tp6gAPFRbrC7FQgiXHnPUIiEY6hyXib50ewNg+1h08tkAC1TKcHiSXIW+I+iSTS6ZtUjWa54uUOtR4VBrT7jv9+cGqgTAOp0NuzeviTIlFqjMk+1ixVPSnAIsUAnj2yCKeMYo7haCG3SOKSBRS877apSE5IoVtFYpJblPBQ2UxsbUtyamMRlgKhJSO5bgIYnJQynB+tmeh0WGQJvpAtw8HsZN6i5poJ2Y9/biNZ5+Bso0dUHYBDoK3FFBxJlpoptpD9NF6Y1IiLJw8QV3sXUC1Mt9uOPbrdzsPsU+PfpDOn1IVwzHdMcGGl8OOG2Sx4yRd2MwARpiQjoK3Gi7n3b/3f2y+1l8/bHVDIwNa+pPXHx/ljA45cbEN9jYdSwfnUWABSp3a+GsKT75CISjmHnowwUEclIuYmZvwB/CjOV2TXSbjTygPkm2IiTHT2wZPj7ylMf4HtZRgOZ1mCb5A8cB32TpvDwEnZTUMODKF5uaNPMyFO6EIP0hWEXb+Kmd0YVZkD5wkbWkF8M84UUHUCPAbSz8dC//wqoDG7qp64z6qYZmEzJUm8NRXC3AQmPi2TaNSSIyVDcS2lxD8Olt03q/KHaQPIQiNIifUQM4IoGClybrJBMne9JwFLQ+PnLzUhzR6UvXTNQebYhWpcIVZ1DWvOhpuoYBFMtTOel9ZagSgcdeHoLbReB9ok15MsDCRyfr5yyIs1aPNo3pTSuC9f1iFcRPnIkcLuULHj7j50INBS6l67/97XZoMG/kdBtMSD2i1ggNuTqxmlMnKIWAvHTH8tod0eQ1DH2lqo1jbtxDpU8q9gTtfesEnSG325Z6Ui1FJY5QhmrKOcwczdB6gAzV29tfwmzVZQeoPKA+LLP3VjsgT4PF+loeJRGvkHBexO/dCUqvYLrzRqsRz64+9sazK7SGccDB9525jo2+agFS5mlyb9yMZs51q8FaZm9s9uZ2j1BFAljo3+yJm/uI8gAx9wy0uK1haBxVz5qVMJqbOsJ1G4PoAAC4tkl7xfazRpYpDkoOJqZhwHuFG9fzbOeamZYjxs/m7sy8sSaYbBMNBvuJbaInvhIELaIYqW0Wxzh0HRW0YhXOxELnaI+CWwitNszM0zNpjEYstwQ052wmQn3DnuLrvUdBF8LzSHxxvc02IgpQjp81ApzVmT8Vq207F0Nx2rbQ6VXgSkYVZ8GyXdH6IEh/tPLUgdW3cXdcgHTpK9UnqHCtlskG9sTCbxFqeJ0apdAkQ6GFmdU+Zre2f8PMG8O5Rue4gaUrOWJSFUwfH8a9Ye8Kv7JR4DC1I9bA9aVvY43fqxUYaGtvv0dByjetTPzoEwhmBsHaY899kKKzD7Balb7Im1dfyEIVXKs1zdJgGb4EabjdUAUBR2f+lLsSGarTED/7pGmv4aHZbtN2Xq3alheE3AVgdSofrdHYHaFZnIJujmcTq6UlShyYgL/91c/9cbtDaOuUpyHbqXzoQGQLtIK0hqFefRLTOgmp3RDu62aFXj1BcK04STyxylBNrdakF6rrBM3hl1JzaSrdHXKQi/yfL2jAV+ANo6FWCk7X34v7phe+ybbCI+FLB9EN806fcF0ZBH2hEgUzsIk1wJOhPUp3tbbk5PYFDaPZe41sZqBHWA1Du7u8bRT1eYD2i9TwWjWxCptwnQy2WRZSFQEH5hUjW/H5jd2TR87YEmcew2HWnTexppSuKojX3c6RK3IADWeIEL3qZ+3iBpPUSyMhYbRyB9adyywREfHJgGCgc3vJ7pN4KdbLJ90W1/Aw2olQx2Zj35iJYwgmBcHw7WZi0cYWM24pQRiAdbPkGZ5NOOMDcN2Tkrwn5N24vjsX+VKr4L/f4jPHdh1GT46OeGhqKd/GYfyEt45JSOj2bN+m3KYfcLU7lX1jAeP7miUa1XQceMBKgxce5XcWK75Ao6SC1naHCB+95JvFlscZuSEGcLSOcya8/nd4r6AKh6WZdUZvmINgeFs5NBw0/ytBSkXWxTsBcozOiv1b26Ee9UssvIcU9jS08yqxjyb3AFs7UtPSXwkJ56BELIIlD7boZACwNoxRw5f2zpqSN8lQNXES+WLLs5r3lCXMt67QJahw9bwxy7sm0H1wRMItsI8S7NrK61vOsI/OoI6iZHNp9vZr0qaBWIZDA7srq0BFRcid+cy3zaGFN8o20HQXiJc9WvOwCofBYGKJMCGeiAZDCak4XsIy+vUV3P1v99vul90/dr+y3Y+7/+z+vfv77ifx4792P2Nqp6gwl7HEdKKTvkcpm2IT81f2tBXHFWajGYcK16wXbZmU1XHntAr6EahpI0ENuURB+/XwOqOnPK3INwjpyQEHM6Np36S9rIRUqrcX1sU4EQuBKUhIJbh8S8mvKpjOYl6CaEtr76gTYOZc9PGJRPbecnz3FlNT4brkg5h0lNzg1cj8MGr6XNVh0qkfvZH0un36RhZo9QEcidj+4xYS+X0+9SALtvnAgsSrHta121+SOrfJXit1Xp+9JNm9rV03ro4d6Tqpd2jtlmRbdVRLvHZN1RKxW1+1POKzGpJloRY9xRLtvI5PSej8tkadebxzZ6Pig85tbpTk3q+/URI9p8UR7IoWXY7yrjir0VGe63dq/FMC1/mddfWXfbdmON3rv2sfmuyFWrZZAQfWqtOqbpxnNTBo5M7rYagLdmpjqMt0ug6uy3jn3QjLRkW9FNZMSbd74brQGVfDmpU//yZV9sfvcNnX9MJn3SYpMeP96reyc8w/c4V6xAKUU6ussetfkQD8WiFIrNP6OUpe335D8xOIhgWIUDg/Qhw64OAhnOikVO/kxgMehS88JfyZEviHRuBytL+UI19RNNxNzDx0W+aQWhTs8PHI+nnqzE89D0y8fbfAwBJPEr8y/GqsgsES2j9bfxpRPgu3qfvKTuXxUU1dNDZWoT5//j8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#"Tipo Pago Ecommerce" = _t, #"Tipo Pago Ipod Ecommerce" = _t, #"Dispositivo de Pago " = _t, #"Tipo  de Pago " = _t, #"Medio de Pago " = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Tipo Pago Ecommerce", type text}, {"Tipo Pago Ipod Ecommerce", type text}, {"Dispositivo de Pago ", type text}, {"Tipo  de Pago ", type text}, {"Medio de Pago ", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Tipo Pago Ecommerce", "Ecommerce Payment Type"}, {"Tipo Pago Ipod Ecommerce", "Ipod Payment Type"}, {"Dispositivo de Pago ", "Payment Device"}, {"Tipo  de Pago ", "Payment Type"}, {"Medio de Pago ", "Payment Method"}}),
    #"Merged Columns" = Table.CombineColumns(#"Renamed Columns",{"Ecommerce Payment Type", "Ipod Payment Type"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"Ecommerce Payment Type - Ipod Payment Type")
in
    #"Merged Columns"