// Market_Store
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - OMNICHANNEL - ZARA - SINT VERSION DRIVE - MARKET, STORE AND BRAND#(lf)SELECT DISTINCT #(lf)#(tab)dp.PAIS country,#(lf)    dp.PAIS_ISO ISO,#(lf)#(tab)dp.DESCRIPCION market,#(lf)#(tab)dp.DESCRIPCION_INGLES market_english,#(lf)#(tab)dl.DESCRIPCION physical_store,#(lf)        dl.DESCRIPCION_DB2 descripcion_db2,#(lf)#(tab)dl.LOCALIZACION,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN dl.ID_CADENA IN (1, 2) THEN 'ZARA'#(lf)#(tab)#(tab)ELSE 'KIDDY''S CLASS'#(lf)#(tab)END AS brand#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)#(tab)ON (dp.ID_PAIS = mf.ID_PAIS)#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl#(lf)#(tab)ON (dl.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING)#(lf)#(tab)#(tab)AND (dl.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121, 6)) -- SINT TRANSACTION#(lf)WHERE #(lf)#(tab)mf.ID_CADENA IN (1, 2) -- ZARA Y ZARA SUR (CON KIDDY'S CLASS INCLUIDAS EN ZARA)#(lf)#(tab)AND mf.ID_TIPO_MOVIMIENTO IN (72, 772) -- ORDER TRANSACTION#(lf)#(tab)AND mf.ESTADO NOT IN ('X', 'M') -- DRIVE #(lf)#(tab)AND mf.REPOSICION = 0 -- DRIVE#(lf)        AND mf.ES_CAMBIO = 0 -- EVITAR CARGAR CAMBIOS COMO SINT#(lf)#(tab)AND mf.ID_SECCION > 0 -- DRIVE#(lf)#(tab)AND mf.ID_PAIS > 0 -- DRIVE#(lf)        AND dl.LOCALIZACION > 0 -- QUITAMOS LOS ""NO TIENE""#(lf)        AND dp.PAIS IN (70 , 4 , 43 , 632 , 208 , 528 , 77 , 800 , 38 , 78 , 640 , 2 , 93 , 508 , 68 , 404 , 11 , 512 , 600 , 480 , 436 , 92 , 8 , 220 , 428 , 647 , 63 , 91 , 11 , 53 , 32 , 1 , 76 , 9 , 416 , 3 , 64 , 664 , 7 , 24 , 624 , 5 , 628 , 79 , 95 , 636 , 54 , 604 , 55 , 18 , 96 , 46 , 204 , 101 , 97 , 432 , 28 , 804 , 649 , 60 , 10 , 644 , 61 , 6 , 66 , 75 , 98 , 388 , 30 , 39 , 680 , 212 , 52 , 72 , 524 , 400)#(lf)ORDER BY #(lf)#(tab)dl.LOCALIZACION ASC"]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MARKET", type text}, {"LOCALIZACION", type text}, {"COUNTRY", Int64.Type}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",",","",Replacer.ReplaceText,{"MARKET", "MARKET_ENGLISH"}),
    #"Added Custom" = Table.AddColumn(#"Replaced Value", "Store Description", each if [PHYSICAL_STORE] = "NO TIENE" then "NO TIENE" else  Text.PadStart(Text.BeforeDelimiter([PHYSICAL_STORE], " -"), 5, "0") & " - " & Text.AfterDelimiter([PHYSICAL_STORE], "- ")),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Store Description", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"PHYSICAL_STORE"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"MARKET", "Market"}, {"COUNTRY", "Country"}, {"MARKET_ENGLISH", "Market English"}, {"LOCALIZACION", "Location"}, {"BRAND", "Brand"}, {"DESCRIPCION_DB2", "Store Description Logistics"}}),
    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "Market - Store", each [Market English] & " - " & [Store Description], type text),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Store Location", each if [Location] = "0" then "DOES NOT HAVE" else Text.PadStart([Location],5,"0"), type text),
    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom2",{"Location"}),
    #"Columna combinada insertada" = Table.AddColumn(#"Removed Columns1", "ID Country-Store", each Text.Combine({Text.From([Country], "es-ES"), "-", [Store Location]}), type text),
    #"Added Conditional Column" = Table.AddColumn(#"Columna combinada insertada", "Pack Store", each if Text.Contains([Store Description Logistics], "PACK STORE") then "PACK STORES" else "NO PACK STORES", type text),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Conditional Column",{"ID Country-Store", "Country", "Market", "Market English", "Store Location", "Store Description", "Store Description Logistics", "Market - Store", "Brand", "Pack Store"}),
    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns", each ([#"Market - Store"] <> "FRANCE - 00160 - BCN-P. GRACIA" and [#"Market - Store"] <> "GERMANY - 06479 - MAD-SERRANO" and [#"Market - Store"] <> "FINLAND - 06659 - S.SEB-N.MERCADO") and ([Store Location] <> "06739" and [Store Location] <> "09323" and [Store Location] <> "09334" and [Store Location] <> "09335" and [Store Location] <> "09385" and [Store Location] <> "09467" and [Store Location] <> "09673" and [Store Location] <> "09677" and [Store Location] <> "09686" and [Store Location] <> "09740" and [Store Location] <> "09780" and [Store Location] <> "09799" and [Store Location] <> "10348" and [Store Location] <> "10349" and [Store Location] <> "10715" and [Store Location] <> "10800" and [Store Location] <> "11182" and [Store Location] <> "11185" and [Store Location] <> "11218" and [Store Location] <> "11221" and [Store Location] <> "11222" and [Store Location] <> "11245" and [Store Location] <> "11274" and [Store Location] <> "11458" and [Store Location] <> "11462" and [Store Location] <> "13027" and [Store Location] <> "13105" and [Store Location] <> "13108" and [Store Location] <> "13109" and [Store Location] <> "13110" and [Store Location] <> "13111" and [Store Location] <> "13112" and [Store Location] <> "13144" and [Store Location] <> "13154" and [Store Location] <> "13155" and [Store Location] <> "13400" and [Store Location] <> "13431" and [Store Location] <> "13434" and [Store Location] <> "14251" and [Store Location] <> "14374" and [Store Location] <> "14377")),
    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows", {"Store Location"}, #"Store Capacity", {"COD STORE"}, "Store Capacity", JoinKind.LeftOuter),
    #"Expanded {0}" = Table.ExpandTableColumn(#"Merged Queries", "Store Capacity", {"Capacity"}, {"Store Capacity"})
in
    #"Expanded {0}"