// Zara_SINT
let
    Source = Table.Combine({Zara_SINT_BF_LAST, Zara_SINT_BF_CURRENT}),
    #"Removed Columns" = Table.RemoveColumns(Source,{"STATUS_EQUIVALENTE"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"COD_PAIS", Int64.Type}, {"UNITS", Int64.Type}, {"ID_TIPO_OPERATIVA_PEDIDO", Int64.Type}, {"STORE_CODE", type text}, {"ORDER_CODE", type text}, {"BLOQUEO_PEDIDO_TRANSPORTISTA", type logical}, {"BLOQUEO_DOCUMENTACION", type logical}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","","No informado",Replacer.ReplaceValue,{"CANCEL_REASON"}),
    #"Merged Queries" = Table.NestedJoin(#"Replaced Value",{"COD_PAIS"},Countries,{"Country"},"Countries",JoinKind.LeftOuter),
    #"Expanded Countries" = Table.ExpandTableColumn(#"Merged Queries", "Countries", {"English Description"}, {"English Description"}),
    #"Added Custom" = Table.AddColumn(#"Expanded Countries", "Store Location", each Text.PadStart([STORE_CODE], 5, "0"), type text),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Store Description", each [Store Location] & " - " & [STORE], type text),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "ID Country-Store", each Text.Combine({Text.From([COD_PAIS], "es-ES"), "-", [Store Location]}), type text),
    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom2",{"STORE", "STORE_CODE"}),
    #"Added Custom Operation Type PAT" = Table.AddColumn(#"Removed Columns1", "Operation Type", each if [ID_TIPO_OPERATIVA_PEDIDO] = 3 then "PAT" else "SINT", type text),
    #"Removed Columns2" = Table.RemoveColumns(#"Added Custom Operation Type PAT",{"ID_TIPO_OPERATIVA_PEDIDO"}),
    #"Added Custom Diff Total Preparation" = Table.TransformColumns(Table.AddColumn(#"Removed Columns2", "Diff Date Total Preparation", each Duration.TotalDays([LOCAL_EXPEDITION_DATE] - [LOCAL_PURCHASE_DATE]), Int64.Type), {{"Diff Date Total Preparation", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Reception" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Total Preparation", "Diff Date Reception", each Duration.TotalDays([LOCAL_RECEPTION_DATE] - [LOCAL_PURCHASE_DATE]), Int64.Type), {{"Diff Date Reception", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Picking" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Reception", "Diff Date Picking", each Duration.TotalDays([LOCAL_PICKING_END_DATE] - [LOCAL_RECEPTION_DATE]), Int64.Type), {{"Diff Date Picking", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Packing" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Picking", "Diff Date Packing", each Duration.TotalDays([LOCAL_PACKING_DATE] - [LOCAL_PICKING_END_DATE]), Int64.Type), {{"Diff Date Packing", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Expedition" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Packing", "Diff Date Expedition", each Duration.TotalDays([LOCAL_EXPEDITION_DATE] - [LOCAL_PACKING_DATE]), Int64.Type), {{"Diff Date Expedition", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Total Rejection" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Expedition", "Diff Date Total Rejection", each Duration.TotalDays([LOCAL_REJECTION_DATE] - [LOCAL_RECEPTION_DATE]), Int64.Type), {{"Diff Date Total Rejection", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Rejection" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Total Rejection", "Diff Date Rejection", each Duration.TotalDays([LOCAL_REJECTION_DATE] - [LOCAL_PICKING_END_DATE]), Int64.Type), {{"Diff Date Rejection", each Number.Round(_, 2), type number}}),
    #"Split Column by Delimiter" = Table.SplitColumn(Table.TransformColumnTypes(#"Added Custom Diff Date Rejection", {{"LOCAL_PACKING_DATE", type text}}, "es-ES"), "LOCAL_PACKING_DATE", Splitter.SplitTextByDelimiter(" ", QuoteStyle.None), {"PACKING_DATE", "PACKING_TIME"}),
    #"Added Conditional Column Packaging Date Pending" = Table.AddColumn(#"Split Column by Delimiter", "Packaging Date Pending", each if [PACKING_DATE] = null then "Pending to Pack" else [PACKING_DATE], type text),
    #"Inserted Time" = Table.AddColumn(#"Added Conditional Column Packaging Date Pending", "LOCAL_PURCHASE_TIME", each DateTime.Time([LOCAL_PURCHASE_DATE]), type time),
    #"Inserted Time1" = Table.AddColumn(#"Inserted Time", "LOCAL_RECEPTION_TIME", each DateTime.Time([LOCAL_RECEPTION_DATE]), type time),
    #"Inserted Time2" = Table.AddColumn(#"Inserted Time1", "LOCAL_EXPEDITION_TIME", each DateTime.Time([LOCAL_EXPEDITION_DATE]), type time),
    #"Inserted Time3" = Table.AddColumn(#"Inserted Time2", "LOCAL_REJECTION_TIME", each DateTime.Time([LOCAL_REJECTION_DATE]), type time),
    #"Inserted Time4" = Table.AddColumn(#"Inserted Time3", "LOCAL_CANCELLATION_TIME", each DateTime.Time([LOCAL_CANCELLATION_DATE]), type time),
    #"Inserted Time5" = Table.AddColumn(#"Inserted Time4", "LOCAL_PICKING_START_TIME", each DateTime.Time([LOCAL_PICKING_START_DATE]), type time),
    #"Inserted Time6" = Table.AddColumn(#"Inserted Time5", "LOCAL_PICKING_END_TIME", each DateTime.Time([LOCAL_PICKING_END_DATE]), type time),
    #"Changed Type5" = Table.TransformColumnTypes(#"Inserted Time6",{{"LOCAL_PURCHASE_DATE", type date}, {"LOCAL_RECEPTION_DATE", type date}, {"PACKING_DATE", type date}, {"PACKING_TIME", type time}, {"LOCAL_EXPEDITION_DATE", type date}, {"LOCAL_REJECTION_DATE", type date}, {"LOCAL_CANCELLATION_DATE", type date}, {"LOCAL_PICKING_START_DATE", type date}, {"LOCAL_PICKING_END_DATE", type date}}),
    #"Added Conditional Column Shipping type" = Table.AddColumn(#"Changed Type5", "Shipping Type", each if [LOCALIZACION_ENTREGA] = "Domicilio" then "Home Delivery" else if [COURIER] = "MY STORE" then "My Store" else "Other Store", type text),
    #"Added Conditional Column Equivalent Status" = Table.AddColumn(#"Added Conditional Column Shipping type", "Equivalent Status", each if ([STATUS] = "EXPEDITED" or [STATUS] = "TRANSFERRED") then "Shipped" else if ([STATUS] = "PACKED" or [STATUS] = "READY_FOR_TRANSFER") then "Packed" else if ([STATUS] = "RECEIVED" or [STATUS] = "RESERVED") then "Received" else if ([STATUS] = "ANNULED" and [CANCEL_REASON] = "Anulación Cliente") then "Customer Canceled" else if [STATUS] = "ANNULED" then "Rejected" else if ([STATUS] = "INCOMPLETE" or [STATUS] = "READY_FOR_PACKING" or [STATUS] = "IN PICKING" or [STATUS] = "ITEMS_COLLECTED" or [STATUS] = "PICKING_COMPLETE" or [STATUS] = "PARTIALLY_PICKED") then "Picking Process" else "DESCONOCIDO", type text),
    #"Merged Queries1" = Table.NestedJoin(#"Added Conditional Column Equivalent Status", {"ORDER_CODE", "ID Country-Store"}, Zara_Cronos_Last30, {"Código Pedido", "ID Country-Store"}, "Zara_Cronos_Last30", JoinKind.LeftOuter),
    #"Expanded {0}" = Table.ExpandTableColumn(#"Merged Queries1", "Zara_Cronos_Last30", {"Fecha Límite Entrega", "Fecha Límite Entrega Table", "Ordenar Fecha Límite Entrega Table", "Fecha Límite Expedición", "Fecha Límite Expedición Table", "Ordenar Fecha Límite Expedición Table"}, {"Max Delivery Date CRONOS", "Max Delivery Date Table CRONOS", "Ordenar Max Delivery Date Table CRONOS", "Max Expedition Date CRONOS", "Max Expedition Date Table CRONOS", "Ordenar Max Expedition Date Table CRONOS"}),
    #"Renamed Columns" = Table.RenameColumns(#"Expanded {0}",{{"COD_PAIS", "Country"}, {"ORDER_CODE", "Order Code"}, {"UNITS", "Units"}, {"LOCAL_PURCHASE_DATE", "Local Purchase Date"}, {"LOCAL_RECEPTION_DATE", "Local Reception Date"}, {"PACKING_DATE", "Local Packaging Date"}, {"LOCAL_EXPEDITION_DATE", "Local Expedition Date"}, {"LOCAL_REJECTION_DATE", "Local Rejection Date"}, {"LOCAL_CANCELLATION_DATE", "Local Cancellation Date"}, {"LOCAL_PICKING_START_DATE", "Local Picking Start Date"}, {"LOCAL_PICKING_END_DATE", "Local Picking End Date"}, {"FECHA_HORA_MAXIMA_PREPARACION", "Max Preparation Date Time"}, {"STATUS", "Status"}, {"CANCEL_REASON", "Cancel Reason"}, {"COURIER", "Courier"}, {"LOCALIZACION_ENTREGA", "Delivery Location"}, {"DROP_POINT", "Drop Point"}, {"FAST_SINT", "Fast Sint"}, {"BUNDLES", "Bundles"}, {"BUNDLES_SIZE", "Bundles Size"}, {"TOTAL_IMPORT", "Total Import"}, {"CURRENCY", "Currency"},{"LOCAL_PURCHASE_TIME", "Local Purchase Time"}, {"LOCAL_RECEPTION_TIME", "Local Reception Time"}, {"PACKING_TIME", "Local Packaging Time"}, {"LOCAL_EXPEDITION_TIME", "Local Expedition Time"}, {"LOCAL_REJECTION_TIME", "Local Rejection Time"}, {"LOCAL_CANCELLATION_TIME", "Local Cancellation Time"}, {"LOCAL_PICKING_START_TIME", "Local Picking Start Time"}, {"LOCAL_PICKING_END_TIME", "Local Picking End Time"},  {"BLOQUEO_PEDIDO_TRANSPORTISTA", "Courier Lock"}, {"BLOQUEO_DOCUMENTACION", "Documentation Lock"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Order Code", "Country", "English Description", "Store Location", "Store Description", "ID Country-Store", "Status", "Equivalent Status", "Cancel Reason", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "Local Picking Start Time", "Local Picking End Date", "Local Picking End Time", "Local Packaging Date", "Local Packaging Time", "Packaging Date Pending", "Local Expedition Date", "Local Expedition Time", "Local Rejection Date", "Local Rejection Time", "Local Cancellation Date", "Local Cancellation Time", "Max Preparation Date Time","Max Delivery Date CRONOS", "Max Delivery Date Table CRONOS", "Ordenar Max Delivery Date Table CRONOS", "Max Expedition Date CRONOS", "Max Expedition Date Table CRONOS", "Ordenar Max Expedition Date Table CRONOS","Units", "Total Import", "Currency", "Operation Type", "Fast Sint", "Shipping Type", "Delivery Location", "Courier", "Drop Point", "Bundles", "Bundles Size", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Diff Date Rejection",  "Courier Lock", "Documentation Lock"})
in
    #"Reordered Columns"