// Zara_Cronos_Last30
let
    Source = Oracle.Database("PTR", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - PTR - CRONOS - ZARA - ÚLTIMOS 30 DÍAS#(lf)SELECT#(lf)#(tab)a.cod_ped AS cod_ped,#(lf)#(tab)a.cod_ped_indom AS cod_ped_indom,#(lf)#(tab)plat.descripcion AS pais,#(lf)#(tab)plat.id_pais AS id_pais,#(lf)#(tab)MAX(a.provincia) AS provincia,#(lf)#(tab)MAX(a.cod_postal) AS codigo_postal,#(lf)#(tab)MAX(a.ciudad) AS ciudad,#(lf)#(tab)MAX(a.distrito) AS distrito,#(lf)#(tab)MAX(a.cod_tienda_destino) AS cod_tienda_destino,#(lf)#(tab)COALESCE(alm.nombre_almacen, TO_CHAR(a.id_loc_alm)) AS almacen,#(lf)#(tab)te.descripcion AS tipo_envio,#(lf)#(tab)es.descripcion AS estado,#(lf)#(tab)tr.descripcion AS transportista,#(lf)#(tab)--a.cod_t_operativa_alm AS cod_t_operativa_alm,#(lf)#(tab)--a.es_stk_integrado AS es_stk_integrado,#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN MIN(cod_t_operativa_alm) > 0 #(lf)#(tab)#(tab)#(tab)AND MAX(es_consolidado) = 0 #(lf)#(tab)#(tab)#(tab)#(tab)AND COUNT(DISTINCT cod_ped_indom) > 1 THEN 1 #(lf)#(tab)#(tab)ELSE 0 #(lf)#(tab)END AS es_roto,#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN MIN(cod_t_operativa_alm) = 0 THEN 1 #(lf)#(tab)#(tab)ELSE 0 #(lf)#(tab)END AS es_picking_transfer,#(lf)#(tab)MAX(es_stk_integrado) AS es_stock_integrado,#(lf)#(tab)MAX(es_instant_delivery) AS es_instant_delivery,#(lf)#(tab)0 AS es_preventa,#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN MAX(es_cruzado) > 0 #(lf)#(tab)#(tab)#(tab)AND COUNT(DISTINCT cod_ped_indom) = 1 THEN 1 #(lf)#(tab)#(tab)ELSE 0 #(lf)#(tab)END AS es_cruzado,#(lf)#(tab)MAX(es_consolidado) AS es_consolidado,#(lf)#(tab)a.feho_local AS feho_pedido,#(lf)#(tab)a.feho_limite_entrg AS feho_limite_entrg,#(lf)#(tab)a.feho_limite_transpt AS feho_limite_transpt,#(lf)#(tab)a.feho_limite_expe AS feho_limite_expedicion,#(lf)#(tab)MAX(eped_aux.ori_fec_entrg_seleccionada) AS origen_cronos,#(lf)#(tab)MAX(        #(lf)#(tab)#(tab)COALESCE(#(lf)#(tab)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 23 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)#(tab)END,#(lf)#(tab)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 1 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)#(tab)END)#(lf)#(tab)#(tab)) AS max_delivery_date_by_cronos,#(lf)#(tab)MAX(        #(lf)#(tab)#(tab)COALESCE(#(lf)#(tab)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 22 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)#(tab)END,#(lf)#(tab)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 2 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)#(tab)END)#(lf)#(tab)#(tab)) AS min_delivery_date_by_cronos,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 3 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS opt_delivery_date_by_cronos,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 4 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS max_delivery_date_backup,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 5 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS min_delivery_date_backup,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 7 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS max_warehouse_date_by_cronos,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 8 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS est_delivery_date_by_cronos,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 14 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS recalc_delivery_date_by_cronos,#(lf)#(tab)a.feho_alm AS feho_alm,#(lf)#(tab)a.feho_empaquetado AS feho_empaquetado,#(lf)#(tab)a.feho_expe AS feho_expedicion,#(lf)#(tab)a.feho_intento_entrg AS feho_intento_entrg,#(lf)#(tab)a.feho_entrg_tnd AS feho_entrg_tnd,#(lf)#(tab)a.feho_entrg_punto_entrg AS feho_entrg_punto_entrg,#(lf)#(tab)a.feho_entrg AS feho_entrg,#(lf)#(tab)a.feho_entrg_transp AS feho_entrg_transp,#(lf)#(tab)a.feho_entrg_cliente AS feho_entrg_cliente,#(lf)#(tab)TRUNC(feho_expe) - TRUNC(feho_local) AS dias_exp,#(lf)#(tab)TRUNC(feho_expe) - TRUNC(feho_alm) AS dias_exp_alm,#(lf)#(tab)TRUNC(feho_entrg_transp) - TRUNC(feho_expe) AS dias_transp,#(lf)#(tab)a.intervalo_rev_ok AS intervalo_rev_ok,#(lf)#(tab)--a.intervalo_preparacion_ok AS intervalo_preparacion_ok,#(lf)#(tab)--a.intervalo_pend_recogida_ok AS intervalo_pend_recogida_ok,#(lf)#(tab)--a.intervalo_trans_ok AS intervalo_trans_ok,#(lf)#(tab)--a.intervalo_entrg_ok AS intervalo_entrg_ok,#(lf)/* #(tab)CASE #(lf)#(tab)#(tab)WHEN a.feho_entrg IS NULL THEN 0 #(lf)#(tab)#(tab)ELSE 1 #(lf)#(tab)END AS completado_ok, */#(lf)#(tab)/* CASE #(lf)#(tab)#(tab)WHEN SUM(intervalo_rev_ok) >=1 THEN ROUND(( CAST( MAX(feho_alm) AS DATE ) - CAST( MIN(feho_local) AS DATE ) ) * 24*60*60,4) #(lf)#(tab)#(tab)ELSE NULL #(lf)#(tab)END AS tiempo_retenido_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.intervalo_preparacion_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_empaquetado AS DATE) - CAST(feho_alm AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_empaquetado_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.intervalo_pend_recogida_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_expe AS DATE) - CAST(feho_empaquetado AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_muelle_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.interv_transpt_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg_transp AS DATE) - CAST(feho_expe AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_intento_entrg_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.interv_recogida_cliente_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg_cliente AS DATE) - CAST(coalesce(feho_entrg_punto_entrg, feho_entrg_tnd) AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_recogida_cliente_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.interv_intento_entrg_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg AS DATE) - CAST(feho_entrg_transp AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_entre_intento_entrg_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.intervalo_entrg_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg_cliente AS DATE) - CAST(feho_local AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_entrg_cliente_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.intervalo_entrg_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg AS DATE) - CAST(feho_local AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_entrg_seg, */#(lf)#(tab)CAST( TRUNC(MAX(feho_entrg)) AS DATE ) - CAST( TRUNC(MIN(feho_local)) AS DATE ) AS dias_entrega,#(lf)#(tab)CAST( TRUNC(MAX(feho_entrg_transp)) AS DATE ) - CAST( TRUNC(MIN(feho_limite_entrg)) AS DATE ) AS dias_vs_compromiso,#(lf)#(tab)(CASE#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(feho_entrg_transp) <= TRUNC(feho_limite_entrg) THEN 'OK'#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(feho_entrg_transp) > TRUNC(feho_limite_entrg) THEN 'KO'#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(sysdate) > TRUNC(feho_limite_entrg) THEN 'Riesgo'#(lf)#(tab)#(tab)ELSE 'Dato no informado'#(lf)#(tab)END) AS exito_entrega,#(lf)#(tab)(CASE#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(feho_entrg_transp) <= TRUNC(feho_limite_transpt) THEN 'OK'#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(feho_entrg_transp) > TRUNC(feho_limite_transpt) THEN 'KO'#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(sysdate) > TRUNC(feho_limite_transpt) THEN 'Riesgo'#(lf)#(tab)#(tab)ELSE 'Dato no informado'#(lf)#(tab)END) AS exito_transporte,#(lf)#(tab)(CASE#(lf)#(tab)#(tab)WHEN feho_expe IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND feho_expe <= feho_limite_expe THEN 'OK'#(lf)#(tab)#(tab)WHEN feho_expe IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND feho_expe > feho_limite_expe THEN 'KO'#(lf)#(tab)#(tab)WHEN feho_expe IS NULL #(lf)#(tab)#(tab)#(tab)AND sysdate > feho_limite_expe THEN 'Riesgo'#(lf)#(tab)#(tab)ELSE 'Dato no informado'#(lf)#(tab)END) AS exito_expedicion#(lf)#(tab)--MAX (ent.totaltax) AS totaltax#(lf)FROM aap_drive.fact_prev_entrg a#(lf)LEFT JOIN aap_drive.drive_plat plat#(lf)#(tab)ON a.id_plat = plat.id_plat#(lf)        AND a.id_plat > 0 -- EXCLUIR MARKETPLACES#(lf)LEFT JOIN aap_drive.drive_almacen alm#(lf)#(tab)ON a.id_loc_alm = alm.id_almacen#(lf)LEFT JOIN aap_drive.drive_entrg_t_env_cis te#(lf)#(tab)ON a.cod_t_env = te.cod_t_env#(lf)#(tab)#(tab)AND te.id_cadena = (CASE WHEN a.id_cadena = 16 THEN 1 ELSE a.id_cadena END)#(lf)LEFT JOIN aap_drive.drive_entrg_est_ped_cis es#(lf)#(tab)ON a.cod_est_ped = es.cod_est_ped#(lf)#(tab)#(tab)AND es.id_cadena = (CASE WHEN a.id_cadena = 16 THEN 1 ELSE a.id_cadena END)#(lf)LEFT JOIN aap_drive.drive_entrg_transptta tr#(lf)#(tab)ON a.cod_transptta = tr.cod_transptta#(lf)#(tab)#(tab)AND tr.id_cadena = (CASE WHEN a.id_cadena = 16 THEN 1 ELSE a.id_cadena END)#(lf)LEFT JOIN fnd_etiquetado.pedido eped#(lf)#(tab)ON eped.cod_ped_ori_wcs = a.cod_ped#(lf)LEFT JOIN fnd_etiquetado.pedido_auxiliar eped_aux#(lf)#(tab)ON eped.id_ped = eped_aux.id_ped#(lf)LEFT JOIN fnd_etiquetado.pedido_tipo_fecha eped_tfec#(lf)#(tab)ON eped.id_ped = eped_tfec.id_ped#(lf)WHERE #(lf)#(tab)a.feho_local BETWEEN (CURRENT_DATE - 30)#(lf)#(tab)#(tab)AND (CURRENT_TIMESTAMP)#(lf)#(tab)#(tab)AND a.cod_est_ped NOT IN (10, 11, 31) #(lf)#(tab)#(tab)AND a.id_cadena IN (1, 16) -- ZARA#(lf)#(tab)#(tab)AND a.es_stk_integrado = 1#(lf)    AND es.descripcion IN ('En oleada', 'Enviado al almacen', 'Recibido almacen', 'En picking', 'Empaquetado')#(lf)GROUP BY #(lf)#(tab)a.cod_ped,#(lf)#(tab)a.cod_ped_indom,#(lf)#(tab)plat.descripcion,#(lf)    plat.id_pais,#(lf)#(tab)COALESCE(alm.nombre_almacen, TO_CHAR(a.id_loc_alm)),#(lf)#(tab)te.descripcion,#(lf)#(tab)a.cod_est_ped,#(lf)#(tab)es.descripcion,#(lf)#(tab)a.cod_transptta,#(lf)#(tab)tr.descripcion,#(lf)#(tab)--a.cod_t_operativa_alm,#(lf)#(tab)--a.es_stk_integrado,#(lf)#(tab)a.es_instant_delivery,#(lf)#(tab)a.es_roto,#(lf)#(tab)a.es_cruzado,#(lf)#(tab)a.es_consolidado,#(lf)#(tab)a.feho_ped,#(lf)#(tab)a.fec_ped,#(lf)#(tab)a.feho_local,#(lf)#(tab)a.feho_limite_expe,#(lf)#(tab)a.feho_limite_entrg,#(lf)#(tab)a.feho_expe,#(lf)#(tab)a.feho_empaquetado,#(lf)#(tab)a.feho_alm,#(lf)#(tab)a.feho_entrg,#(lf)#(tab)a.feho_entrg_cliente,#(lf)#(tab)a.feho_entrg_transp,#(lf)#(tab)a.feho_intento_entrg,#(lf)#(tab)a.feho_entrg_tnd,#(lf)#(tab)a.feho_entrg_punto_entrg,#(lf)#(tab)a.feho_limite_transpt,#(lf)#(tab)a.intervalo_rev_ok#(lf)#(tab)--a.intervalo_preparacion_ok,#(lf)#(tab)--a.intervalo_pend_recogida_ok,#(lf)#(tab)--a.intervalo_trans_ok,#(lf)#(tab)--a.intervalo_entrg_ok#(lf)ORDER BY#(lf)#(tab)a.feho_local ASC", CommandTimeout=#duration(0, 4, 0, 0)]),
    #"Added Conditional Column" = Table.AddColumn(Source, "Operation Type", each if [ES_PICKING_TRANSFER] = 1 then "PAT" else if [ES_PICKING_TRANSFER] = 0 then "SINT" else "DESCONOCIDO"),
    #"Added Custom Fecha Limite Entrega" = Table.AddColumn(#"Added Conditional Column", "Fecha Límite Entrega", each if [MAX_DELIVERY_DATE_BY_CRONOS] <> null then [MAX_DELIVERY_DATE_BY_CRONOS] else if [MAX_DELIVERY_DATE_BACKUP] <> null then [MAX_DELIVERY_DATE_BACKUP] else [FEHO_LIMITE_ENTRG], type datetime),
    #"Added Custom Fecha Limite Expedicion" = Table.AddColumn(#"Added Custom Fecha Limite Entrega", "Fecha Límite Expedición", each if [MAX_WAREHOUSE_DATE_BY_CRONOS] <> null then [MAX_WAREHOUSE_DATE_BY_CRONOS] else [FEHO_LIMITE_EXPEDICION], type datetime),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom Fecha Limite Expedicion",{"PROVINCIA", "CODIGO_POSTAL", "CIUDAD", "DISTRITO", "FEHO_LIMITE_TRANSPT", "ORIGEN_CRONOS", "MAX_DELIVERY_DATE_BY_CRONOS", "MIN_DELIVERY_DATE_BY_CRONOS", "OPT_DELIVERY_DATE_BY_CRONOS", "MAX_DELIVERY_DATE_BACKUP", "MIN_DELIVERY_DATE_BACKUP", "MAX_WAREHOUSE_DATE_BY_CRONOS", "EST_DELIVERY_DATE_BY_CRONOS", "RECALC_DELIVERY_DATE_BY_CRONOS", "FEHO_ALM", "FEHO_EMPAQUETADO", "FEHO_INTENTO_ENTRG", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION", "ES_STOCK_INTEGRADO", "ES_PICKING_TRANSFER", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG_CLIENTE", "TIPO_ENVIO", "TRANSPORTISTA", "ES_ROTO", "ES_INSTANT_DELIVERY", "ES_PREVENTA", "ES_CRUZADO", "ES_CONSOLIDADO", "FEHO_EXPEDICION", "FEHO_ENTRG", "FEHO_LIMITE_ENTRG", "FEHO_LIMITE_EXPEDICION"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Columns",{{"COD_PED", type text}, {"COD_PED_INDOM", type text}, {"COD_TIENDA_DESTINO", type text}, {"Operation Type", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"COD_PED", "Código Pedido"}, {"COD_PED_INDOM", "Código Subpedido"}, {"PAIS", "Mercado"}, {"COD_TIENDA_DESTINO", "Código Tienda Destino"}, {"ALMACEN", "Almacén"}, {"FEHO_PEDIDO", "Fecha Pedido"}, {"ESTADO", "Estado"}, {"ID_PAIS", "Country"}}),
    #"Added Conditional Column3" = Table.AddColumn(#"Renamed Columns", "Estado Equivalente", each if [Estado] = "En oleada" then "PENDING TO PACK" else if [Estado] = "Recibido almacen" then "PENDING TO PACK" else if [Estado] = "En picking" then "PENDING TO PACK" else if [Estado] = "Enviado al almacen" then "PENDING TO PACK" else if [Estado] = "Empaquetado" then "PACKED" else "DESC", type text),
    #"Merged Queries" = Table.NestedJoin(#"Added Conditional Column3", {"Código Tienda Destino"}, #"Localizacion Cronos", {"Localización"}, "Localizacion", JoinKind.LeftOuter),
    #"Expanded Localizacion" = Table.ExpandTableColumn(#"Merged Queries", "Localizacion", {"Descripción"}, {"Descripción Tienda Destino"}),
    #"Merged Queries1" = Table.NestedJoin(#"Expanded Localizacion", {"Almacén"}, #"Localizacion Cronos", {"Localización"}, "Localizacion", JoinKind.LeftOuter),
    #"Expanded Localizacion1" = Table.ExpandTableColumn(#"Merged Queries1", "Localizacion", {"Descripción"}, {"Descripción.1"}),
    #"Added Conditional Column2" = Table.AddColumn(#"Expanded Localizacion1", "Almacén/Tienda", each if [Descripción.1] = null then [Almacén] else if [Descripción.1] <> null then [Descripción.1] else "Desconocido", type text),
    #"Inserted First Characters" = Table.AddColumn(#"Added Conditional Column2", "Store Location", each Text.Start([#"Almacén/Tienda"], 5), type text),
    #"Inserted Merged Column" = Table.AddColumn(#"Inserted First Characters", "ID Country-Store", each Text.Combine({Text.From([Country], "es-ES"), [Store Location]}, "-"), type text),
    #"Removed Columns2" = Table.RemoveColumns(#"Inserted Merged Column",{"Código Tienda Destino", "Almacén", "Descripción.1"}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns2",{{"Fecha Pedido", type date}, {"Fecha Límite Expedición", type date}, {"Fecha Límite Entrega", type date}}),
    #"Added Custom Fecha Exp Table" = Table.AddColumn(#"Changed Type1", "Fecha Límite Expedición Table", each if [Fecha Límite Expedición] = null then "Not Informed" else if (Date.IsInCurrentDay([Fecha Límite Expedición]) or Date.IsInNextNDays([Fecha Límite Expedición], 5) or Date.IsInPreviousNDays([Fecha Límite Expedición], 3)) then Date.ToText([Fecha Límite Expedición]) else if [Fecha Límite Expedición] > Date.From(DateTime.FixedLocalNow()) then Text.Combine({"> ", Date.ToText(Date.AddDays(Date.From(DateTime.FixedLocalNow()), 6))}) else if [Fecha Límite Expedición] < Date.From(DateTime.FixedLocalNow()) then Text.Combine({"< ", Date.ToText(Date.AddDays(Date.From(DateTime.FixedLocalNow()), -3))}) else "0", type text),
    #"Added Custom Fecha Ent Table" = Table.AddColumn(#"Added Custom Fecha Exp Table", "Fecha Límite Entrega Table", each if [Fecha Límite Entrega] = null then "Not Informed" else if (Date.IsInCurrentDay([Fecha Límite Entrega]) or Date.IsInNextNDays([Fecha Límite Entrega], 5) or Date.IsInPreviousNDays([Fecha Límite Entrega], 3)) then Date.ToText([Fecha Límite Entrega]) else if [Fecha Límite Entrega] > Date.From(DateTime.FixedLocalNow()) then Text.Combine({"> ", Date.ToText(Date.AddDays(Date.From(DateTime.FixedLocalNow()), 6))}) else if [Fecha Límite Entrega] < Date.From(DateTime.FixedLocalNow()) then Text.Combine({"< ", Date.ToText(Date.AddDays(Date.From(DateTime.FixedLocalNow()), -3))}) else "0", type text),
    #"Added Orden Fecha Exp" = Table.AddColumn(#"Added Custom Fecha Ent Table", "Ordenar Fecha Límite Expedición Table", each if [Fecha Límite Expedición Table] = "Not Informed" then 1 else if Text.Contains([Fecha Límite Expedición Table], "<") then 2 else if Text.Contains([Fecha Límite Expedición Table], ">") then 21000000 else if Text.Contains([Fecha Límite Expedición Table], "/") then Text.Combine({Text.End([Fecha Límite Expedición Table], 4), Text.Middle([Fecha Límite Expedición Table], 3, 2), Text.Start([Fecha Límite Expedición Table], 2)}) else 0),
    #"Added Orden Fecha Ent" = Table.AddColumn(#"Added Orden Fecha Exp", "Ordenar Fecha Límite Entrega Table", each if [Fecha Límite Entrega Table] = "Not Informed" then 1 else if Text.Contains([Fecha Límite Entrega Table], "<") then 2 else if Text.Contains([Fecha Límite Entrega Table], ">") then 21000000 else if Text.Contains([Fecha Límite Entrega Table], "/") then Text.Combine({Text.End([Fecha Límite Entrega Table], 4), Text.Middle([Fecha Límite Entrega Table], 3, 2), Text.Start([Fecha Límite Entrega Table], 2)}) else 0),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Orden Fecha Ent",{{"Ordenar Fecha Límite Expedición Table", Int64.Type}, {"Ordenar Fecha Límite Entrega Table", Int64.Type}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type3",{"Código Pedido", "Código Subpedido", "Mercado", "Descripción Tienda Destino", "Almacén/Tienda", "Store Location", "Operation Type", "Estado", "Estado Equivalente", "Fecha Pedido", "Fecha Límite Expedición", "Fecha Límite Expedición Table", "Fecha Límite Entrega", "Fecha Límite Entrega Table", "Ordenar Fecha Límite Expedición Table", "Ordenar Fecha Límite Entrega Table"})
in
    #"Reordered Columns"