// Usuarios_Compra_Despues_1_Setp_2019
let
    Source = Oracle.Database("axine1-scansrv.central.inditex.grp:11521/s_itxpro_mstrcorp", [HierarchicalNavigation=true, Query="-- PULL#(lf)-- COMPRAS CLIENTES POSTERIORES AL 1 DE SEPTIEMBRE#(lf)SELECT#(lf)  DISTINCT#(lf)    u.EMAIL,#(lf)    COUNT (DISTINCT f.ID_PEDIDO_ECOMMERCE) num_pedidos,#(lf)    f.ID_FECHA,#(lf)    p.DESCRIPCION,#(lf)    td.DESCRIPCION,#(lf)    c.CADENA#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM f#(lf)INNER JOIN DMECOMMERCE.DIM_USUARIO_ECOMM u  #(lf)  ON u.ID_USUARIO_ECOMM = f.ID_USUARIO_ECOMM #(lf)    AND u.ID_PAIS = f.ID_PAIS#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION l#(lf)  ON l.ID_LOCALIZACION = f.ID_LOCALIZACION#(lf)INNER JOIN DMCOMERCIAL.DIM_CADENA c#(lf)  ON c.ID_CADENA = f.ID_CADENA#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS p#(lf)  ON p.ID_PAIS = f.ID_PAIS#(lf)INNER JOIN DMECOMMERCE.DIM_TIPO_DISPOSITIVO td#(lf)  ON td.ID_TIPO_DISPOSITIVO = f.ID_TIPO_DISPOSITIVO#(lf)WHERE #(lf)  f.ID_FECHA_PLATAFORMA > TO_DATE('01-08-2019', 'DD-MM-YYYY')#(lf)      AND f.ID_FECHA > TO_DATE('01-09-2019', 'DD-MM-YYYY')#(lf)  AND f.ID_CADENA = 3 -- PULL#(lf)  AND f.ID_TIPO_MOVIMIENTO IN (72,772) #(lf)  AND f.ESTADO <> 'X'#(lf)  AND f.ID_TIPO_DISPOSITIVO <> 23 -- EXCLUIMOS IPOD#(lf)  AND l.ID_TIPO_TIENDA <> 6 -- EXCLUIMOS MARKETPLACES#(lf)GROUP BY#(lf)  u.EMAIL,#(lf)  f.ID_FECHA,#(lf)  p.DESCRIPCION,#(lf)  td.DESCRIPCION,#(lf)  c.CADENA"]),
    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"ID_FECHA", type date}, {"NUM_PEDIDOS", Int64.Type}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"EMAIL", "Email"}, {"NUM_PEDIDOS", "Número Pedidos"}, {"ID_FECHA", "Fecha"}, {"DESCRIPCION", "Mercado"}, {"DESCRIPCION2", "Tipo Dispositivo"}, {"CADENA", "Cadena"}})
in
    #"Columnas con nombre cambiado"