// Market_Store
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - OMNICHANNEL - CADENAS - SINT VERSION DRIVE - MARKET, STORE AND BRAND#(lf)SELECT #(lf)  DISTINCT #(lf)    dp.PAIS country,#(lf)    dp.PAIS_ISO ISO,#(lf)    dp.DESCRIPCION market,#(lf)    dp.DESCRIPCION_INGLES market_english,#(lf)    dl1.DESCRIPCION physical_store,#(lf)    dl1.LOCALIZACION location,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN mf.ID_CADENA = 3 THEN 'PULL AND BEAR'#(lf)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 5 THEN 'BERSHKA'#(lf)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 6 THEN 'STRADIVARIUS'#(lf)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 7 THEN 'OYSHO'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 8 THEN 'LEFTIES'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 11 THEN 'MASSIMO DUTTI'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 14 THEN 'ZARA HOME'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 16 THEN 'UTERQÜE'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)END#(tab)#(lf)#(tab)END AS brand#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)  ON dp.ID_PAIS = mf.ID_PAIS#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)  ON dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING#(lf)    AND dl1.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- PICKING EN TIENDA#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)  ON dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALMACEN#(lf)    AND dl2.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- EXPEDICIÓN DESDE TIENDA#(lf)WHERE#(lf)#(tab)mf.ID_FECHA_PLATAFORMA BETWEEN (CURRENT_DATE - 90)#(lf)#(tab)#(tab)AND (CURRENT_DATE + 30)#(lf)#(tab)AND mf.ID_FECHA BETWEEN (CURRENT_DATE - 61)#(lf)#(tab)#(tab)AND (CURRENT_DATE + 1)#(lf)  AND ((mf.ID_TIPO_MOVIMIENTO IN (72, 772) AND mf.ESTADO NOT IN ('X', 'N', 'PQ')) -- ORDER TRANSACTION#(lf)    OR mf.ID_TIPO_MOVIMIENTO IN (73, 808)) -- RETURN TRANSACTION#(lf)  AND mf.REPOSICION = 0 -- DRIVE#(lf)  AND mf.ES_CAMBIO = 0 -- DRIVE#(lf)  AND mf.ID_CADENA IN (3, 5, 6, 7, 8, 11, 14, 16)#(lf)  AND mf.ID_SECCION > 0 -- DRIVE#(lf)  AND mf.ID_PAIS > 0 -- DRIVE#(lf)  AND dl1.LOCALIZACION > 0 -- QUITAMOS LOS ""NO TIENE""#(lf)ORDER BY #(lf)  dl1.LOCALIZACION ASC", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MARKET", type text}, {"COUNTRY", Int64.Type}, {"LOCATION", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",",","",Replacer.ReplaceText,{"MARKET", "MARKET_ENGLISH"}),
    #"Added Custom" = Table.AddColumn(#"Replaced Value", "Store Description", each if [PHYSICAL_STORE] = "NO TIENE" then "NO TIENE" else  Text.PadStart(Text.BeforeDelimiter([PHYSICAL_STORE], " -"), 5, "0") & " - " & Text.AfterDelimiter([PHYSICAL_STORE], "- "), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"PHYSICAL_STORE"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"MARKET", "Market"}, {"COUNTRY", "Country"}, {"MARKET_ENGLISH", "Market English"}, {"LOCATION", "Location"}, {"BRAND", "Brand"}}),
    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "Market - Store", each [Market English] & " - " & [Store Description], type text),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Store Location", each if [Location] = "0" then "DOES NOT HAVE" else Text.PadStart([Location],5,"0"), type text),
    #"Inserted Merged Column" = Table.AddColumn(#"Added Custom2", "ID Country-Store", each Text.Combine({ Text.From([Country], "es-ES"),[Store Location]}, "-"), type text),
    #"Removed Columns1" = Table.RemoveColumns(#"Inserted Merged Column",{"Location"}),
    #"Merged Queries" = Table.NestedJoin(#"Removed Columns1", {"Store Location"}, AMT, {"STORE"}, "AMT", JoinKind.LeftOuter),
    #"Expanded AMT" = Table.ExpandTableColumn(#"Merged Queries", "AMT", {"AMT"}, {"AMT"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Expanded AMT",{"ID Country-Store", "Country", "Market", "Market English", "Store Location", "Store Description", "Market - Store"})
in
    #"Reordered Columns"