// Returns_Store_MICRO
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - DEVOLUCIONES SINT - CADENA - TIENDA - LAST 30#(lf)SELECT#(lf)  mf.ID_FECHA,#(lf)  COUNT(DISTINCT mf.ID_PEDIDO_ECOMMERCE) devoluciones,#(lf)  SUM(mf.UNIDADES) unidades,#(lf)  SUM(mf.IMPORTE) local_amount,#(lf)  SUM(ROUND (mf.IMPORTE * mf.CAMBIO_REFERENCIA, 2)) amount_euros,#(lf)  CASE#(lf)#(tab)#(tab)WHEN mf.ID_CADENA = 3 THEN 'PULL AND BEAR'#(lf)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 5 THEN 'BERSHKA'#(lf)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 6 THEN 'STRADIVARIUS'#(lf)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 7 THEN 'OYSHO'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 8 THEN 'LEFTIES'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 11 THEN 'MASSIMO DUTTI'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 14 THEN 'ZARA HOME'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN mf.ID_CADENA = 16 THEN 'UTERQÜE'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)END#(tab)#(lf)#(tab)END AS BRAND,#(lf)  dp.DESCRIPCION_INGLES market_english,#(lf)  dp.PAIS,#(lf)  dl1.LOCALIZACION location,#(lf)  dl1.DESCRIPCION physical_store#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMECOMMERCE.DIM_ESTADO_PEDIDO_ECOMMERCE depe#(lf)  ON depe.ID_ESTADO_PEDIDO_ECOMMERCE = mf.ID_ESTADO_PEDIDO_ECOMMERCE#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)  ON dp.ID_PAIS = mf.ID_PAIS#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)  ON dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING#(lf)  AND dl1.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- PICKING EN TIENDA#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)  ON dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALMACEN#(lf)  AND dl2.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- EXPEDICIÓN DESDE TIENDA#(lf)WHERE#(lf)#(tab)mf.ID_FECHA_PLATAFORMA BETWEEN (CURRENT_DATE - 70)#(lf)#(tab)#(tab)AND (CURRENT_DATE + 30)#(lf)#(tab)AND mf.ID_FECHA BETWEEN (CURRENT_DATE - 31)#(lf)#(tab)#(tab)AND (CURRENT_DATE + 1)#(lf)  AND mf.ID_TIPO_MOVIMIENTO IN (73, 808) -- RETURN TRANSACTION#(lf)  AND mf.ID_CADENA IN (3, 5, 6, 7, 8, 11, 14, 16)#(lf)  AND mf.REPOSICION = 0 -- DRIVE#(lf)  AND mf.ES_CAMBIO = 0 -- DRIVE#(lf)  AND mf.ID_SECCION > 0 -- DRIVE#(lf)  AND mf.ID_PAIS > 0 -- DRIVE#(lf)  AND dl1.LOCALIZACION > 0 -- QUITAMOS LOS ""NO TIENE""#(lf)GROUP BY#(lf)  mf.ID_FECHA,#(lf)  dp.DESCRIPCION_INGLES,#(lf)  dp.PAIS,#(lf)  dl1.LOCALIZACION,#(lf)  dl1.DESCRIPCION,#(lf)  mf.ID_CADENA", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_FECHA", type date}, {"DEVOLUCIONES", Int64.Type}, {"UNIDADES", Int64.Type}, {"LOCATION", type text}, {"PAIS", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ID_FECHA", "Date"}, {"DEVOLUCIONES", "Returns"}, {"UNIDADES", "Units"}, {"AMOUNT_EUROS", "Amount (€)"}, {"MARKET_ENGLISH", "Market English"},  {"LOCAL_AMOUNT", "Local Amount"}, {"LOCATION", "Location"}, {"PHYSICAL_STORE", "Physical Store"}, {"PAIS", "Country"}, {"BRAND", "Brand"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns",",","",Replacer.ReplaceText,{"Market English"}),
    #"Added Custom" = Table.AddColumn(#"Replaced Value", "Store Location", each Text.PadStart([Location], 5, "0"), type text),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Store Description", each [Store Location] & " - " & Text.AfterDelimiter([Physical Store], "- "), type text),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Market - Store", each [Market English] & " - " & [Store Description], type text),
    #"Inserted Merged Column" = Table.AddColumn(#"Added Custom2", "ID Country-Store", each Text.Combine({Text.From([Country], "es-ES"), [Store Location]}, "-"), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Inserted Merged Column",{"Physical Store", "Location"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"Date", "ID Country-Store", "Market English", "Market - Store", "Store Location", "Store Description", "Returns", "Units", "Amount (€)", "Local Amount"})
in
    #"Reordered Columns"