// Store_Status
let
    Source = DB2.Database("ieecdb2v1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="-- IBM DB2 - SEGUNDO TRAMO DE RÉPLICA - ENTORNO PRO - OMNICHANNEL - SINT - FY2019#(lf)SELECT#(lf)#(tab)CASE#(lf)#(tab)#(tab)#(tab)WHEN os.ID_CADENA = 2 THEN 'PULL AND BEAR'#(lf)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)WHEN os.ID_CADENA = 4 THEN 'BERSHKA'#(lf)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN os.ID_CADENA = 6 THEN 'STRADIVARIUS'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN os.ID_CADENA = 7 THEN 'OYSHO'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN os.ID_CADENA = 8 THEN 'LEFTIES'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN os.ID_CADENA = 11 THEN 'MASSIMO DUTTI'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN os.ID_CADENA = 14 THEN 'ZARA HOME'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)ELSE CASE#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)WHEN os.ID_CADENA = 18 THEN 'UTERQÜE'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)#(tab)END#(tab)#(lf)#(tab)#(tab)END AS Brand,#(lf)#(tab)pa.ID_PAIS AS COUNTRY,#(lf)#(tab)pa.DESCRIPCION AS COUNTRY_DESCRIPTION,#(lf)#(tab)os.NOMBRE AS STORE_DESCRIPTION,#(lf)#(tab)os.ID_LOCALIZACION AS PHYSICAL_STORE_ID,#(lf)#(tab)tgdos.DESCRIPCION AS RELATIONSHIP_TYPE,#(lf)#(tab)CASE os.ID_ESTADO_ORIGEN_STOCK #(lf)#(tab)#(tab)WHEN 1 THEN CASE #(lf)#(tab)#(tab)#(tab)WHEN NOT gdosc.ID_GRUPO_DISTRIBUCION_ORIGEN_STOCK IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)AND gdosc.PEDIDOS_REASIGNADOS >= MAXIMO_PEDIDOS_REASIGNADOS THEN 'Capacidad Topeada' #(lf)#(tab)#(tab)#(tab)ELSE CASE gdos.HABILITADO #(lf)#(tab)#(tab)#(tab)#(tab)WHEN 1 THEN 'Relación Activa'#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 2 THEN 'Relación Pausada'#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 3 THEN 'Relación Contingencia'#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 4 THEN 'Relación Pausada Parcial'#(lf)#(tab)#(tab)#(tab)ELSE#(tab)'Relación Inactiva'#(lf)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)END#(lf)#(tab)ELSE 'Origen Inactivo'#(lf)#(tab)END AS STATUS,#(lf)#(tab)COALESCE(d.POBLACION, 'Nulo') AS CITY,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(tab) = 3 THEN gdosc.PEDIDOS_REASIGNADOS#(lf)#(tab)#(tab)ELSE#(tab)osc.UMBRAL_MINIMO #(lf)#(tab)END AS MIN_THRESHOLD,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(tab) = 3 THEN gdosc.PEDIDOS_REASIGNADOS#(lf)#(tab)#(tab)ELSE#(tab)osc.TOTAL_PEDIDOS_VIVOS#(lf)#(tab)END AS CURRENT_LIVE_ORDERS,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(tab) = 3 THEN gdosc.MAXIMO_PEDIDOS_REASIGNADOS#(lf)#(tab)#(tab)ELSE#(tab)osc.UMBRAL_MAXIMO#(lf)#(tab)END AS MAX_THRESHOLD,#(lf)#(tab)CASE os.ID_ESTADO_ORIGEN_STOCK #(lf)#(tab)#(tab)WHEN 1 THEN CASE #(lf)#(tab)#(tab)#(tab)WHEN NOT gdosc.ID_GRUPO_DISTRIBUCION_ORIGEN_STOCK IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)AND gdosc.PEDIDOS_REASIGNADOS >= MAXIMO_PEDIDOS_REASIGNADOS THEN 0 #(lf)#(tab)#(tab)#(tab)ELSE CASE gdos.HABILITADO #(lf)#(tab)#(tab)#(tab)#(tab)WHEN 1 THEN 1#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 2 THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 3 THEN 0#(lf)#(tab)#(tab)#(tab)#(tab)WHEN 4 THEN 0#(lf)#(tab)#(tab)#(tab)ELSE#(tab)0#(lf)#(tab)#(tab)#(tab)END#(lf)#(tab)#(tab)END#(lf)#(tab)ELSE 0#(lf)#(tab)END AS BOOLEAN_STATUS#(lf)FROM#(tab)INDOM_ITX.GRUPO_DISTRIBUCION gd#(lf)INNER JOIN INDOM_ITX.ENTIDAD_ECOMMERCE ee#(lf)#(tab)ON ee.ID_GRUPO_DISTRIBUCION = gd.ID_GRUPO_DISTRIBUCION#(lf)INNER JOIN INDOM_ITX.GRUPO_DISTRIBUCION_ORIGEN_STOCK gdos#(lf)#(tab)ON gdos.ID_GRUPO_DISTRIBUCION = gd.ID_GRUPO_DISTRIBUCION#(lf)INNER JOIN INDOM_ITX.ORIGEN_STOCK os#(lf)#(tab)ON os.ID_ORIGEN_STOCK = gdos.ID_ORIGEN_STOCK#(lf)#(tab)#(tab)AND os.COD_ORIGEN_STOCK_WCS LIKE '%PST%' -- ORIGEN STOCK TIENDA FÍSICA#(lf)#(tab)#(tab)#(tab)AND os.ID_CADENA IN (2, 4, 6, 7, 8, 11, 14, 18)#(lf)INNER JOIN INDOM_ITX.TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK tgdos#(lf)#(tab)ON tgdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK = gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(lf)LEFT JOIN INDOM_ITX.GRUPO_DISTRIBUCION_ORIGEN_STOCK_CAPACIDAD gdosc#(lf)#(tab)ON gdosc.ID_GRUPO_DISTRIBUCION_ORIGEN_STOCK = gdos.ID_GRUPO_DISTRIBUCION_ORIGEN_STOCK#(lf)LEFT JOIN INDOM_ITX.ORIGEN_STOCK_CARGA osc#(lf)#(tab)ON osc.ID_ORIGEN_STOCK = os.ID_ORIGEN_STOCK#(lf)INNER JOIN MAESTROS.LOCALIZACION l#(lf)#(tab)ON l.ID_LOCALIZACION = os.ID_LOCALIZACION#(lf)INNER JOIN MAESTROS.DIRECCION d#(lf)#(tab)ON d.ID_DIRECCION = l.ID_DIRECCION#(lf)INNER JOIN MAESTROS.PAIS pa#(lf)#(tab)ON pa.ID_PAIS = os.ID_PAIS#(lf)           --AND pa.ID_PAIS = 11 SPAIN#(lf)WHERE#(lf)#(tab)ee.DESCRIPCION NOT LIKE '%TEST%'#(lf)#(tab)#(tab)AND ee.DESCRIPCION NOT LIKE '%Test%'#(lf)#(tab)#(tab)#(tab)AND gdos.ID_TIPO_GRUPO_DISTRIBUCION_ORIGEN_STOCK IN (1, 2, 3)#(lf)#(tab)#(tab)#(tab)#(tab)AND #(lf)#(tab)#(tab)#(tab)#(tab)(tgdos.DESCRIPCION = 'Capacidad' #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)OR #(lf)#(tab)#(tab)#(tab)#(tab)#(tab)(tgdos.DESCRIPCION = 'Disponible'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)#(tab)AND gdos.HABILITADO IN (1, 4)#(lf)#(tab)#(tab)#(tab)#(tab)#(tab))#(lf)#(tab)#(tab)#(tab)#(tab))#(lf)WITH UR;", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"COUNTRY", Int64.Type}, {"BOOLEAN_STATUS", type text}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"BRAND", "Brand"}, {"COUNTRY", "Country"}, {"COUNTRY_DESCRIPTION", "Country Description"}, {"STORE_DESCRIPTION", "Store"}, {"PHYSICAL_STORE_ID", "Store ID"}, {"RELATIONSHIP_TYPE", "Relationship Type"}, {"STATUS", "Status"}, {"CITY", "City"}, {"MIN_THRESHOLD", "Min Threshold"}, {"CURRENT_LIVE_ORDERS", "Current Orders"}, {"MAX_THRESHOLD", "Max Threshold"}, {"BOOLEAN_STATUS", "Boolean Status"}}),
    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "Store Description", each Text.PadStart(Text.BeforeDelimiter(Number.ToText([Store ID]), " -"), 5, "0") & " - " & [Store]),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Store Description", type text}}),
    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado1", "Market - Store", each [Country Description] & " - " & [Store Description]),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"Market - Store", type text}}),
    #"Personalizada agregada2" = Table.AddColumn(#"Tipo cambiado2", "ID Country-Store", each Number.ToText([Country]) & "-" & Text.PadStart(Text.BeforeDelimiter(Number.ToText([Store ID]), " -"), 5, "0")),
    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Personalizada agregada2",{{"ID Country-Store", type text}}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado3","1","Yes",Replacer.ReplaceText,{"Boolean Status"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","0","No",Replacer.ReplaceText,{"Boolean Status"}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Valor reemplazado1",{"ID Country-Store", "Country", "Country Description", "Store", "Store ID", "Relationship Type", "Status", "City", "Min Threshold", "Current Orders", "Max Threshold", "Boolean Status", "Store Description", "Market - Store"}),
    #"Consultas combinadas" = Table.NestedJoin(#"Columnas reordenadas", {"Country"}, Countries, {"Country"}, "Countries", JoinKind.LeftOuter),
    #"Se expandió Countries" = Table.ExpandTableColumn(#"Consultas combinadas", "Countries", {"English Description"}, {"English Description"}),
    #"Columnas reordenadas1" = Table.ReorderColumns(#"Se expandió Countries",{"ID Country-Store", "Country", "Country Description", "English Description", "Store", "Store ID", "Relationship Type", "Status", "City", "Min Threshold", "Current Orders", "Max Threshold", "Boolean Status", "Store Description", "Market - Store"}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Columnas reordenadas1",{ "Country", "Country Description", "Store", "Store ID", "City", "Market - Store"})
in
    #"Columnas quitadas"