// AMT
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZjNbhs3EMdfZeFzDjNckrs8ukZqBLCCwgEKtEEOjMU4i6520ZVUIHqbPoAPQR9BL1ZyZMlOxD9XFx32xxlyPjgz1MePV0TKuas3VzfdsOmqW9/3flqOV5/eJESWEGIDEbkWIeVqKNUyRLWGx6Ck8O16E774Yf/kq4WfNvun4Ygt3I91gyVZ1S3wCivdJPsW3eM29NX18Bh/78O3sBYN3RB2R2NZXbSOWn2ZPmcv06fpMn21u2wdXWiHvtQOLsZMEmFeDbeSZlO3jl99DNLUd5uxOlDHTY0pkeECZXIl2ojb/NSN1Yft/t8p7E5qG4JIgpfLRKsdvEqqNSVXqdoWsXjyzm8nX92Pyym5dHdKYmyFgyheC4ioeBZqC9ctBbN8j8VQcKSyJA4Jk4FI1xA1ZUNsUnrjp1UYqvf+Hz9Np4oj9y2PuEGI2mTAvf87XYf32/33lwtgFCDKtEimSSlx3a+2y5BSe//f6tWFIsysw4yfTe7HdXXb9Z/DtDki1SBENUOTVcFRBKUc9mENpdhCVBNAHLPVIilTKyClVPOscOxTXfnpII3GUB1qHYC2oFaRK+ypFYKxsaq6ICkhymaYlKz7cS2X57aLbhirX8M0hekUqHpmhXJ6bgWn/d+uVrGydTGr/PG7UtnvLLE8/06Nza+vkxW3IYHFOL3aQC5JDkjcM4DqBkhYzgNu7Zz5FumcFWWaVc6zEZQJqLiLeKO0wqgW+Gs2gVSdj4FTTRL9ff/0sBmn6k//OZbmcKqJFjKjGMsVdJJUdCBnC3LS7fKMKfnl3cZ/7dbRvLCMl+80tViElIw7WeRkvMiiWMgAsloyLCtlFD4GMdzLaiilgUJmJx7OK3Qpxa5jaYrJMfhheSxB9jC7Z0gsskAmpodGRJIjS+TxkTuBln6ekyFJi+suBf6u2/nnnI7NQee+xxLNme9xudT1RZgewjLOxr+FNKLcjKuw9vvvJxeJUe92fv3Xdoiz5W6T4OMpn6TCQ8xSnxB2Sl6AWFqhqcBqg6cCq+EscWzi50hZB6WkwOdm4NRmCEVWl14Aii3MIhR364pvCnmywf0k04ENMlcDxgWmEWN1eFnlsxefhAqnNJJpecbiGRQhg+XkWfrL5Lt1cthD91ILAeAWAXkO5lRJMf4wDl0sPnHKGU+bawgsAA2QUHLDcxLyP8ofYx8jEM0Pj314NX9ZyJR0F8Bk6s4zMqbAmtdsG6vx8PD1pd7JaxLhmDaMMcfOQCVpppJ0nKo1fpClhy4cvzRowtG5MuWdJUTSZrOZEj2gYE07NIOz0q5kAjov7STOzKwnoMfaS1pBPb+IDv9YzS3iCxbJw2920QXbHdrMnCbzw1tlEfrwQ+0F15sdFcTIqBIF5SdOTtncSZ3cFPU1Baps6Sysn/+x+VbdjfF+hDQpPfj+y6nEmCKPOVfgaQrjsrxtS9xaUz4fSTMqcPEcHjVM2Txl67L6eobr4vZK3sJ4ypKnarbrNACQRg0MSFADJEjl61UaDoouLZvM8l9LDn/6Hw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [STORE = _t, AMT = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"STORE", type text}, {"AMT", type text}})
in
    #"Changed Type"