// Zara_SINT
let
    Source = Zara_SINT_LASTMONTH,
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"COD_PAIS", Int64.Type}, {"UNITS", Int64.Type}, {"ID_TIPO_OPERATIVA_PEDIDO", Int64.Type}, {"STORE_CODE", type text}, {"ORDER_CODE", type text}, {"BLOQUEO_PEDIDO_TRANSPORTISTA", type logical}, {"BLOQUEO_DOCUMENTACION", type logical}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type","","No informado",Replacer.ReplaceValue,{"CANCEL_REASON"}),
    #"Merged Queries" = Table.NestedJoin(#"Replaced Value",{"COD_PAIS"},Countries,{"Country"},"Countries",JoinKind.LeftOuter),
    #"Expanded Countries" = Table.ExpandTableColumn(#"Merged Queries", "Countries", {"English Description"}, {"English Description"}),
    #"Added Custom" = Table.AddColumn(#"Expanded Countries", "Store Location", each Text.PadStart([STORE_CODE], 5, "0"), type text),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Store Description", each [Store Location] & " - " & [STORE], type text),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "ID Country-Store", each Text.Combine({Text.From([COD_PAIS], "es-ES"), "-", [Store Location]}), type text),
    #"Added Custom Operation Type PAT" = Table.AddColumn(#"Added Custom2", "Operation Type", each if [ID_TIPO_OPERATIVA_PEDIDO] = 3 then "PAT" else "SINT", type text),
    #"Added Conditional Column" = Table.AddColumn(#"Added Custom Operation Type PAT", "Locked", each if ([BLOQUEO_PEDIDO_TRANSPORTISTA] = true or [BLOQUEO_DOCUMENTACION] = true) then true else false, type logical),
    #"Removed Columns" = Table.RemoveColumns(#"Added Conditional Column",{"ID_TIPO_OPERATIVA_PEDIDO", "STORE", "STORE_CODE", "STATUS_EQUIVALENTE", "BLOQUEO_PEDIDO_TRANSPORTISTA", "BLOQUEO_DOCUMENTACION", "FECHA_HORA_MAXIMA_PREPARACION"}),
    #"Added Custom Diff Total Preparation" = Table.TransformColumns(Table.AddColumn(#"Removed Columns", "Diff Date Total Preparation", each Duration.TotalDays([LOCAL_EXPEDITION_DATE] - [LOCAL_PURCHASE_DATE]), Int64.Type), {{"Diff Date Total Preparation", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Reception" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Total Preparation", "Diff Date Reception", each Duration.TotalDays([LOCAL_RECEPTION_DATE] - [LOCAL_PURCHASE_DATE]), Int64.Type), {{"Diff Date Reception", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Picking" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Reception", "Diff Date Picking", each Duration.TotalDays([LOCAL_PICKING_END_DATE] - [LOCAL_RECEPTION_DATE]), Int64.Type), {{"Diff Date Picking", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Packing" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Picking", "Diff Date Packing", each Duration.TotalDays([LOCAL_PACKING_DATE] - [LOCAL_PICKING_END_DATE]), Int64.Type), {{"Diff Date Packing", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Expedition" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Packing", "Diff Date Expedition", each Duration.TotalDays([LOCAL_EXPEDITION_DATE] - [LOCAL_PACKING_DATE]), Int64.Type), {{"Diff Date Expedition", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Total Rejection" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Expedition", "Diff Date Total Rejection", each Duration.TotalDays([LOCAL_REJECTION_DATE] - [LOCAL_RECEPTION_DATE]), Int64.Type), {{"Diff Date Total Rejection", each Number.Round(_, 2), type number}}),
    #"Added Custom Diff Date Rejection" = Table.TransformColumns(Table.AddColumn(#"Added Custom Diff Date Total Rejection", "Diff Date Rejection", each Duration.TotalDays([LOCAL_REJECTION_DATE] - [LOCAL_PICKING_END_DATE]), Int64.Type), {{"Diff Date Rejection", each Number.Round(_, 2), type number}}),
    #"Split Column by Delimiter" = Table.SplitColumn(Table.TransformColumnTypes(#"Added Custom Diff Date Rejection", {{"LOCAL_PACKING_DATE", type text}}, "es-ES"), "LOCAL_PACKING_DATE", Splitter.SplitTextByDelimiter(" ", QuoteStyle.None), {"PACKING_DATE", "PACKING_TIME"}),
    #"Added Conditional Column Packaging Date Pending" = Table.AddColumn(#"Split Column by Delimiter", "Packaging Date Pending", each if [PACKING_DATE] = null then "Pending to Pack" else [PACKING_DATE], type text),
    #"Inserted Time" = Table.AddColumn(#"Added Conditional Column Packaging Date Pending", "LOCAL_PURCHASE_TIME", each DateTime.Time([LOCAL_PURCHASE_DATE]), type time),
    #"Inserted Time1" = Table.AddColumn(#"Inserted Time", "LOCAL_RECEPTION_TIME", each DateTime.Time([LOCAL_RECEPTION_DATE]), type time),
    #"Inserted Time2" = Table.AddColumn(#"Inserted Time1", "LOCAL_EXPEDITION_TIME", each DateTime.Time([LOCAL_EXPEDITION_DATE]), type time),
    #"Inserted Time3" = Table.AddColumn(#"Inserted Time2", "LOCAL_REJECTION_TIME", each DateTime.Time([LOCAL_REJECTION_DATE]), type time),
    #"Inserted Time4" = Table.AddColumn(#"Inserted Time3", "LOCAL_CANCELLATION_TIME", each DateTime.Time([LOCAL_CANCELLATION_DATE]), type time),
    #"Inserted Time5" = Table.AddColumn(#"Inserted Time4", "LOCAL_PICKING_START_TIME", each DateTime.Time([LOCAL_PICKING_START_DATE]), type time),
    #"Inserted Time6" = Table.AddColumn(#"Inserted Time5", "LOCAL_PICKING_END_TIME", each DateTime.Time([LOCAL_PICKING_END_DATE]), type time),
    #"Inserted Time7" = Table.AddColumn(#"Inserted Time6", "LOCAL_MAX_ESTIM_ENTREGA_TIME", each DateTime.Time([LOCAL_MAX_ESTIM_ENTREGA_DATE]), type time),
    #"Changed Type5" = Table.TransformColumnTypes(#"Inserted Time7",{{"LOCAL_PURCHASE_DATE", type date}, {"LOCAL_RECEPTION_DATE", type date}, {"PACKING_DATE", type date}, {"PACKING_TIME", type time}, {"LOCAL_EXPEDITION_DATE", type date}, {"LOCAL_REJECTION_DATE", type date}, {"LOCAL_CANCELLATION_DATE", type date}, {"LOCAL_PICKING_START_DATE", type date}, {"LOCAL_PICKING_END_DATE", type date}, {"LOCAL_MAX_ESTIM_ENTREGA_DATE", type date}}),
    #"Added Conditional Column Shipping type" = Table.AddColumn(#"Changed Type5", "Shipping Type", each if [LOCALIZACION_ENTREGA] = "Domicilio" then "Home Delivery" else if [COURIER] = "MY STORE" then "My Store" else "Other Store", type text),
    #"Added Conditional Column Equivalent Status" = Table.AddColumn(#"Added Conditional Column Shipping type", "Equivalent Status", each if ([STATUS] = "EXPEDITED" or [STATUS] = "TRANSFERRED") then "Shipped" else if ([STATUS] = "PACKED" or [STATUS] = "READY_FOR_TRANSFER") then "Packed" else if ([STATUS] = "RECEIVED" or [STATUS] = "RESERVED") then "Received" else if ([STATUS] = "ANNULED" and [CANCEL_REASON] = "Anulación Cliente") then "Customer Canceled" else if [STATUS] = "ANNULED" then "Rejected" else if ([STATUS] = "INCOMPLETE" or [STATUS] = "READY_FOR_PACKING" or [STATUS] = "IN PICKING" or [STATUS] = "ITEMS_COLLECTED" or [STATUS] = "PICKING_COMPLETE" or [STATUS] = "PARTIALLY_PICKED") then "Picking Process" else "DESCONOCIDO", type text),
    #"Added Custom Max Delivery Date Table" = Table.AddColumn(#"Added Conditional Column Equivalent Status", "Max Delivery Date Table", each if [LOCAL_MAX_ESTIM_ENTREGA_DATE] = null then "Not Informed" else if (Date.IsInCurrentDay([LOCAL_MAX_ESTIM_ENTREGA_DATE]) or Date.IsInNextNDays([LOCAL_MAX_ESTIM_ENTREGA_DATE], 5) or Date.IsInPreviousNDays([LOCAL_MAX_ESTIM_ENTREGA_DATE], 3)) then Date.ToText([LOCAL_MAX_ESTIM_ENTREGA_DATE]) else if [LOCAL_MAX_ESTIM_ENTREGA_DATE] > Date.From(DateTime.FixedLocalNow()) then Text.Combine({"> ", Date.ToText(Date.AddDays(Date.From(DateTime.FixedLocalNow()), 6))}) else if [LOCAL_MAX_ESTIM_ENTREGA_DATE] < Date.From(DateTime.FixedLocalNow()) then Text.Combine({"< ", Date.ToText(Date.AddDays(Date.From(DateTime.FixedLocalNow()), -3))}) else "0", type text),
    #"Added Custom Ordenar Max Delivery Date Table" = Table.TransformColumnTypes(Table.AddColumn(#"Added Custom Max Delivery Date Table", "Ordenar Max Delivery Date Table", each if [Max Delivery Date Table] = "Not Informed" then 1 else if Text.Contains([Max Delivery Date Table], "<") then 2 else if Text.Contains([Max Delivery Date Table], ">") then 21000000 else if Text.Contains([Max Delivery Date Table], "/") then Text.Combine({Text.End([Max Delivery Date Table], 4), Text.Middle([Max Delivery Date Table], 3, 2), Text.Start([Max Delivery Date Table], 2)}) else 0), {{"Ordenar Max Delivery Date Table", Int64.Type}}),
    #"Added Conditional Column Delayed Order" = Table.AddColumn(#"Added Custom Ordenar Max Delivery Date Table", "Delayed Order", each if ([STATUS] = "ANNULED" or [LOCAL_MAX_ESTIM_ENTREGA_DATE] = null) then false else if [LOCAL_EXPEDITION_DATE] = null then DateTime.Date(DateTime.LocalNow()) >= [LOCAL_MAX_ESTIM_ENTREGA_DATE] else [LOCAL_MAX_ESTIM_ENTREGA_DATE] <= [LOCAL_EXPEDITION_DATE], type logical),
    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column Delayed Order",{{"COD_PAIS", "Country"}, {"ORDER_CODE", "Order Code"}, {"UNITS", "Units"}, {"LOCAL_PURCHASE_DATE", "Local Purchase Date"}, {"LOCAL_RECEPTION_DATE", "Local Reception Date"}, {"PACKING_DATE", "Local Packaging Date"}, {"LOCAL_EXPEDITION_DATE", "Local Expedition Date"}, {"LOCAL_REJECTION_DATE", "Local Rejection Date"}, {"LOCAL_CANCELLATION_DATE", "Local Cancellation Date"}, {"LOCAL_PICKING_START_DATE", "Local Picking Start Date"}, {"LOCAL_PICKING_END_DATE", "Local Picking End Date"}, {"STATUS", "Status"}, {"CANCEL_REASON", "Cancel Reason"}, {"COURIER", "Courier"}, {"LOCALIZACION_ENTREGA", "Delivery Location"}, {"DROP_POINT", "Drop Point"}, {"FAST_SINT", "Fast Sint"}, {"BUNDLES", "Bundles"}, {"BUNDLES_SIZE", "Bundles Size"}, {"TOTAL_IMPORT", "Total Import"}, {"CURRENCY", "Currency"}, {"LOCAL_PURCHASE_TIME", "Local Purchase Time"}, {"LOCAL_RECEPTION_TIME", "Local Reception Time"}, {"PACKING_TIME", "Local Packaging Time"}, {"LOCAL_EXPEDITION_TIME", "Local Expedition Time"}, {"LOCAL_REJECTION_TIME", "Local Rejection Time"}, {"LOCAL_CANCELLATION_TIME", "Local Cancellation Time"}, {"LOCAL_PICKING_START_TIME", "Local Picking Start Time"}, {"LOCAL_PICKING_END_TIME", "Local Picking End Time"}, {"LOCAL_MAX_ESTIM_ENTREGA_DATE", "Local Max Delivery Date"}, {"LOCAL_MAX_ESTIM_ENTREGA_TIME", "Local Max Delivery Time"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Order Code", "Country", "English Description", "Store Location", "Store Description", "ID Country-Store", "Status", "Equivalent Status", "Cancel Reason", "Local Purchase Date", "Local Purchase Time", "Local Reception Date", "Local Reception Time", "Local Picking Start Date", "Local Picking Start Time", "Local Picking End Date", "Local Picking End Time", "Local Packaging Date", "Local Packaging Time", "Packaging Date Pending", "Local Expedition Date", "Local Expedition Time", "Local Rejection Date", "Local Rejection Time", "Local Cancellation Date", "Local Cancellation Time", "Local Max Delivery Date", "Local Max Delivery Time", "Units", "Total Import", "Currency", "Operation Type", "Fast Sint", "Shipping Type", "Delivery Location", "Courier", "Locked", "Drop Point", "Bundles", "Bundles Size", "Diff Date Total Preparation", "Diff Date Reception", "Diff Date Picking", "Diff Date Packing", "Diff Date Expedition", "Diff Date Total Rejection", "Diff Date Rejection"})
in
    #"Reordered Columns"