// Zara_Returns_Store_MICRO
let
    Source = Table.Combine({Zara_Returns_Store_SINT_LASTMONTH, Zara_Returns_Store_PAT_LASTMONTH}),
    #"Renamed Columns" = Table.RenameColumns(Source,{{"ID_FECHA", "Date"}, {"DEVOLUCIONES", "Returns"}, {"UNIDADES", "Units"}, {"AMOUNT_EUROS", "Amount (€)"}, {"MARKET_ENGLISH", "Market English"},  {"LOCAL_AMOUNT", "Local Amount"}, {"LOCATION", "Location"}, {"PHYSICAL_STORE", "Physical Store"}, {"COUNTRY", "Country"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns",",","",Replacer.ReplaceText,{"Market English"}),
    #"Added Custom" = Table.AddColumn(#"Replaced Value", "Store Location", each Text.PadStart([Location], 5, "0"), type text),
    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Store Description", each [Store Location] & " - " & Text.AfterDelimiter([Physical Store], "- "), type text),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Market - Store", each [Market English] & " - " & [Store Description], type text),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "ID Country-Store", each Text.Combine({Text.From([Country], "es-ES"), "-", [Store Location]}), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom3",{"Physical Store", "Location"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns",{"Date", "ID Country-Store", "Country", "Market English", "Market - Store", "Store Location", "Store Description", "Operation Type", "Returns", "Units", "Amount (€)", "Local Amount"})
in
    #"Reordered Columns"