// PreSale_TMALL
let
    Source = DB2.Database("cneccdb2cisv1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="-- IBM DB2 - PREVENTA - BERSHKA#(lf)WITH PRINCIPAL AS#(lf)(#(lf)SELECT xo.ORDERS_ID wcs_order_id,#(lf)#(tab)o.TIMEPLACED order_timeplaced,#(lf)#(tab)o.STATUS wcs_order_status,#(lf)#(tab)o.MEMBER_ID customer_id,#(lf)#(tab)o.STOREENT_ID,#(lf)#(tab)oi.ORDERITEMS_ID order_items,#(lf)#(tab)oi.PARTNUM partnumber,#(lf)#(tab)oi.QUANTITY order_units,#(lf)#(tab)a.COUNTRY order_country,#(lf)#(tab)a.STATE order_state,#(lf)#(tab)a.CITY order_city,#(lf)#(tab)a.ZIPCODE order_zipcode,#(lf)#(tab)xoi.EXTFFMCENTER_ID stock_origin,#(lf)#(tab)ep.DESCRIPCION indom_status,#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN BITAND(p.ATRIBUTOS, POWER(2,9)) = POWER(2,9) THEN 'Sí' #(lf)#(tab)#(tab)ELSE 'No' #(lf)#(tab)END AS PREVENTA_INDOM,#(lf)#(tab)CASE #(lf)        WHEN lp.ID_LINEA_PEDIDO IS NULL THEN 'Línea desconocida INDOM'#(lf)        WHEN lpup.ID_TIPO_LINEA_PEDIDO_UNIDADES_PENDIENTES = 8 THEN 'Preventa'#(lf)        WHEN lpup.ID_TIPO_LINEA_PEDIDO_UNIDADES_PENDIENTES = 9 THEN 'Preventa ya liberada'#(lf)        ELSE 'No preventa'#(lf)    END AS PREVENTA,#(lf)#(tab)s.DIRECTORY virtual_store,#(lf)#(tab)xo.ID_EXTERNAL_MARKETPLACE_ORDER tmall_order_id,#(lf)#(tab)xo.ID_XMPS_ORDER_TYPE prepacking_order,#(lf)#(tab)xo.PAYMENT_RECEIVED tmall_payment_received,#(lf)#(tab)xo.ORDER_CANCELED tmall_order_canceled,#(lf)#(tab)xo.ORDER_UNLOCKED shipping_locked_release#(lf)FROM UECOITX_SP2.XMPS_ORDER xo#(lf)INNER JOIN UECOITX_SP2.ORDERS o#(lf)INNER JOIN UECOITX_SP2.ORDERITEMS oi#(lf)#(tab)ON oi.ORDERS_ID = o.ORDERS_ID#(lf)INNER JOIN UECOITX_SP2.XORDERITEMS_INFO xoi#(lf)#(tab)ON xoi.ORDERITEMS_ID = oi.ORDERITEMS_ID#(lf)#(tab)#(tab)ON o.ORDERS_ID = xo.ORDERS_ID#(lf)LEFT JOIN INDOM_ITX.PEDIDO p#(lf)INNER JOIN INDOM_ITX.ESTADO_PEDIDO ep#(lf)#(tab)ON ep.ID_ESTADO_PEDIDO = p.ID_ESTADO_PEDIDO#(lf)#(tab)#(tab)ON p.COD_PEDIDO_WCS = xo.ORDERS_ID#(lf)LEFT JOIN UECOITX_SP2.ADDRESS a#(lf)#(tab)ON o.ADDRESS_ID = a.ADDRESS_ID#(lf)LEFT JOIN UECOITX_SP2.STORE s#(lf)#(tab)ON xo.STORE_ID = s.STORE_ID#(lf)LEFT JOIN INDOM_ITX.LINEA_PEDIDO lp #(lf)#(tab)ON oi.ORDERITEMS_ID = lp.COD_LINEA_PEDIDO_WCS#(lf)LEFT JOIN INDOM_ITX.LINEA_PEDIDO_UNIDADES_PENDIENTES lpup #(lf)#(tab)ON lp.ID_LINEA_PEDIDO = lpup.ID_LINEA_PEDIDO#(lf)#(tab)#(tab)AND lpup.ID_ESTADO_INVENTARIO = 200#(lf)WHERE #(lf)#(tab)s.DIRECTORY = 'BershkaXT'#(lf)#(tab)#(tab)AND o.TIMEPLACED >= '2020-10-20' #(lf)),#(lf)PAGO_CONFIRMADO AS#(lf)(#(lf)SELECT xo.ORDERS_ID wcs_order_id,#(lf)#(tab)oi.ORDERITEMS_ID order_items,#(lf)#(tab)xoeu.EVENT_TIMESTAMP_UTC event_timestamp_utc,#(lf)#(tab)xoeu.ID_XMPS_ORDER_EVENT_TYPE event_type,#(lf)#(tab)xoeu.EVENT_PROCESS_STATUS event_process_status,#(lf)#(tab)xoeu.EVENT_PROCESS_DETAIL event_process_detail#(lf)FROM UECOITX_SP2.XMPS_ORDER xo#(lf)INNER JOIN UECOITX_SP2.XMPS_ORDER_EVENT_UPDATE xoeu#(lf)#(tab)ON xoeu.ID_XMPS_ORDER = xo.ID_XMPS_ORDER#(lf)INNER JOIN UECOITX_SP2.ORDERS o#(lf)INNER JOIN UECOITX_SP2.ORDERITEMS oi#(lf)#(tab)ON oi.ORDERS_ID = o.ORDERS_ID#(lf)#(tab)#(tab)ON o.ORDERS_ID = xo.ORDERS_ID#(lf)LEFT JOIN INDOM_ITX.PEDIDO p#(lf)INNER JOIN INDOM_ITX.ESTADO_PEDIDO ep#(lf)#(tab)ON ep.ID_ESTADO_PEDIDO = p.ID_ESTADO_PEDIDO#(lf)#(tab)#(tab)ON p.COD_PEDIDO_WCS = xo.ORDERS_ID#(lf)LEFT JOIN UECOITX_SP2.STORE s#(lf)#(tab)ON xo.STORE_ID = s.STORE_ID#(lf)WHERE #(lf)#(tab)s.DIRECTORY = 'BershkaXT'#(lf)#(tab)#(tab)AND xo.PAYMENT_RECEIVED = 1#(lf)#(tab)#(tab)#(tab)AND xoeu.ID_XMPS_ORDER_EVENT_TYPE = 8#(lf)),#(lf)PAGO_CANCELADO AS#(lf)(#(lf)SELECT xo.ORDERS_ID wcs_order_id,#(lf)#(tab)oi.ORDERITEMS_ID order_items,#(lf)#(tab)xoeu.EVENT_TIMESTAMP_UTC event_timestamp_utc,#(lf)#(tab)xoeu.ID_XMPS_ORDER_EVENT_TYPE event_type,#(lf)#(tab)xoeu.EVENT_PROCESS_STATUS event_process_status,#(lf)#(tab)xoeu.EVENT_PROCESS_DETAIL event_process_detail#(lf)FROM UECOITX_SP2.XMPS_ORDER xo#(lf)INNER JOIN UECOITX_SP2.XMPS_ORDER_EVENT_UPDATE xoeu#(lf)#(tab)ON xoeu.ID_XMPS_ORDER = xo.ID_XMPS_ORDER#(lf)INNER JOIN UECOITX_SP2.ORDERS o#(lf)INNER JOIN UECOITX_SP2.ORDERITEMS oi#(lf)#(tab)ON oi.ORDERS_ID = o.ORDERS_ID#(lf)#(tab)#(tab)ON o.ORDERS_ID = xo.ORDERS_ID#(lf)LEFT JOIN INDOM_ITX.PEDIDO p#(lf)INNER JOIN INDOM_ITX.ESTADO_PEDIDO ep#(lf)#(tab)ON ep.ID_ESTADO_PEDIDO = p.ID_ESTADO_PEDIDO#(lf)#(tab)#(tab)ON p.COD_PEDIDO_WCS = xo.ORDERS_ID#(lf)LEFT JOIN UECOITX_SP2.STORE s#(lf)#(tab)ON xo.STORE_ID = s.STORE_ID#(lf)WHERE #(lf)#(tab)s.DIRECTORY = 'BershkaXT'#(lf)#(tab)#(tab)AND xo.ORDER_CANCELED = 1#(lf)#(tab)#(tab)#(tab)AND xoeu.ID_XMPS_ORDER_EVENT_TYPE = 4#(lf)),#(lf)PEDIDO_DESBLOQUEADO AS#(lf)(#(lf)SELECT xo.ORDERS_ID wcs_order_id,#(lf)#(tab)oi.ORDERITEMS_ID order_items,#(lf)#(tab)xoeu.EVENT_TIMESTAMP_UTC event_timestamp_utc,#(lf)#(tab)xoeu.ID_XMPS_ORDER_EVENT_TYPE event_type,#(lf)#(tab)xoeu.EVENT_PROCESS_STATUS event_process_status,#(lf)#(tab)xoeu.EVENT_PROCESS_DETAIL event_process_detail#(lf)FROM UECOITX_SP2.XMPS_ORDER xo#(lf)INNER JOIN UECOITX_SP2.XMPS_ORDER_EVENT_UPDATE xoeu#(lf)#(tab)ON xoeu.ID_XMPS_ORDER = xo.ID_XMPS_ORDER#(lf)INNER JOIN UECOITX_SP2.ORDERS o#(lf)INNER JOIN UECOITX_SP2.ORDERITEMS oi#(lf)#(tab)ON oi.ORDERS_ID = o.ORDERS_ID#(lf)#(tab)#(tab)ON o.ORDERS_ID = xo.ORDERS_ID#(lf)LEFT JOIN INDOM_ITX.PEDIDO p#(lf)INNER JOIN INDOM_ITX.ESTADO_PEDIDO ep#(lf)#(tab)ON ep.ID_ESTADO_PEDIDO = p.ID_ESTADO_PEDIDO#(lf)#(tab)#(tab)ON p.COD_PEDIDO_WCS = xo.ORDERS_ID#(lf)LEFT JOIN UECOITX_SP2.STORE s#(lf)#(tab)ON xo.STORE_ID = s.STORE_ID#(lf)WHERE #(lf)#(tab)s.DIRECTORY = 'BershkaXT'#(lf)#(tab)#(tab)AND xo.ORDER_UNLOCKED = 1#(lf)#(tab)#(tab)#(tab)AND xoeu.ID_XMPS_ORDER_EVENT_TYPE = 5#(lf))#(lf)SELECT #(lf)#(tab)pr.wcs_order_id,#(lf)#(tab)pr.order_timeplaced,#(lf)#(tab)FROM_UTC_TIMESTAMP(TO_UTC_TIMESTAMP(pr.order_timeplaced, 'Europe/Dublin'), l.HUSO_HORARIO) order_localtimeplaced,#(lf)#(tab)pr.wcs_order_status,#(lf)#(tab)pr.customer_id,#(lf)#(tab)pr.order_items,#(lf)#(tab)pr.partnumber,#(lf)#(tab)pr.order_units,#(lf)#(tab)pr.order_country,#(lf)#(tab)pr.order_state,#(lf)#(tab)pr.order_city,#(lf)#(tab)pr.order_zipcode,#(lf)#(tab)pr.stock_origin,#(lf)#(tab)pr.indom_status,#(lf)#(tab)pr.preventa_indom,#(lf)#(tab)pr.preventa,#(lf)#(tab)pr.virtual_store,#(lf)#(tab)pr.tmall_order_id,#(lf)#(tab)pr.prepacking_order,#(lf)#(tab)pr.tmall_payment_received,#(lf)#(tab)pr.tmall_order_canceled,#(lf)#(tab)pr.shipping_locked_release,#(lf)#(tab)pcon.event_timestamp_utc,#(lf)#(tab)FROM_UTC_TIMESTAMP(pcon.event_timestamp_utc, l.HUSO_HORARIO) confirmado_event_timestamp_local,#(lf)#(tab)pcon.event_type,#(lf)#(tab)pcon.event_process_status,#(lf)#(tab)pcon.event_process_detail,#(lf)#(tab)pcan.event_timestamp_utc,#(lf)#(tab)FROM_UTC_TIMESTAMP(pcan.event_timestamp_utc, l.HUSO_HORARIO) cancelado_event_timestamp_local,#(lf)#(tab)pcan.event_type,#(lf)#(tab)pcan.event_process_status,#(lf)#(tab)pcan.event_process_detail,#(lf)#(tab)des.event_timestamp_utc,#(lf)#(tab)FROM_UTC_TIMESTAMP(des.event_timestamp_utc, l.HUSO_HORARIO) desbloqueado_event_timestamp_local,#(lf)#(tab)des.event_type,#(lf)#(tab)des.event_process_status,#(lf)#(tab)des.event_process_detail#(lf)FROM PRINCIPAL pr#(lf)LEFT JOIN  PAGO_CONFIRMADO pcon#(lf)#(tab)ON pcon.wcs_order_id = pr.wcs_order_id#(lf)#(tab)#(tab)AND pcon.order_items = pr.order_items#(lf)LEFT JOIN PAGO_CANCELADO pcan#(lf)#(tab)ON pcan.wcs_order_id = pr.wcs_order_id#(lf)#(tab)#(tab)AND pcan.order_items= pr.order_items#(lf)LEFT JOIN PEDIDO_DESBLOQUEADO des#(lf)#(tab)ON des.wcs_order_id = pr.wcs_order_id#(lf)#(tab)#(tab)AND des.order_items = pr.order_items#(lf)INNER JOIN MAESTROS.ENTIDAD_ECOMMERCE ee#(lf)#(tab)ON ee.COD_ENTIDAD_ECOMMERCE_WCS = pr.STOREENT_ID#(lf)INNER JOIN MAESTROS.ENTIDAD_ECOMMERCE_LOCALIZACION eel#(lf)#(tab)ON eel.ID_ENTIDAD_ECOMMERCE = ee.ID_ENTIDAD_ECOMMERCE#(lf)INNER JOIN MAESTROS.LOCALIZACION l#(lf)#(tab)ON l.ID_LOCALIZACION = eel.ID_LOCALIZACION#(lf)WITH UR;"]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"WCS_ORDER_ID", type text}, {"ORDER_UNITS", Int64.Type}, {"TMALL_ORDER_ID", type text}, {"PREPACKING_ORDER", type text}, {"TMALL_PAYMENT_RECEIVED", type text}, {"TMALL_ORDER_CANCELED", type text}, {"SHIPPING_LOCKED_RELEASE", type text}, {"ORDER_ITEMS", type text}, {"CUSTOMER_ID", type text}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Changed Type",{{"WCS_ORDER_ID", "Order"}, {"ORDER_TIMEPLACED", "Order Timeplaced"}, {"ORDER_LOCALTIMEPLACED", "Order Local Timeplaced"}, {"WCS_ORDER_STATUS", "Order Status"}, {"CUSTOMER_ID", "Customer ID"}, {"ORDER_ITEMS", "Order Items"}, {"PARTNUMBER", "Partnumber"}, {"ORDER_UNITS", "Order Units"}, {"ORDER_COUNTRY", "Order Country"}, {"ORDER_STATE", "Order State"}, {"ORDER_CITY", "Order City"}, {"ORDER_ZIPCODE", "Order ZipCode"}, {"STOCK_ORIGIN", "Stock Origin"}, {"INDOM_STATUS", "INDOM Status"}, {"PREVENTA", "Preventa INDOM"}, {"PREVENTA_INDOM", "Preventa"}, {"VIRTUAL_STORE", "Virtual Store"}, {"TMALL_ORDER_ID", "TMALL Order"}, {"PREPACKING_ORDER", "Prepacking Order"}, {"TMALL_PAYMENT_RECEIVED", "TMALL Payment Received"}, {"TMALL_ORDER_CANCELED", "TMALL Order Canceled"}, {"SHIPPING_LOCKED_RELEASE", "Shipping Locked Release"}, {"EVENT_TIMESTAMP_UTC", "TMALL Payment Received UTC"}, {"CONFIRMADO_EVENT_TIMESTAMP_LOCAL", "TMALL Payment Received Local"}, {"EVENT_TYPE", "Event Type"}, {"EVENT_PROCESS_STATUS", "Event Process Status"}, {"EVENT_PROCESS_DETAIL", "Event Process Detail"}, {"EVENT_TIMESTAMP_UTC2", "TMALL Order Canceled UTC"}, {"CANCELADO_EVENT_TIMESTAMP_LOCAL", "TMALL Order Canceled Local"}, {"EVENT_TYPE2", "Event Type 2"}, {"EVENT_PROCESS_STATUS2", "Event Process Status 2"}, {"EVENT_PROCESS_DETAIL2", "Event Process Detail 2"}, {"EVENT_TIMESTAMP_UTC3", "Shipping Locked Release UTC"}, {"DESBLOQUEADO_EVENT_TIMESTAMP_LOCAL", "Shipping Locked Release Local"}, {"EVENT_TYPE3", "Event Type 3"}, {"EVENT_PROCESS_STATUS3", "Event Process Status 3"}, {"EVENT_PROCESS_DETAIL3", "Event Process Detail 3"}}),
    #"Fecha insertada" = Table.AddColumn(#"Columnas con nombre cambiado", "Fecha", each DateTime.Date([Order Timeplaced]), type date),
    #"Hora insertada" = Table.AddColumn(#"Fecha insertada", "Hora", each DateTime.Time([Order Timeplaced]), type time),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Hora insertada",{"Order", "Order Timeplaced", "Fecha", "Hora", "Order Local Timeplaced", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC", "TMALL Payment Received Local", "Event Type", "Event Process Status", "Event Process Detail", "TMALL Order Canceled UTC", "TMALL Order Canceled Local", "Event Type 2", "Event Process Status 2", "Event Process Detail 2", "Shipping Locked Release UTC", "Shipping Locked Release Local", "Event Type 3", "Event Process Status 3", "Event Process Detail 3"}),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas reordenadas",{{"Fecha", "Order Timeplaced Date"}, {"Hora", "Order Timeplaced Time"}}),
    #"Fecha insertada1" = Table.AddColumn(#"Columnas con nombre cambiado1", "Fecha", each DateTime.Date([Order Local Timeplaced]), type date),
    #"Hora insertada1" = Table.AddColumn(#"Fecha insertada1", "Hora", each DateTime.Time([Order Local Timeplaced]), type time),
    #"Columnas reordenadas1" = Table.ReorderColumns(#"Hora insertada1",{"Order", "Order Timeplaced", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced", "Fecha", "Hora", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC", "TMALL Payment Received Local", "Event Type", "Event Process Status", "Event Process Detail", "TMALL Order Canceled UTC", "TMALL Order Canceled Local", "Event Type 2", "Event Process Status 2", "Event Process Detail 2", "Shipping Locked Release UTC", "Shipping Locked Release Local", "Event Type 3", "Event Process Status 3", "Event Process Detail 3"}),
    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Columnas reordenadas1",{{"Fecha", "Order Local Timeplaced Date"}, {"Hora", "Order Local Timeplaced Time"}}),
    #"Fecha insertada2" = Table.AddColumn(#"Columnas con nombre cambiado2", "Fecha", each DateTime.Date([TMALL Payment Received UTC]), type date),
    #"Hora insertada2" = Table.AddColumn(#"Fecha insertada2", "Hora", each DateTime.Time([TMALL Payment Received UTC]), type time),
    #"Columnas reordenadas2" = Table.ReorderColumns(#"Hora insertada2",{"Order", "Order Timeplaced", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC", "Fecha", "Hora", "TMALL Payment Received Local", "Event Type", "Event Process Status", "Event Process Detail", "TMALL Order Canceled UTC", "TMALL Order Canceled Local", "Event Type 2", "Event Process Status 2", "Event Process Detail 2", "Shipping Locked Release UTC", "Shipping Locked Release Local", "Event Type 3", "Event Process Status 3", "Event Process Detail 3"}),
    #"Columnas con nombre cambiado3" = Table.RenameColumns(#"Columnas reordenadas2",{{"Fecha", "TMALL Payment Received UTC Date"}, {"Hora", "TMALL Payment Received UTC Time"}}),
    #"Fecha insertada3" = Table.AddColumn(#"Columnas con nombre cambiado3", "Fecha", each DateTime.Date([TMALL Payment Received Local]), type date),
    #"Hora insertada3" = Table.AddColumn(#"Fecha insertada3", "Hora", each DateTime.Time([TMALL Payment Received Local]), type time),
    #"Columnas reordenadas3" = Table.ReorderColumns(#"Hora insertada3",{"Order", "Order Timeplaced", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local", "Fecha", "Hora", "Event Type", "Event Process Status", "Event Process Detail", "TMALL Order Canceled UTC", "TMALL Order Canceled Local", "Event Type 2", "Event Process Status 2", "Event Process Detail 2", "Shipping Locked Release UTC", "Shipping Locked Release Local", "Event Type 3", "Event Process Status 3", "Event Process Detail 3"}),
    #"Columnas con nombre cambiado4" = Table.RenameColumns(#"Columnas reordenadas3",{{"Fecha", "TMALL Payment Received Local Date"}, {"Hora", "TMALL Payment Received Local Time"}}),
    #"Fecha insertada4" = Table.AddColumn(#"Columnas con nombre cambiado4", "Fecha", each DateTime.Date([TMALL Order Canceled UTC]), type date),
    #"Hora insertada4" = Table.AddColumn(#"Fecha insertada4", "Hora", each DateTime.Time([TMALL Order Canceled UTC]), type time),
    #"Columnas reordenadas4" = Table.ReorderColumns(#"Hora insertada4",{"Order", "Order Timeplaced", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local", "TMALL Payment Received Local Date", "TMALL Payment Received Local Time", "Event Type", "Event Process Status", "Event Process Detail", "TMALL Order Canceled UTC", "Fecha", "Hora", "TMALL Order Canceled Local", "Event Type 2", "Event Process Status 2", "Event Process Detail 2", "Shipping Locked Release UTC", "Shipping Locked Release Local", "Event Type 3", "Event Process Status 3", "Event Process Detail 3"}),
    #"Columnas con nombre cambiado5" = Table.RenameColumns(#"Columnas reordenadas4",{{"Fecha", "TMALL Order Canceled UTC Date"}, {"Hora", "TMALL Order Canceled UTC Time"}}),
    #"Fecha insertada5" = Table.AddColumn(#"Columnas con nombre cambiado5", "Fecha", each DateTime.Date([TMALL Order Canceled Local]), type date),
    #"Hora insertada5" = Table.AddColumn(#"Fecha insertada5", "Hora", each DateTime.Time([TMALL Payment Received Local]), type time),
    #"Columnas reordenadas5" = Table.ReorderColumns(#"Hora insertada5",{"Order", "Order Timeplaced", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local", "TMALL Payment Received Local Date", "TMALL Payment Received Local Time", "Event Type", "Event Process Status", "Event Process Detail", "TMALL Order Canceled UTC", "TMALL Order Canceled UTC Date", "TMALL Order Canceled UTC Time", "TMALL Order Canceled Local", "Fecha", "Hora", "Event Type 2", "Event Process Status 2", "Event Process Detail 2", "Shipping Locked Release UTC", "Shipping Locked Release Local", "Event Type 3", "Event Process Status 3", "Event Process Detail 3"}),
    #"Columnas con nombre cambiado6" = Table.RenameColumns(#"Columnas reordenadas5",{{"Fecha", "TMALL Order Canceled Local Date"}, {"Hora", "TMALL Order Canceled Local Time"}}),
    #"Fecha insertada6" = Table.AddColumn(#"Columnas con nombre cambiado6", "Fecha", each DateTime.Date([Shipping Locked Release UTC]), type date),
    #"Hora insertada6" = Table.AddColumn(#"Fecha insertada6", "Hora", each DateTime.Time([Shipping Locked Release UTC]), type time),
    #"Columnas reordenadas6" = Table.ReorderColumns(#"Hora insertada6",{"Order", "Order Timeplaced", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local", "TMALL Payment Received Local Date", "TMALL Payment Received Local Time", "Event Type", "Event Process Status", "Event Process Detail", "TMALL Order Canceled UTC", "TMALL Order Canceled UTC Date", "TMALL Order Canceled UTC Time", "TMALL Order Canceled Local", "TMALL Order Canceled Local Date", "TMALL Order Canceled Local Time", "Event Type 2", "Event Process Status 2", "Event Process Detail 2", "Shipping Locked Release UTC", "Fecha", "Hora", "Shipping Locked Release Local", "Event Type 3", "Event Process Status 3", "Event Process Detail 3"}),
    #"Columnas con nombre cambiado7" = Table.RenameColumns(#"Columnas reordenadas6",{{"Fecha", "Shipping Locked Release UTC Date"}, {"Hora", "Shipping Locked Release UTC Time"}}),
    #"Fecha insertada7" = Table.AddColumn(#"Columnas con nombre cambiado7", "Fecha", each DateTime.Date([Shipping Locked Release Local]), type date),
    #"Hora insertada7" = Table.AddColumn(#"Fecha insertada7", "Hora", each DateTime.Time([Shipping Locked Release Local]), type time),
    #"Columnas reordenadas7" = Table.ReorderColumns(#"Hora insertada7",{"Order", "Order Timeplaced", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local", "TMALL Payment Received Local Date", "TMALL Payment Received Local Time", "Event Type", "Event Process Status", "Event Process Detail", "TMALL Order Canceled UTC", "TMALL Order Canceled UTC Date", "TMALL Order Canceled UTC Time", "TMALL Order Canceled Local", "TMALL Order Canceled Local Date", "TMALL Order Canceled Local Time", "Event Type 2", "Event Process Status 2", "Event Process Detail 2", "Shipping Locked Release UTC", "Shipping Locked Release UTC Date", "Shipping Locked Release UTC Time", "Shipping Locked Release Local", "Fecha", "Hora", "Event Type 3", "Event Process Status 3", "Event Process Detail 3"}),
    #"Columnas con nombre cambiado8" = Table.RenameColumns(#"Columnas reordenadas7",{{"Fecha", "Shipping Locked Release Local Date"}, {"Hora", "Shipping Locked Release Local Time"}}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Columnas con nombre cambiado8",{"Order Timeplaced", "Order Local Timeplaced", "TMALL Payment Received UTC", "TMALL Payment Received Local", "TMALL Order Canceled UTC", "TMALL Order Canceled Local", "Shipping Locked Release UTC", "Shipping Locked Release Local", "Event Type", "Event Type 2", "Event Type 3"}),
    #"Columnas con nombre cambiado9" = Table.RenameColumns(#"Columnas quitadas",{{"Event Process Status", "TMALL Payment Received Process Status"}, {"Event Process Detail", "TMALL Payment Received Process Detail"}, {"Event Process Status 2", "TMALL Order Canceled Process Status"}, {"Event Process Detail 2", "TMALL Order Canceled Process Detail"}, {"Event Process Status 3", "Shipping Locked Release Process Status"}, {"Event Process Detail 3", "Shipping Locked Release Process Detail"}}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Columnas con nombre cambiado9","0","No",Replacer.ReplaceText,{"Prepacking Order"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","1","Yes",Replacer.ReplaceText,{"Prepacking Order"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","0","No",Replacer.ReplaceText,{"TMALL Payment Received"}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2",null,"Not informed",Replacer.ReplaceValue,{"TMALL Payment Received"}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","1","Yes",Replacer.ReplaceText,{"TMALL Payment Received"}),
    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","0","No",Replacer.ReplaceText,{"TMALL Order Canceled"}),
    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5",null,"Not informed",Replacer.ReplaceValue,{"TMALL Order Canceled"}),
    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6","1","Yes",Replacer.ReplaceText,{"TMALL Order Canceled"}),
    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","0","No",Replacer.ReplaceText,{"Shipping Locked Release"}),
    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","1","Yes",Replacer.ReplaceText,{"Shipping Locked Release"}),
    #"Valor reemplazado10" = Table.ReplaceValue(#"Valor reemplazado9",null,"Not informed",Replacer.ReplaceValue,{"Shipping Locked Release"}),
    #"Valor reemplazado11" = Table.ReplaceValue(#"Valor reemplazado10",null,"Not informed",Replacer.ReplaceValue,{"INDOM Status"}),
    #"Columna condicional agregada" = Table.AddColumn(#"Valor reemplazado11", "Type Stock Origin", each if [Stock Origin] = null then "Not informed" else if Text.Contains([Stock Origin], "WMS") then "Warehouse" else if Text.Contains([Stock Origin], "PST") then "Store" else if Text.Contains([Stock Origin], "FFM") then "Marketplace" else "UNKNOWN"),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"Type Stock Origin", type text}}),
    #"Columnas reordenadas8" = Table.ReorderColumns(#"Tipo cambiado",{"Order", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Order State", "Order City", "Order ZipCode", "Type Stock Origin", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local Date", "TMALL Payment Received Local Time", "TMALL Payment Received Process Status", "TMALL Payment Received Process Detail", "TMALL Order Canceled UTC Date", "TMALL Order Canceled UTC Time", "TMALL Order Canceled Local Date", "TMALL Order Canceled Local Time", "TMALL Order Canceled Process Status", "TMALL Order Canceled Process Detail", "Shipping Locked Release UTC Date", "Shipping Locked Release UTC Time", "Shipping Locked Release Local Date", "Shipping Locked Release Local Time", "Shipping Locked Release Process Status", "Shipping Locked Release Process Detail"}),
    #"Columna condicional agregada1" = Table.AddColumn(#"Columnas reordenadas8", "Country", each if [Order Country] = "CN" then "China" else "UNKNOWN"),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columna condicional agregada1",{{"Country", type text}}),
    #"Columnas reordenadas9" = Table.ReorderColumns(#"Tipo cambiado1",{"Order", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Order Country", "Country", "Order State", "Order City", "Order ZipCode", "Type Stock Origin", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local Date", "TMALL Payment Received Local Time", "TMALL Payment Received Process Status", "TMALL Payment Received Process Detail", "TMALL Order Canceled UTC Date", "TMALL Order Canceled UTC Time", "TMALL Order Canceled Local Date", "TMALL Order Canceled Local Time", "TMALL Order Canceled Process Status", "TMALL Order Canceled Process Detail", "Shipping Locked Release UTC Date", "Shipping Locked Release UTC Time", "Shipping Locked Release Local Date", "Shipping Locked Release Local Time", "Shipping Locked Release Process Status", "Shipping Locked Release Process Detail"}),
    #"Columnas quitadas1" = Table.RemoveColumns(#"Columnas reordenadas9",{"Order Country"}),
    #"Columna condicional agregada2" = Table.AddColumn(#"Columnas quitadas1", "State", each if Text.Contains([Order State], "CN11") then "CN-BJ" else if Text.Contains([Order State], "CN12") then "CN-TJ" else if Text.Contains([Order State], "CN13") then "CN-HE" else if Text.Contains([Order State], "CN14") then "CN-SX" else if Text.Contains([Order State], "CN15") then "CN-NM" else if Text.Contains([Order State], "CN21") then "CN-LN" else if Text.Contains([Order State], "CN22") then "CN-JL" else if Text.Contains([Order State], "CN23") then "CN-HL" else if Text.Contains([Order State], "CN31") then "CN-SH" else if Text.Contains([Order State], "CN32") then "CN-JS" else if Text.Contains([Order State], "CN33") then "CN-ZJ" else if Text.Contains([Order State], "CN34") then "CN-AH" else if Text.Contains([Order State], "CN35") then "CN-FJ" else if Text.Contains([Order State], "CN36") then "CN-JX" else if Text.Contains([Order State], "CN37") then "CN-SD" else if Text.Contains([Order State], "CN41") then "CN-HA" else if Text.Contains([Order State], "CN42") then "CN-HB" else if Text.Contains([Order State], "CN43") then "CN-HN" else if Text.Contains([Order State], "CN44") then "CN-GD" else if Text.Contains([Order State], "CN45") then "CN-GX" else if Text.Contains([Order State], "CN46") then "CN-HI" else if Text.Contains([Order State], "CN50") then "CN-CQ" else if Text.Contains([Order State], "CN51") then "CN-SC" else if Text.Contains([Order State], "CN52") then "CN-GZ" else if Text.Contains([Order State], "CN53") then "CN-YN" else if Text.Contains([Order State], "CN54") then "CN-XZ" else if Text.Contains([Order State], "CN61") then "CN-SN" else if Text.Contains([Order State], "CN62") then "CN-GS" else if Text.Contains([Order State], "CN63") then "CN-GS" else if Text.Contains([Order State], "CN64") then "CN-NX" else if Text.Contains([Order State], "CN65") then "CN-XJ" else if Text.Contains([Order State], "CN71") then "CN-TW" else if Text.Contains([Order State], "CN91") then "CN-HK" else if Text.Contains([Order State], "CN92") then "CN-MO" else if Text.Contains([Order State], "CN") then "CN" else "UNKNOWN"),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columna condicional agregada2",{{"State", type text}}),
    #"Consultas combinadas" = Table.NestedJoin(#"Tipo cambiado2", {"State"}, #"China Status", {"State Code"}, "China Status", JoinKind.LeftOuter),
    #"Se expandió China Status" = Table.ExpandTableColumn(#"Consultas combinadas", "China Status", {"State Chinese", "State ISO"}, {"State Chinese", "State ISO"}),
    #"Columnas reordenadas10" = Table.ReorderColumns(#"Se expandió China Status",{"Order", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Country", "Order State", "State", "State Chinese", "State ISO", "Order City", "Order ZipCode", "Type Stock Origin", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local Date", "TMALL Payment Received Local Time", "TMALL Payment Received Process Status", "TMALL Payment Received Process Detail", "TMALL Order Canceled UTC Date", "TMALL Order Canceled UTC Time", "TMALL Order Canceled Local Date", "TMALL Order Canceled Local Time", "TMALL Order Canceled Process Status", "TMALL Order Canceled Process Detail", "Shipping Locked Release UTC Date", "Shipping Locked Release UTC Time", "Shipping Locked Release Local Date", "Shipping Locked Release Local Time", "Shipping Locked Release Process Status", "Shipping Locked Release Process Detail"}),
    #"Columnas quitadas2" = Table.RemoveColumns(#"Columnas reordenadas10",{"Order State"}),
    #"Columnas con nombre cambiado10" = Table.RenameColumns(#"Columnas quitadas2",{{"Order City", "City"}, {"Order ZipCode", "ZipCode"}}),
    #"Valor reemplazado12" = Table.ReplaceValue(#"Columnas con nombre cambiado10",null,"Not informed",Replacer.ReplaceValue,{"Stock Origin"}),
    #"Hora insertada8" = Table.AddColumn(#"Valor reemplazado12", "Hora", each Time.Hour([Order Local Timeplaced Time]), Int64.Type),
    #"Minuto insertado" = Table.AddColumn(#"Hora insertada8", "Minuto", each Time.Minute([Order Local Timeplaced Time]), Int64.Type),
    #"Columnas reordenadas11" = Table.ReorderColumns(#"Minuto insertado",{"Order", "Order Timeplaced Date", "Order Timeplaced Time", "Order Local Timeplaced Date", "Order Local Timeplaced Time", "Hora", "Minuto", "Order Status", "Customer ID", "Order Items", "Partnumber", "Order Units", "Country", "State", "State Chinese", "State ISO", "City", "ZipCode", "Type Stock Origin", "Stock Origin", "INDOM Status", "Preventa", "Preventa INDOM", "Virtual Store", "TMALL Order", "Prepacking Order", "TMALL Payment Received", "TMALL Order Canceled", "Shipping Locked Release", "TMALL Payment Received UTC Date", "TMALL Payment Received UTC Time", "TMALL Payment Received Local Date", "TMALL Payment Received Local Time", "TMALL Payment Received Process Status", "TMALL Payment Received Process Detail", "TMALL Order Canceled UTC Date", "TMALL Order Canceled UTC Time", "TMALL Order Canceled Local Date", "TMALL Order Canceled Local Time", "TMALL Order Canceled Process Status", "TMALL Order Canceled Process Detail", "Shipping Locked Release UTC Date", "Shipping Locked Release UTC Time", "Shipping Locked Release Local Date", "Shipping Locked Release Local Time", "Shipping Locked Release Process Status", "Shipping Locked Release Process Detail"}),
    #"Columnas con nombre cambiado11" = Table.RenameColumns(#"Columnas reordenadas11",{{"Hora", "Order Local Timeplaced  Hour"}, {"Minuto", "Order Local Timeplaced  Minute"}})
in
    #"Columnas con nombre cambiado11"