// Pedidos_SINT_Cadenas_Tienda_FY2020
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - PEDIDOS SINT - BERSHKA - TIENDA - FY2020#(lf)SELECT#(lf)#(tab)mf.ID_FECHA,#(lf)#(tab)COUNT(DISTINCT mf.ID_PEDIDO_ECOMMERCE) pedidos,#(lf)#(tab)SUM(mf.UNIDADES) unidades,#(lf)#(tab)SUM(mf.IMPORTE) local_amount,#(lf)#(tab)SUM(ROUND (mf.IMPORTE * mf.CAMBIO_REFERENCIA, 2)) amount_euros,#(lf)#(tab)mf.ID_CADENA,#(lf)#(tab)dp.DESCRIPCION market,#(lf)#(tab)dl1.LOCALIZACION location,#(lf)#(tab)dl1.DESCRIPCION physical_store#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)#(tab)ON (dp.ID_PAIS = mf.ID_PAIS)#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)    ON (dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING)#(lf)        AND (dl1.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121)) -- PICKING EN TIENDA#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)    ON (dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALMACEN)#(lf)        AND (dl2.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121)) -- EXPEDICIÓN DESDE TIENDA#(lf)WHERE#(lf)#(tab)mf.ID_FECHA_PLATAFORMA >= TO_DATE ('01/01/2020', 'DD/MM/YYYY')#(lf)#(tab)#(tab)AND mf.ID_FECHA_PLATAFORMA < TO_DATE ('01/03/2021', 'DD/MM/YYYY')#(lf)#(tab)AND mf.ID_FECHA >= TO_DATE ('01/02/2020', 'DD/MM/YYYY') #(lf)#(tab)#(tab)AND mf.ID_FECHA < TO_DATE ('01/02/2021', 'DD/MM/YYYY')#(lf)#(tab)AND mf.ID_TIPO_MOVIMIENTO IN (72, 772) -- ORDER TRANSACTION#(lf)#(tab)AND mf.ID_CADENA = 5 -- BERSHKA#(lf)#(tab)AND mf.ESTADO NOT IN ('X', 'N', 'PQ') -- DRIVE CADENAS#(lf)#(tab)AND mf.REPOSICION = 0 -- DRIVE#(lf)        AND mf.ES_CAMBIO = 0 -- DRIVE#(lf)#(tab)AND mf.ID_SECCION > 0 -- DRIVE#(lf)#(tab)AND mf.ID_PAIS > 0 -- DRIVE#(lf)GROUP BY#(lf)#(tab)mf.ID_FECHA,#(lf)#(tab)mf.ID_CADENA,#(lf)#(tab)dp.DESCRIPCION, #(lf)#(tab)dl1.LOCALIZACION,#(lf)#(tab)dl1.DESCRIPCION", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"UNIDADES", Int64.Type}, {"LOCAL_AMOUNT", Currency.Type}, {"AMOUNT_EUROS", Currency.Type}, {"ID_CADENA", Int64.Type}, {"LOCATION", Int64.Type}, {"PEDIDOS", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ID_FECHA", "Fecha Pedido"}, {"UNIDADES", "Unidades"}, {"LOCAL_AMOUNT", "Importe (ML)"}, {"AMOUNT_EUROS", "Importe (€)"}, {"ID_CADENA", "ID Cadena"}, {"MARKET", "Mercado"}, {"LOCATION", "ID Localizacion"}, {"PHYSICAL_STORE", "Tienda Física"}, {"PEDIDOS", "Pedidos"}}),
    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Tipo Operativa", each "SINT"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Tipo Operativa", type text}})
in
    #"Changed Type1"