// Pedidos_SINT_SINT_Plus_Tienda
let
    Source = Table.Combine({Pedidos_SINT_Cadenas_Tienda_FY2019, Pedidos_SINT_Cadenas_Tienda_FY2020, Pedidos_SINT_Cadenas_Tienda_FY2021, Pedidos_SINT_Plus_Cadenas_Tienda_FY2019, Pedidos_SINT_Plus_Cadenas_Tienda_FY2020, Pedidos_SINT_Plus_Cadenas_Tienda_FY2021}),
    #"Added Custom" = Table.AddColumn(Source, "Localización", each Text.PadStart(Number.ToText([ID Localizacion]), 5, "0")),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom",{{"Localización", type text}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"Fecha Pedido", "Pedidos", "Unidades", "Importe (ML)", "Importe (€)", "ID Cadena", "Mercado", "ID Localizacion", "Localización", "Tienda Física"}),
    #"Added Conditional Column" = Table.AddColumn(#"Reordered Columns", "Cadena", each if [ID Cadena] = 1 then "ZARA" else if [ID Cadena] = 2 then "ZARA" else if [ID Cadena] = 3 then "PULL & BEAR" else if [ID Cadena] = 5 then "BERSHKA" else if [ID Cadena] = 6 then "STRADIVARIUS" else if [ID Cadena] = 7 then "OYSHO" else if [ID Cadena] = 11 then "MASSIMO DUTTI" else if [ID Cadena] = 14 then "ZARA HOME" else if [ID Cadena] = 16 then "UTERQÜE" else if [ID Cadena] = 8 then "LEFTIES" else "DESCONOCIDA"),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Conditional Column",{{"Cadena", type text}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type1",{"Fecha Pedido", "Pedidos", "Unidades", "Importe (ML)", "Importe (€)", "ID Cadena", "Cadena", "Mercado", "ID Localizacion", "Localización", "Tienda Física", "Tipo Operativa"}),
    #"Added Conditional Column1" = Table.AddColumn(#"Reordered Columns1", "Tipo Tienda", each if [ID Localizacion] = 3167 then "Regular Store" else if Text.Contains([Tienda Física], "PACK") then "Packing Store" else "Regular Store"),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column1",{{"Tipo Tienda", type text}})
in
    #"Changed Type2"