// PEDIDOS_BF
let
    Source = DB2.Database("ieecdb2v1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="SELECT ee.DESCRIPCION AS TIENDA_ONLINE, p.FECHA_HORA_PEDIDO, p.FECHA_ALTA,p.COD_PEDIDO_WCS, #(lf)CASE WHEN p.ID_ESTADO_PEDIDO IN (1,2,15,16,20) THEN 'RESERVADO'#(lf)WHEN p.ID_ESTADO_PEDIDO IN (3,4,23) THEN 'ALMACEN'#(lf)WHEN p.ID_ESTADO_PEDIDO IN (5) THEN 'ENVIADO'#(lf)WHEN p.ID_ESTADO_PEDIDO IN (6) THEN 'PENDIENTE_ENTREGA'#(lf)WHEN p.ID_ESTADO_PEDIDO IN (7) THEN 'ENTREGADO'#(lf)WHEN p.ID_ESTADO_PEDIDO IN (8) THEN 'ENTREGADO_INCIDENCIA'#(lf)WHEN p.ID_ESTADO_PEDIDO IN (13) THEN 'RECHAZADO'#(lf)WHEN p.ID_ESTADO_PEDIDO IN (10,11,17,22) THEN 'EDICION/II'#(lf)WHEN p.ID_ESTADO_PEDIDO IN (9,12,18,19) THEN 'CANCELADO'#(lf)ELSE 'OTROS'#(lf)END AS ESTADO_PEDIDO,#(lf)sp.CODIGO_RASTREO AS COD_SUBPEDIDO,#(lf)esp.DESCRIPCION AS ESTADO_SUBPEDIDO,#(lf)os.COD_ORIGEN_STOCK_WCS,#(lf)L.PARTNUMBER,#(lf)  l.CANTIDAD,#(lf)  CASE WHEN bitand(p.ATRIBUTOS,512) = 512 THEN 'SI' ELSE 'NO' END AS PRESALE_ORDER,#(lf)CASE WHEN bitand(p.ATRIBUTOS,power(2,17)) = power(2,17) THEN 'SI' ELSE 'NO' END AS CONSOLIDATION_ORDER,#(lf)CASE WHEN BITAND(sp.ATRIBUTOS,1048576)= 1048576 THEN 'SI' ELSE 'NO' END AS SILO,#(lf)case when BITAND(sp.atributos,16) = 16 then 'SI' else 'NO' end AS PICKING_transfer#(lf)FROM INDOM_ITX.PEDIDO p#(lf)JOIN INDOM_ITX.ENTIDAD_ECOMMERCE ee ON ee.ID_ENTIDAD_ECOMMERCE = p.ID_ENTIDAD_ECOMMERCE#(lf)JOIN INDOM_ITX.SUBPEDIDO sp ON sp.ID_PEDIDO = p.ID_PEDIDO#(lf)JOIN INDOM_ITX.ESTADO_SUBPEDIDO esp ON sp.ID_ESTADO_SUBPEDIDO = esp.ID_ESTADO_SUBPEDIDO#(lf)JOIN INDOM_ITX.ORIGEN_STOCK os ON sp.ID_ORIGEN_STOCK = os.ID_ORIGEN_STOCK#(lf)LEFT JOIN INDOM_ITX.LINEA_PEDIDO L ON L.ID_SUBPEDIDO = SP.ID_SUBPEDIDO#(lf)--WHERE p.COD_PEDIDO_WCS in '51486378962'-- Buscar por COD_PEDIDO_WCS#(lf)WHERE os.ID_CADENA = 4 and os.ID_PAIS = 1-- Filtrar por cadena y país -- in (2,4,6,7,8,11,14,18), todos los países#(lf)and #(lf)    --sp.FECHA_ALTA > current timestamp - 2 day -- Días 25,26,27#(lf)sp.FECHA_ALTA >= '2020-12-03 00:00:00.000'#(lf)AND sp.FECHA_ALTA < '2020-12-05 00:00:00.000'#(lf)order by 1 asc, 4 asc, 3 asc#(lf)WITH UR"]),
    #"Inserted Time" = Table.AddColumn(Source, "Hora Pedido", each DateTime.Time([FECHA_HORA_PEDIDO]), type time),
    #"Inserted Time1" = Table.AddColumn(#"Inserted Time", "Hora Alta", each DateTime.Time([FECHA_ALTA]), type time),
    #"Changed Type" = Table.TransformColumnTypes(#"Inserted Time1",{{"FECHA_HORA_PEDIDO", type date}, {"FECHA_ALTA", type date}, {"COD_PEDIDO_WCS", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"TIENDA_ONLINE", "Market"}, {"FECHA_HORA_PEDIDO", "Fecha Pedido"}, {"FECHA_ALTA", "Fecha Alta"}, {"COD_PEDIDO_WCS", "COD Pedido WCS"}, {"ESTADO_PEDIDO", "Estado Pedido"}, {"COD_SUBPEDIDO", "COD Subpedido"}, {"COD_ORIGEN_STOCK_WCS", "COD Origen Stock WCS"}, {"PARTNUMBER", "Partnumber"}, {"CANTIDAD", "Cantidad"}, {"PRESALE_ORDER", "Presale Order"}, {"CONSOLIDATION_ORDER", "Consolidation Order"}, {"ESTADO_SUBPEDIDO", "Estado Subpedido"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Market", "Fecha Pedido", "Hora Pedido", "Fecha Alta", "Hora Alta", "COD Pedido WCS", "Estado Pedido", "COD Subpedido", "Estado Subpedido", "COD Origen Stock WCS", "Partnumber", "Cantidad", "Presale Order", "Consolidation Order", "SILO"}),
    #"Columna duplicada" = Table.DuplicateColumn(#"Reordered Columns", "COD Origen Stock WCS", "COD Origen Stock WCS - Copia"),
    #"Dividir columna por delimitador" = Table.SplitColumn(#"Columna duplicada", "COD Origen Stock WCS - Copia", Splitter.SplitTextByDelimiter("-", QuoteStyle.Csv), {"COD Origen Stock WCS - Copia.1", "COD Origen Stock WCS - Copia.2", "COD Origen Stock WCS - Copia.3"}),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"COD Origen Stock WCS - Copia.1", type text}, {"COD Origen Stock WCS - Copia.2", type text}, {"COD Origen Stock WCS - Copia.3", type text}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"COD Origen Stock WCS - Copia.1", "Cadena"}, {"COD Origen Stock WCS - Copia.2", "Stock"}, {"COD Origen Stock WCS - Copia.3", "Store_numero"}}),
    #"Columna condicional agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "Cod origen stock", each if [Store_numero] = "CSU" then [Store_numero] else if [Stock] = "EWMS " then [Stock] else if [Stock] = "PST" then [Stock] else [Stock]),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"Cod origen stock", type text}})
in
    #"Tipo cambiado1"