// Store_Capacity
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("ZVtLlkSpCtxLjXsgiIhr6dP738ZTqboS8YYkXEX+oPnvvz8t+lg///zEHD///XNgE9twf3Ac/BwtYY+uG3ZNvGhrreLD1Ass4jE2PNofHK6Ab7PX9WStVeAW0Wb5fu8/on6vOqPiYwwFeM0J6/nFv/ON8Ir3efl9eA/B9ZcBHAPXjwHrbfkhfz4anGdZJ/7qfqISSD8Xru9zgnxnM8CP0eH75P+dL1Yj+Tmez1Ce3QbYiwvaj2gA3M0R9st/zF9+tAvwK/2s/7fbDJTOutqT9rEj0yv5NcZHPu/h/7Da6lZbVJfVoipHU1hOrM1VV+tHkPEEPaViDY7RKm4OWGdWStOKc6/QXB0o63fdZ4UC5ODbq1EuhkYyBcSszSfJEeW6HCXXe11vq5D2c3AKacsW0KfRPqd2WwCbeFX7JlgQlSLi2MXq8/NSgG1pR3zHqLWuFT98yAD8WLPgdxSbiI9Z8dt0RBH264U79v3SX9N6B+T93ev3W2DNy/c76vpCfhzPF4YC7cD/Pg+er62YcJ45DPlvuJ9f43vnma1mhXN+NJBoYADaOhrUGBhVZ69Ra+tbnPAUhScYtM2O++uN4tsw/8JkHuj7YVNcEy0/+ESKDZ8zrz+eul8XfwQWNwJIe2teqayXuy5X68X2iWauaUUvN9xccHLsJ7bKwuaxYXJeN/l62dBBrZk8P/yOeFrg47cGwXotDL8RmKz9wlEiJNLrioI/9BPMoC+OsAHr2U3GJQ65EX3ldwtwIH8jgH4LFM3OFpiJd4pbdsNMTf6cjKE42GaPsBrSZ/IscVMV4YBiJzq5UVcqzhrKu0sD+WbcfvSrBeAHFB87znYsfhbqZ8uP5HUN2F4YsVnhXVwY4m/YfHgfKN85q5tve+kAb1fD4nCQPluHsLVrRyg2ded8xAvKwwT10yYWW0PJXiGP7u9HDev7+6hhapdGBsVYtBZw3qaofxkYlvP7B4sifscggJ2Kq64oLxXM853CcvrneMUdyV9EYb/eSD6C8HCQr2fae/Lb1SueZ6B9GxW/6V/1fHieJgPk2SktdKHztEnrk38ppqGO59n8YbNgZN/uWGw7pq0No32I4fdKxfiitCio71N3kL2jPvT6TxT7rfDJD4Lx3bG4F26ubvNYyvN2BVgKNxMq4Ntdovxg1wbfHtkgPlgxB6l7xwW6oVKVkozrZBYoapgTAZmF3LTR5a/60RTTY/nm/Se2ft2ySGHePPPibFO0gxYspaw1yg+BLFk30myQVDpVyOw6N9U9npth6ujXlWqqr0eQlqmnbrhQT31CSSuZCwrHt/sqQuvo68uxdhCFkrJn419izRX6x+Curag26Xjg3tAKtGGuyxK2WIk2EggKTIR8u1ejOHaLAm1XoG99EVa5UxMkHc0sqLpojla22gAJ5iig2gxFwyvxIqFJ0T2wWgsV5pjSM81estx4C2gwgxT+Q1CEAxr6nl0IeMmAD9YigsEFjWNTbyOA426odL+N8zMyLmCzbysnnpzwKAErBlzjBHNj17df94kqazS9G95JA0EqJaPEBOCqWODnyKQaOUeNhfhGDQJp1Lng7xgEWkN5dNq/6SJ5cWxX7ijQpqejQtvkCrkKdFekk02ME1rHnmKLAL20OcYppTiXrXq1WeRY6QRKXqodTzyM4oxSTdMxSiipqCnFoQy8ZUMqCpt3tAFDG2hCTaWhwNoin1kYWJvhgYV8UsnnZFDRt9CnxqSiuGOUMUH+daFAHYskzzBbzkv0SomicRNNiVCFEkuQwqCJ3B7XsCBy7RREJjmZQ9V24iiVVDLQzUaQGxqLzEgk1IdMwrMKrYa5M9egurWBVyqtFwtzvYWDT+xcTiY5UUWbwZ8yeDmNL/0ws0L7RjOyrtsXCk2/iTe8MaTYXOIau11X2jY181GcCQxRdPqk48zorEGshzkITzCnqCyM4a4AW4bMBweWz5az0QrXpvXYJzR52zhgtqoLmuid4xSbQsVZ7JYaNt0elV40/aPgFw7FesfZ66TZLu+/K02gt4mVtTG+CdG3yn+bNLQYqdLXXtg1nDp8pQOgAHeZhldwOWwuDGgArNQlBg7PIw2mDKc7DpuNhss2kH4aCNRjwBRjx+s7BfkbbvcB+HNFiAq0gcNt8YH0Hc473AjG/Xd8pMsAqMRFY8HwW/O24+0/DfnLQfHjZyw00GigT/WFBtDxMmEXPYPOj1MgE3AYmWzgNFXxPoH/7H8LvuF6Hgb8LsfzZNH8HBwd+uChSG4rY+d3BfjbN8Rnbx1gzynHw697nkJ/A9SjT4f+gzf/174+WHOKW/GL9of1LW+r3voziN4d1m/XPx694veRU8IPltRnkceo8pFzYNwP6E+2RfkZFWB+5WufvrMzf1NYU7pynpX+yB+mth53alqmvA2mwNt+6tT3XEnjVLkHZu+luJ4t4H9nUlw/BPFLOvGjAI+O5183gT18XhY9/uZNGP1dLgVMsXdTh/INoh+YIGO0RudxkGcfyE/2GEXeHRKw5+Vk6esn8peXgR+8xWmoT0d5TtLfVJRnXma+72cWoOWWqRF/WGCM5ahflo9gtUfVX0weG+AtyPaXRucj+SH+lJP1+7Zw6rrjExTYImiP8jv+ewXRhIZjV5tG8ER4cgEF/Gx9DYJhfc8p9YMzHxXYEJ4xCQ6UX1OCCS+CsJK+jfWB8CL6vIwvMJ53p0OCB8EO/E2d3BCh/Zigf5uRPRn6swXhg/E0ZOGhizGM/AynJ0gT+Ruorx1PCRb83pXjPa7nNJRxp/XoPM5PoBbCE/09JuWb6UTvuP8k+fKTqxlOMPIbguuRPe78TfEZ/WPDg2DcLwatT+ch/41seOqTKorPzQjG9ZdzPGcY4qk0iJcHDoIXwiCfcyvuBCM92seZeeH3qyE+J1S1oRwI4wxNlfK/dYQHxJudryHfnnoB+N3lpyPM+oMG79DTkLArzTt0wiR7s2h8u4FrnBHE4DUW/bAWftICKXahSde3ArAtpUK9Y6OVhVJlamCnN/FZ0o5EUMl73o9XFh0W8HxXVd9N0am748Os/5c1JJczFcHmcAaecUw8Yxe6ZFgDdtTmyGLH7LY5pGyA3qFOSvh9YPo9depB3RdmH08lPQbHVD4RhWMqJ82Q3q47PwbslrMFpkceRjpyfMEb2e4WJeerijIwzGcp1XQDzaCjTJyvOYQioEGG2h0+ZuhtVof+DcLyTeQ3sjpDbhIh6GBbaT4yTVAiR+R//dvMm77HvAMYDcG8OP2KpXzC9HrVu/NXWv4Ox18pVHfetoBgau6T2u+F3l8dk6+H5JNaxoevrWvZtrYPvYRgRXI4SIhaRUv/3fyb8ebM0x4cQD9wdxkDYYfdZVWp7g6/PlZVcUAqyGHL1BB2eMV7s+Uo9x/Ap4I6d5zWoq/oBkLoowPoChtbawQvUFA+Fyrwb7B7MNFPol/Azci50mfkgdzkbehH7ajPHGq9tfMx4psZ/GajD503o2/k19EasuZ+1rBW1ckuKTKZ2d/Mx6ulb3C958hnIFfluJPM9UD5Cogcz394bbPo8NQPAmgxRdhhuR3fRv08X198oOeboL+XtPl/gIcFFckuBID1DUslz+H6Udl//wM=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"COD STORE" = _t, Capacity = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"COD STORE", type text}, {"Capacity", Int64.Type}}),
    #"Removed Duplicates" = Table.Distinct(#"Changed Type")
in
    #"Removed Duplicates"