// Budget_EUR_FY2020
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [Market = _t, Currency = _t, #"Febrero 2020" = _t, #"Marzo 2020" = _t, #"Abril 2020" = _t, #"Mayo 2020" = _t, #"Junio 2020" = _t, #"Julio 2020" = _t, #"Agosto 2020" = _t, #"Septiembre 2020" = _t, #"Octubre 2020" = _t, #"Noviembre 2020" = _t, #"Diciembre 2020" = _t, #"Enero 2021" = _t]),
    #"Valor reemplazado" = Table.ReplaceValue(Source,".",";",Replacer.ReplaceText,{"Febrero 2020", "Marzo 2020", "Abril 2020", "Mayo 2020", "Junio 2020", "Julio 2020", "Agosto 2020", "Septiembre 2020", "Octubre 2020", "Noviembre 2020", "Diciembre 2020", "Enero 2021"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado",",",".",Replacer.ReplaceText,{"Febrero 2020", "Marzo 2020", "Abril 2020", "Mayo 2020", "Junio 2020", "Julio 2020", "Agosto 2020", "Septiembre 2020", "Octubre 2020", "Noviembre 2020", "Diciembre 2020", "Enero 2021"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1",";",",",Replacer.ReplaceText,{"Febrero 2020", "Marzo 2020", "Abril 2020", "Mayo 2020", "Junio 2020", "Julio 2020", "Agosto 2020", "Septiembre 2020", "Octubre 2020", "Noviembre 2020", "Diciembre 2020", "Enero 2021"}),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Valor reemplazado2",{{"Febrero 2020", Currency.Type}, {"Marzo 2020", Currency.Type}, {"Abril 2020", Currency.Type}, {"Mayo 2020", Currency.Type}, {"Junio 2020", Currency.Type}, {"Julio 2020", Currency.Type}, {"Agosto 2020", Currency.Type}, {"Septiembre 2020", Currency.Type}, {"Octubre 2020", Currency.Type}, {"Noviembre 2020", Currency.Type}, {"Diciembre 2020", Currency.Type}, {"Enero 2021", Currency.Type}}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Tipo cambiado", {"Market", "Currency"}, "Attribute", "Value"),    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Columns", "Attribute", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Attribute.1", "Attribute.2"}),
    #"Renamed Columns" = Table.RenameColumns(#"Split Column by Delimiter",{{"Attribute.1", "Fiscal Month"}, {"Attribute.2", "Fiscal Year"}, {"Value", "Budget"}}),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Fiscal Year", Int64.Type}}),
    #"Added Conditional Column" = Table.AddColumn(#"Tipo cambiado1", "Fiscal Quarter", each if [Fiscal Month] = "Febrero" then "Q1" else if [Fiscal Month] = "Marzo" then "Q1" else if [Fiscal Month] = "Abril" then "Q1" else if [Fiscal Month] = "Mayo" then "Q2" else if [Fiscal Month] = "Junio" then "Q2" else if [Fiscal Month] = "Julio" then "Q2" else if [Fiscal Month] = "Agosto" then "Q3" else if [Fiscal Month] = "Septiembre" then "Q3" else if [Fiscal Month] = "Octubre" then "Q3" else if [Fiscal Month] = "Noviembre" then "Q4" else if [Fiscal Month] = "Diciembre" then "Q4" else if [Fiscal Month] = "Enero" then "Q4" else null, type text),
    #"Added Conditional Column1" = Table.AddColumn(#"Added Conditional Column", "Month Number", each if [Fiscal Month] = "Febrero" then 2 else if [Fiscal Month] = "Marzo" then 3 else if [Fiscal Month] = "Abril" then 4 else if [Fiscal Month] = "Mayo" then 5 else if [Fiscal Month] = "Junio" then 6 else if [Fiscal Month] = "Julio" then 7 else if [Fiscal Month] = "Agosto" then 8 else if [Fiscal Month] = "Septiembre" then 9 else if [Fiscal Month] = "Octubre" then 10 else if [Fiscal Month] = "Noviembre" then 11 else if [Fiscal Month] = "Diciembre" then 12 else if [Fiscal Month] = "Enero" then 1 else null, Int64.Type),
    #"Added Column" = Table.AddColumn(#"Added Conditional Column1", "Year Month Number", each [Fiscal Year] * 12 + [Month Number] - 1),
    #"Reordered Columns" = Table.ReorderColumns(#"Added Column",{"Year Month Number", "Fiscal Year", "Fiscal Quarter", "Fiscal Month", "Month Number", "Market", "Currency", "Budget"}),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Reordered Columns",{{"Year Month Number", Int64.Type}})
in
    #"Tipo cambiado2"