// Store_Status_China
let
    Origen = Oracle.Database("PTR", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - PTR - FOTO STOCK - ESTADO DE LAS TIENDAS - BERSHKA - CHINA#(lf)SELECT #(lf)    ee.DESCRIPCION AS MERCADO_ECOMM,#(lf)    tos.DESCRIPCION AS TIPO_ORIGEN_STOCK,#(lf)    p.DESCRIPCION AS PAIS,#(lf)    os.ID_LOC, #(lf)    os.COD_ORI_STK_WCS,#(lf)    os.NOMBRE AS DESCRIPCION_TIENDA,#(lf)    tgdos.DESCRIPCION AS RELACION,#(lf)    CASE #(lf)        WHEN os.ID_EST_ORI_STK = 2 THEN 'Contingencia'#(lf)        WHEN os.ID_EST_ORI_STK = 3 THEN 'CSU'#(lf)        WHEN gdos.HABILITADO = 0 THEN 'Desactivada'#(lf)        WHEN gdos.HABILITADO = 1 THEN 'Activa' #(lf)        WHEN gdos.HABILITADO = 2 THEN 'Pausada total' #(lf)        WHEN gdos.HABILITADO = 3 THEN 'Desactivada' #(lf)        WHEN gdos.HABILITADO = 4 THEN 'Pausada parcial' #(lf)        WHEN gdos.HABILITADO IS NULL THEN 'Desactivada' #(lf)        ELSE 'Desactivada' #(lf)    END AS ESTADO#(lf)FROM FND_INDOM_ITX_CN.ENTIDAD_ECOMMERCE ee#(lf)INNER JOIN FND_INDOM_ITX_CN.GRP_DISTRIBUCION_ORI_STOCK gdos #(lf)  ON ee.ID_GRUPO_DISTRIBUCION = gdos.ID_GRUPO_DISTRIBUCION #(lf)        AND ee.ID_CADENA = 4 -- BERSHKA#(lf)INNER JOIN FND_INDOM_ITX_CN.ORIGEN_STOCK os #(lf)  ON os.ID_ORI_STK = gdos.ID_ORIGEN_STOCK#(lf)    AND os.ID_T_ORI_STK = 3#(lf)INNER JOIN FND_INDOM_ITX_CN.ORIGEN_STOCK osf #(lf)  ON osf.ID_ORI_STK = os.ID_ORI_STK_FISICO#(lf)    AND osf.ID_T_ORI_STK = 6#(lf)INNER JOIN FND_INDOM_ITX_CN.T_GRP_DIST_ORI_STK tgdos#(lf)    ON gdos.ID_T_GRP_DISTRIBUCION_ORI_STK = tgdos.ID_T_GRP_DIST_ORI_STK#(lf)INNER JOIN FND_INDOM_ITX_CN.TIPO_ORIGEN_STOCK tos #(lf)    ON os.ID_T_ORI_STK = tos.ID_T_ORI_STK#(lf)INNER JOIN FND_MAESTROS.PAIS p #(lf)    ON os.ID_PAIS = p.ID_PAIS#(lf)WHERE GDOS.HABILITADO IN (0, 1, 2, 3, 4) #(lf)  AND os.ID_EST_ORI_STK > 0#(lf)  AND ee.DESCRIPCION NOT LIKE '%TEST%'#(lf)UNION ALL#(lf)SELECT #(lf)    ee.DESCRIPCION AS MERCADO_ECOMM,#(lf)    tos.DESCRIPCION AS TIPO_ORIGEN_STOCK,#(lf)    p.DESCRIPCION AS PAIS,#(lf)    os.ID_LOC,#(lf)    os.COD_ORI_STK_WCS,#(lf)    os.NOMBRE AS DESCRIPCION_TIENDA,#(lf)    tgdos.DESCRIPCION AS RELACION,#(lf)    CASE #(lf)        WHEN os.ID_EST_ORI_STK = 2 THEN 'Contingencia'#(lf)        WHEN os.ID_EST_ORI_STK = 3 THEN 'CSU'#(lf)        WHEN gdos.HABILITADO = 0 THEN 'Desactivada'#(lf)        WHEN gdos.HABILITADO = 1 THEN 'Activa' #(lf)        WHEN gdos.HABILITADO = 2 THEN 'Pausada total' #(lf)        WHEN gdos.HABILITADO = 3 THEN 'Desactivada' #(lf)        WHEN gdos.HABILITADO = 4 THEN 'Pausada parcial' #(lf)        WHEN gdos.HABILITADO IS NULL THEN 'Desactivada' #(lf)        ELSE 'Desactivada' #(lf)   END AS ESTADO#(lf)FROM FND_INDOM_ITX_CN.ENTIDAD_ECOMMERCE ee#(lf)INNER JOIN FND_INDOM_ITX_CN.GRP_DISTRIBUCION_ORI_STOCK gdos #(lf)    ON ee.ID_GRUPO_DISTRIBUcION = gdos.ID_GRUPO_DISTRIBUCION #(lf)        AND ee.ID_CADENA = 4 -- BERSHKA#(lf)INNER JOIN FND_INDOM_ITX_CN.ORIGEN_STOCK os #(lf)  ON os.ID_ORI_STK = gdos.ID_ORIGEN_STOCK#(lf)    AND os.ID_T_ORI_STK = 6#(lf)INNER JOIN FND_INDOM_ITX_CN.T_GRP_DIST_ORI_STK tgdos#(lf)    ON gdos.ID_T_GRP_DISTRIBUCION_ORI_STK = tgdos.ID_T_GRP_DIST_ORI_STK#(lf)INNER JOIN FND_INDOM_ITX_CN.TIPO_ORIGEN_STOCK tos #(lf)    ON os.ID_T_ORI_STK = tos.ID_T_ORI_STK#(lf)INNER JOIN FND_MAESTROS.PAIS p #(lf)    ON os.ID_PAIS = p.ID_PAIS#(lf)WHERE GDOS.HABILITADO IN (0, 1, 2, 3, 4) #(lf)    AND os.ID_EST_ORI_STK > 0#(lf)    AND ee.DESCRIPCION NOT LIKE '%TEST%'#(lf)GROUP BY #(lf)    ee.DESCRIPCION,#(lf)    tos.DESCRIPCION,#(lf)    p.DESCRIPCION, #(lf)    os.ID_LOC,#(lf)    os.COD_ORI_STK_WCS,#(lf)    os.NOMBRE,#(lf)#(tab)os.ID_EST_ORI_STK,#(lf)    tgdos.DESCRIPCION, #(lf)    gdos.HABILITADO#(lf)ORDER BY 1 ASC, 2 ASC", CommandTimeout=#duration(0, 4, 0, 0)]),
    #"Personalizada agregada" = Table.AddColumn(Origen, "Localización", each if Text.Contains([COD_ORI_STK_WCS],"CAJA") then [DESCRIPCION_TIENDA] else [COD_ORI_STK_WCS] & " " & Text.AfterDelimiter([DESCRIPCION_TIENDA], "Uterqüe ")),
    #"Tipo cambiado" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Localización", type text}}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"MERCADO_ECOMM", "ID_LOC", "COD_ORI_STK_WCS", "DESCRIPCION_TIENDA"}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas quitadas",{"TIPO_ORIGEN_STOCK", "PAIS", "Localización", "ESTADO", "RELACION"}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas reordenadas",{{"TIPO_ORIGEN_STOCK", "Tipo Origen Stock"}, {"PAIS", "Mercado"}, {"ESTADO", "Estado"}, {"RELACION", "Relación"}})
in
    #"Columnas con nombre cambiado"