// Pedidos_Unidades_Importe_I2020_ES
let
    Source = DB2.Database("ieecdb2v1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="-- DB2 - SEGUNDO TRAMO DE REPLICA#(lf)-- BERSHKA#(lf)-- PEDIDOS, UNIDADES E IMPORTE - I2020 - ESPAÑA#(lf)SELECT#(lf)#(tab)FROM_UTC_TIMESTAMP(TO_UTC_TIMESTAMP(o.TIMEPLACED, 'Europe/Dublin'), 'Europe/Madrid') hora_españa,#(lf)#(tab)CASE#(lf)        WHEN e.NOMBRE LIKE '%BershkaX%' THEN 'Marketplace'#(lf)        ELSE 'Web propia'#(lf)    END tipo_tienda,#(lf)    COUNT(DISTINCT(o.ORDERS_ID)) pedidos,#(lf)    SUM(oi.QUANTITY) unidades,#(lf)    SUM(oi.TOTALPRODUCT + oi.TOTALADJUSTMENT) importe#(lf)FROM UECOITX_SP2.ORDERITEMS oi  #(lf)INNER JOIN UECOITX_SP2.ORDERS o#(lf)#(tab)ON o.ORDERS_ID = oi.ORDERS_ID #(lf)#(tab)#(tab)AND o.STATUS NOT IN ('P','N','J','X')#(lf)#(tab)#(tab)#(tab)AND oi.STATUS NOT IN ('P','N','J','X') #(lf)#(tab)#(tab)#(tab)#(tab)AND o.STOREENT_ID LIKE '4%' -- BERSHKA#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND FROM_UTC_TIMESTAMP(TO_UTC_TIMESTAMP(o.TIMEPLACED, 'Europe/Dublin'), 'Europe/Madrid') >=  '2021-01-06 17:45:00.000'#(lf)INNER JOIN MAESTROS.ENTIDAD_ECOMMERCE e#(lf)#(tab)ON e.COD_ENTIDAD_ECOMMERCE_WCS = o.STOREENT_ID#(lf)#(tab)#(tab)AND e.NOMBRE IN ('BershkaES', 'BershkaESCN')#(lf)GROUP BY#(lf)#(tab)FROM_UTC_TIMESTAMP(TO_UTC_TIMESTAMP(o.TIMEPLACED, 'Europe/Dublin'), 'Europe/Madrid'),#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN e.NOMBRE LIKE '%BershkaX%' THEN 'Marketplace'#(lf)#(tab)#(tab)ELSE 'Web propia'#(lf)#(tab)END#(lf)WITH UR;", CommandTimeout=#duration(0, 2, 0, 0)]),
    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"UNIDADES", Int64.Type}, {"IMPORTE", Currency.Type}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"HORA_ESPAÑA", "Fecha Hora Pedido España"}, {"TIPO_TIENDA", "Tipo Tienda"}, {"PEDIDOS", "Pedidos"}, {"UNIDADES", "Unidades"}, {"IMPORTE", "Importe (€)"}}),
    #"Fecha insertada" = Table.AddColumn(#"Columnas con nombre cambiado", "Fecha", each DateTime.Date([Fecha Hora Pedido España]), type date),
    #"Hora insertada" = Table.AddColumn(#"Fecha insertada", "Hora", each Time.Hour([Fecha Hora Pedido España]), Int64.Type),
    #"Minuto insertado" = Table.AddColumn(#"Hora insertada", "Minuto", each Time.Minute([Fecha Hora Pedido España]), Int64.Type),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Minuto insertado",{{"Fecha", "Fecha Pedido España"}, {"Hora", "Hora Pedido España"}, {"Minuto", "Minuto Pedido España"}}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas con nombre cambiado1",{"Fecha Hora Pedido España", "Fecha Pedido España", "Hora Pedido España", "Minuto Pedido España", "Tipo Tienda", "Pedidos", "Unidades", "Importe (€)"})
in
    #"Columnas reordenadas"