// Ipod_Returns_FY2020
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - IPOD - RETURNS - BERSHKA - FY2020#(lf)SELECT #(lf)  mf.ID_FECHA,#(lf)  mf.ID_HORA,#(lf)  mf.ID_MINUTO,#(lf)  mf.FECHA_PED_DEVOL,#(lf)  mf.HORA_PED_DEVOL,#(lf)  mf.ID_PEDIDO_ECOMMERCE,#(lf)  mf.ID_DEVOLUCION_ECOMMERCE,#(lf)  mf.UNIDADES,#(lf)  mf.IMPORTE local_credit_amount,#(lf)  ROUND (mf.IMPORTE * mf.CAMBIO_REFERENCIA, 2) credit_amount_euros,#(lf)  mf.MODELO,#(lf)  mf.CALIDAD,#(lf)  mf.COLOR,#(lf)  mf.ID_CADENA,#(lf)  mf.ID_SECCION,#(lf)  depe.DESCRIPCION ecommerce_order_status,#(lf)  dtpe.COD_TIPO_PAGO ecommerce_payment_type,#(lf)  dtpi.DESCRIPCION ipod_payment_type,#(lf)  dp.DESCRIPCION market,#(lf)  dl1.DESCRIPCION physical_store,#(lf)  dp.PAIS_ISO,#(lf)  dl1.CIUDAD,#(lf)  dl1.CALLE,#(lf)  dl1.CODIGO_POSTAL,#(lf)  dl1.LONGITUD,#(lf)  dl1.LATITUD#(lf)FROM #(lf)  DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN#(lf)  DMECOMMERCE.DIM_ESTADO_PEDIDO_ECOMMERCE depe#(lf)    ON (depe.ID_ESTADO_PEDIDO_ECOMMERCE = mf.ID_ESTADO_PEDIDO_ECOMMERCE)#(lf)INNER JOIN#(lf)  DMECOMMERCE.DIM_TIPO_PAGO_ECOMMERCE dtpe#(lf)    ON (dtpe.ID_TIPO_PAGO_ECOMMERCE = mf.ID_TIPO_PAGO_ECOMM)#(lf)INNER JOIN#(lf)  DMECOMMERCE.DIM_TIPO_PAGO_IPOD dtpi#(lf)    ON (dtpi.ID_TIPO_PAGO_IPOD = mf.ID_TIPO_PAGO_IPOD)#(lf)INNER JOIN #(lf)  DMCOMERCIAL.DIM_PAIS dp#(lf)    ON (dp.ID_PAIS = mf.ID_PAIS)#(lf)INNER JOIN#(lf)  DMECOMMERCE.DIM_TIPO_DISPOSITIVO dtd#(lf)    ON (dtd.ID_TIPO_DISPOSITIVO = mf.ID_TIPO_DISPOSITIVO)#(lf)      AND dtd.ID_TIPO_DISPOSITIVO IN (23) -- IPOD TRANSACTION#(lf)INNER JOIN #(lf)  DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)    ON (dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_DISPOSITIVO)#(lf)INNER JOIN #(lf)  DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)    ON (dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION)#(lf)WHERE #(lf)  mf.ID_FECHA_PLATAFORMA >= TO_DATE ('01/01/2020', 'DD/MM/YYYY')#(lf)    AND mf.ID_FECHA_PLATAFORMA < TO_DATE ('01/03/2021', 'DD/MM/YYYY')#(lf)      AND mf.ID_FECHA >= TO_DATE ('01/02/2020', 'DD/MM/YYYY') #(lf)        AND mf.ID_FECHA < TO_DATE ('01/02/2021', 'DD/MM/YYYY')#(lf)          AND mf.ID_CADENA = 5 -- BERSHKA #(lf)            AND mf.ID_TIPO_MOVIMIENTO IN (73, 808) -- RETURN TRANSACTION#(lf)              AND mf.REPOSICION = 0 -- DRIVE#(lf)                AND mf.ID_SECCION > 0 -- DRIVE#(lf)                  AND mf.ID_PAIS > 0 -- DRIVE#(lf)                    AND dl1.LOCALIZACION > 0 -- DRIVE#(lf)ORDER BY#(lf)  mf.ID_FECHA ASC", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_FECHA", type date}, {"ID_PEDIDO_ECOMMERCE", type text}, {"ID_MINUTO", Int64.Type}, {"ID_HORA", Int64.Type}, {"UNIDADES", Int64.Type}, {"CREDIT_AMOUNT_EUROS", Currency.Type}, {"MODELO", type text}, {"CALIDAD", type text}, {"COLOR", type text}, {"LOCAL_CREDIT_AMOUNT", Currency.Type}, {"FECHA_PED_DEVOL", type date}, {"HORA_PED_DEVOL", Int64.Type}, {"ID_DEVOLUCION_ECOMMERCE", type text}, {"ID_SECCION", Int64.Type}, {"ID_CADENA", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ID_FECHA", "Date"}, {"ID_HORA", "Hour"}, {"ID_MINUTO", "Minute"}, {"ID_PEDIDO_ECOMMERCE", "Ecommerce Order ID"}, {"MODELO", "Modelo"}, {"CALIDAD", "Calidad"}, {"COLOR", "Color"}, {"UNIDADES", "Units"}, {"CREDIT_AMOUNT_EUROS", "Credit Amount (€)"}, {"MARKET", "Market"}, {"PHYSICAL_STORE", "Physical Store"}, {"PAIS_ISO", "Country ISO"}, {"CIUDAD", "City"}, {"CALLE", "Street"}, {"CODIGO_POSTAL", "Postal Code"}, {"LONGITUD", "Longitude"}, {"LATITUD", "Latitude"}, {"LOCAL_CREDIT_AMOUNT", "Local Credit Amount"}, {"FECHA_PED_DEVOL", "Return Order Date"}, {"HORA_PED_DEVOL", "Return Order Hour"}, {"ID_DEVOLUCION_ECOMMERCE", "Ecommerce Return ID"}, {"ECOMMERCE_ORDER_STATUS", "Ecommerce Order Status"}, {"IPOD_PAYMENT_TYPE", "Ipod Payment Type"}, {"ECOMMERCE_PAYMENT_TYPE", "Ecommerce Payment Type"}, {"ID_SECCION", "Section ID"}, {"ID_CADENA", "Chain ID"}})
in
    #"Renamed Columns"