// Consumibles Zara Home
let
    Source = DB2.Database("axindb2tndg6v1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="SELECT ID_PAIS, #(lf)       PAIS, #(lf)       CODIGO_TIENDA, #(lf)       TIENDA, #(lf)       CAST (FECHA_ALTA  AS DATE) as FECHA_ALTA , #(lf)       --FECHA_HASTA, #(lf)       DESCRIPCION, #(lf)       SUM(CAJAS) AS N_CAJAS #(lf)FROM   (SELECT * #(lf)        FROM   (SELECT G.ID_PAIS,PA.DESCRIPCION    AS PAIS, #(lf)                       S.ID_LOCALIZACION AS CODIGO_TIENDA, #(lf)                       L.DESCRIPCION     AS TIENDA, #(lf)                       CAST (P.FECHA_ALTA AS DATE) as FECHA_ALTA, #(lf)                       --MAX(date(P.FECHA_ALTA)) AS FECHA_HASTA, #(lf)                       CP.ID_TIPO_CAJA_ECOMMERCE, #(lf)                       COUNT(*)          AS CAJAS #(lf)                FROM   ECLOG_CADENAS_TND.PEDIDO P #(lf)                       JOIN ECLOG_CADENAS_TND.SUBPEDIDO S #(lf)                         ON P.ID_PEDIDO = S.ID_PEDIDO #(lf)                       JOIN ECLOG_CADENAS_TND.GRUPO_DISTRIBUCION G #(lf)                         ON P.ID_GRUPO_DISTRIBUCION = G.ID_GRUPO_DISTRIBUCION #(lf)                       JOIN MAESTROS.PAIS PA #(lf)                         ON G.ID_PAIS = PA.ID_PAIS #(lf)                       JOIN MAESTROS.LOCALIZACION L #(lf)                         ON S.ID_LOCALIZACION = L.ID_LOCALIZACION #(lf)                       JOIN ECLOG_CADENAS_TND.CAJA_PEDIDO CP #(lf)                         ON P.ID_PEDIDO = CP.ID_PEDIDO #(lf)                WHERE  G.ID_CADENA = 14 --zara home#(lf)                       --AND S.ID_LOCALIZACION IN (5582) #(lf)                       --AND S.ID_LOCALIZACION IN ( :IdGrupoDistribucion ) -- 3149#(lf)                       AND                       P.FECHA_ALTA BETWEEN '2020-02-01' AND '2022-02-01'  --BETWEEN :Fecha_Desde AND :FechaHasta  -- #(lf)#(tab)#(tab)#(tab)#(tab)group by  G.ID_PAIS,PA.DESCRIPCION ,S.ID_LOCALIZACION,L.DESCRIPCION,P.FECHA_ALTA,CP.ID_TIPO_CAJA_ECOMMERCE)#(lf)                A #(lf)               INNER JOIN ECLOG_CADENAS_TND.TIPO_CAJA_ECOMMERCE E #(lf)                       ON E.ID_TIPO_CAJA_ECOMMERCE = A.ID_TIPO_CAJA_ECOMMERCE) #(lf)          GROUP  BY ID_PAIS, #(lf)          PAIS, #(lf)          CODIGO_TIENDA, #(lf)          TIENDA,  #(lf)          FECHA_ALTA,#(lf)          DESCRIPCION#(lf) WITH UR #(tab) ", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_PAIS", type text}, {"CODIGO_TIENDA", type text}, {"FECHA_ALTA", type date}}),
    #"Added Custom Store Location" = Table.AddColumn(#"Changed Type", "Store Location", each Text.PadStart([CODIGO_TIENDA], 5, "0"), type text),
    #"Added Custom Store Description" = Table.AddColumn(#"Added Custom Store Location", "Store Description", each [Store Location] & " - " & [TIENDA], type text),
    #"Added Custom ID Country-Store" = Table.AddColumn(#"Added Custom Store Description", "ID Country-Store", each Text.Combine({Text.From([ID_PAIS], "es-ES"), "-", [Store Location]}), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom ID Country-Store",{"CODIGO_TIENDA"}),
    #"Merged Queries Countries" = Table.NestedJoin(#"Removed Columns", {"ID_PAIS"}, Countries, {"Country"}, "Countries", JoinKind.LeftOuter),
    #"Expanded Countries" = Table.ExpandTableColumn(#"Merged Queries Countries", "Countries", {"English Description"}, {"Market English"}),
    Replace = Table.ReplaceValue(#"Expanded Countries","Boîte","Box",Replacer.ReplaceText,{"DESCRIPCION"}),
    Replace1 = Table.ReplaceValue(Replace,"Caja","Box",Replacer.ReplaceText,{"DESCRIPCION"}),
    Replace2 = Table.ReplaceValue(Replace1,"CAJA","Box",Replacer.ReplaceText,{"DESCRIPCION"}),
    Replace3 = Table.ReplaceValue(Replace2,"BOX","Box",Replacer.ReplaceText,{"DESCRIPCION"}),
    Replace4 = Table.ReplaceValue(Replace3,"Sobre","Envelope",Replacer.ReplaceText,{"DESCRIPCION"}),
    Replace5 = Table.ReplaceValue(Replace4,"BAG","Bag",Replacer.ReplaceText,{"DESCRIPCION"}),
    #"Renamed Columns" = Table.RenameColumns(Replace5,{{"ID_PAIS", "ID Contry"}, {"PAIS", "Market Descripcion"}, {"TIENDA", "Store Name"}, {"FECHA_ALTA", "Date"}, {"DESCRIPCION", "Descripcion Consumible"}, {"N_CAJAS", "Num Consumibles"}, {"Store Location", "Store Code"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Date", "ID Contry", "Market English", "Market Descripcion", "ID Country-Store", "Store Code", "Store Name", "Store Description", "Descripcion Consumible", "Num Consumibles"}),
    #"Valor reemplazado" = Table.ReplaceValue(#"Reordered Columns","BIG","Big",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado","Box mediana + tapa","Medium box + cover",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado2" = Table.ReplaceValue(#"Valor reemplazado1","Box unitaria + tapa","Unitary box + cover",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado3" = Table.ReplaceValue(#"Valor reemplazado2","Box grande","Big box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado4" = Table.ReplaceValue(#"Valor reemplazado3","Box gigante","Giant box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado5" = Table.ReplaceValue(#"Valor reemplazado4","Box pequeña + tapa","Small box + cover",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado6" = Table.ReplaceValue(#"Valor reemplazado5","MEDIUM","Medium",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado7" = Table.ReplaceValue(#"Valor reemplazado6","SMALL","Small",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado8" = Table.ReplaceValue(#"Valor reemplazado7","BOLSA MEDIANA/Medium Bag","Medium Bag",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado9" = Table.ReplaceValue(#"Valor reemplazado8","BOLSA PEQUEÑA/Small Bag","Small Bag",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado10" = Table.ReplaceValue(#"Valor reemplazado9","BOLSA GRANDE/Big Bag","Big Bag",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado11" = Table.ReplaceValue(#"Valor reemplazado10","GIANT","Giant",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado12" = Table.ReplaceValue(#"Valor reemplazado11","box","Box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado13" = Table.ReplaceValue(#"Valor reemplazado12","Box MEDIANA/Medium Box","Medium Box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado14" = Table.ReplaceValue(#"Valor reemplazado13","Box CREMALLERA GRANDE/Big ZIPPER Box","Big Zipper Box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado15" = Table.ReplaceValue(#"Valor reemplazado14","ZIPPER","Zipper",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado16" = Table.ReplaceValue(#"Valor reemplazado15","Box GIGANTE/Giant Box","Giant Box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado17" = Table.ReplaceValue(#"Valor reemplazado16","Box PEQUEÑA/Small Box","Small Box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado18" = Table.ReplaceValue(#"Valor reemplazado17","Rollo alfombra","Carpet roll",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado19" = Table.ReplaceValue(#"Valor reemplazado18","Carpet rol","Carpet roll",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado20" = Table.ReplaceValue(#"Valor reemplazado19","BOLSA ALFOMBRA GRANDE/Big Bag RUG","Big Bag RUG",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado21" = Table.ReplaceValue(#"Valor reemplazado20","RUG","Rug",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado22" = Table.ReplaceValue(#"Valor reemplazado21","Carpet rolll","Carpet roll",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado23" = Table.ReplaceValue(#"Valor reemplazado22","Big Bag Rug","Big Rug Bag",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado24" = Table.ReplaceValue(#"Valor reemplazado23","Envelope online","Online Envelope",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado25" = Table.ReplaceValue(#"Valor reemplazado24","High CHAIR Box","High Chair Box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado26" = Table.ReplaceValue(#"Valor reemplazado25","MINI COT MATTRESS Box","Mini Cot Mattress Box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado27" = Table.ReplaceValue(#"Valor reemplazado26","HIGH CHAIR Box","High Chair Box",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado28" = Table.ReplaceValue(#"Valor reemplazado27","Online envelope","Online Envelope",Replacer.ReplaceText,{"Descripcion Consumible"}),
    #"Valor reemplazado29" = Table.ReplaceValue(#"Valor reemplazado28","COT MATTRESS Box","Cot Mattress Box",Replacer.ReplaceText,{"Descripcion Consumible"})
in
    #"Valor reemplazado29"