// AMT
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jV3Ljh1Hcv2VBtezyIiMfC1pWRZsSLLBAQbwCLO4I97RNNzshpukgeHf+AO0GPgT+GOOrKhLDbviRNbmLu6pzMrKZ8SJR/700yvikfjV7159c3l+erh/vNz9cH24Pr69fnr1p9/99CoxVVH0h+vzz9e31/d3/3F9vn66++bp3fX95fPfL7eHSjrxUD3xkD525qGsD/3T8+X+/d13l+ef7w2g1DYAfUqiCKUhGBXOE319/+Hp+e77+0+X59v/Nbv/Z2rO/8SF2X2+SfL+T0Jbf1ye/3b3/dPH+/dXbdjbny8Pf9nLUS4hztJjnFKIZ+H4/T18f5Le4vrbfP+/frq8/6+PjzqYnz7Mcf5lH2kRHhHMJSzNEpVmpr6ca41qW0/ILHn9EKeCJ1iqo3hzOrWeKZi1nBtGG/UA5VwqRIlrmugP9798vD7cvX78RX/fXP+mX6eD+eH+8VZL2df++rl8qr7UtkFbPUdUx7n29X7uuWYzdfkc074i7p/ufv/x8//Oob41PXcAFRunb99/uP7l8vj518tW6+dfHw3uqe0D9e76ePfj5X8uz89PN2jbGd5c/nu268ePn/9+a0mnbYQ8hAcBZLQMEC01d6CHdx/fXnU2fPf5/959mQtCAbaNv4el3rhDLMm+HB6edMbfP/z5+vzhBhUMSUZQ3rY6tw+5ZwTRgKWoEYKkAkjXTf3qlHlZZcNg5QDk0oNqawAmqQiklLf9HzWIBEyWsvX1ESFugqZe2hbsm6f32/r47l677unuX67Pz9fnW6+OtHiCt+Pz23fvLndv7nXsL7dOL+T8Pyd18f/fzpXj/7pb6P/fXSfww9Pzb0AeAwCbwOIAupH5AFmvBl+ZqfhFZTvtww5Kq05O2/4aPVEb6ATu69f7H13H1k1/+Pzrz1PC+ePlz7r9Xb90YYcYb/KBj9VNnvMxlfYgJgW9T6WpwgjjskmIyxNCt5R86rkkhPayftvLnB2Q0Q5YR0IVVs5gS9WDdDuaglFVyX0r/Hz//sPcJFQ8eVBB9e6GbmP+WgEt9Hj5R4GbIdIn8vunx3udJ7pJPN1OVzsI0TlZ8nZoQJhaCJc+p/43948f7vUjHh4uz2+fbu/dTlkXqlspWGlKAaz74bYg3YpHgVAOxYXCKQXwPECn3Pvh8tf791Oue6ujdpNyMiOodADpKZFhhbbN+VAGEFHfdEG3FCXUQm6EBolrj3qk2PbtlCTmNqHvLx+f9Sx4evs8l+1vsiMU6GjbfFyotgrFwJTD+VuHX1K19JxRt1AFkApnHQ2c6uxodHTZEiqVGoJq2QRtb7WbjHVEdHUMf4eY6+aE3lW3rcffmEiFvh6of83aC7XDUhnDlBuHpZttxWDLbNuegdCySdtHVZDLdnQ7OqJUUMLkHFcAVwwK54oViFFGYjGbuOWKxZKBsiIlr9VwsYWzemjw+qG8DdziITnzusxrakxkrGtSQWA92cXEiuMgSynNB14I9y8YB5GAHJDc/SklJsYj1qBwWCkHFIi2J2LgCHxlErBcxLYxB6BNADwCZSlfF1tpRwG35AQA3jZuD5CFqF5MJQ+b0xbC/FS7Fk+0svpoptUT1P2vVw0SHbwqx9IZMbnyKSJq6oBniCNtUgaHrEIJnffVKJUDQVvJNgFAcOpXpoiDrKYMumd33kQ15zytVCs+PrRKjM72BCibfO0KQ6pezIn8n08P2hRFr788XG8bf7UzwcXK2GQ9VI7/EdP+uzz+/Nff2M2N1zh0eqPusuWtJ5elZ+ZIgZGNVHA/mmWT5dzGt9HQR0/BKwUfVvN25iGYbEcPFhzVtKBKqGwDfaA4qFSXKqG+De+RWmkbG+DUs/GlxyWvcuWC3yATrVzlnOomQvhY2cRjHzMrFsAIkQ86UO2Usq51lDO7UKrt1C5EBarxupdWH9LaK4K4ElD+9VBOp75R8kmKXvIZqlzVxnRqh59WpFM7fOEzz2nz0hmiRuvLp0wXKqFG2rica9ZsfgX7jCrEUNPUzo74B2FqoOTsCFQpMdJRhbemuEdSYaTsa6mBSyElVAS9awrzgCJQlX0jTkApAodmHkA9FZumPlKAeprPcYG6Ks9sG6oRFiSUtFqi2aejdWaRaadtDJd/yjVIZqiKDSDKBUGqI26fDbXj1ELlOVFk1lXlFGi7tNDJBR4tPDI8PrgH5UqDHDRXxuX6Nht9jCua3mw7pUvaGMnilWpdENumkhEuNeCKNlrBrTA3sGTmpPCXmYpziDlijGxSpYc0QmWaoA14DjLcnBm3b2xyr1+jnfBHjluHt0GZUoZve9HPdTUs3Yk2+6tTom8CoFdVXqiEuhvlxRMlr57odWVnSsWV7jtn//9UPN8ZomFT7vD8qJ4PjtZDrpagM2DJwuhhJmvSp5OsXZ26qRarmk4QUZ36mkHrpqItHkopoG+6yRPYg6W623LXEcLFKkc+Wz1LULaXup9AvvKt22WM5xZ6N3WjSCM8OuZ0AQYUcup9s4lCmHPAHKiS3/xTUKc3AOxQ9kpsPn4uELYwjfDzs0THeOeNf8QwuTp+zyPQ5TtBGVtnS/HNENNsjRBTiTykmMUQtaMH/H83MtxvpZ3+4CDarKNea2qGHEbPDR5S3fzzfIw227s7LXwmupuz3PHI024kH0jbseYA3N2qtA8yKoGP1W4LHfAttAuOiI7pOWSp+ti0BAQXE+3BVChtEyARSlHZFJfN0QRNthj8aWYWGcc6n0+YakpqaytMSaGCkFqK4GL+ThBuIcc5sr8Nsrlguu4TRMjmVYmBzUv34U1RcWxeWsgj2+Z7fPGvmpbvt60jrw/efRNevobNznwUJmmsaEVOw/d3YkJA2prusm/UC3TT4bH5dIUiZvf9pFR+BVJ0L76dggtwXGI7ZqNWmLk/fmIhCrcCjEScefV66Qu6ldl1giNu7iTUSdDdWdNMffIaiYY+s+81x5xQieXXmNXVKSq8mi+2iKJxsB01rCOt6uhIIcu8Wly5+hO6dfDRjSBdTtn8CNzF1VrHvEXukGZXtRtzGibVgPc1iImZs+BZICmSE6VxGAOQN33NP+dM2/GIv0AsSjbPjtEnqvD77hmSN0nelUz06wrCJHeITXcAjG2OV36dJaozMSzHOTJoSU0jgs1hDZfmSILiLqfsCNwpYkobE+K8uULDLzfIlHPZNkTIzLYcEfdcccVDIjcxKubO7vjBqbzYIWQihAttUxr6MLKFRrkl8yl+m8yxOviiQM4lY8C9nqKacdM46n6yOYdblOA7zccFl8xoXKmUAqBq0UF+KejERxYy4PLBdSBPPZ0J2d/3dPqAHVGR4SM1ozKlV+DBMG3nkebSQzRw2MyY4S3mmw4Ua+CHqKoGQ+W5yCa1uTVOP1ZUTmfIWkOimtZ8HRU5UVM5EcKp41vWD40TbKROPJ9NIpNHAJenDQjIRd0COkR1rveAQySzz0K0+epgso91fSCLER0+ZvS1p4/pxoHUyCL9K6Lza7DgEJ4J4uCfwreQAA+sgxE4fb4Flpzc3is//kfSerJVysGIVPq6zS9RX/yabrNwTFotAsZEIaS/swWDuFC/zSkHgnFo3G7uG0eoCh5/7tt26RAJZMq/+9FkVjqXmUi3/nAgQXOULBbcb6OWg5NJwa8X6ItqCYSMUQLTTMsMhDD5qrRW5quv+lk+KUBGf3tAW3lfpY2hip6gVRwWGdUSv8XXF7VyGG5FlBAfM/sIe1GlDsO0tKmC35ehqkkW7OGKb/su4EEJRXPMkQmlugQjgCb3BSst53zEjG5bP0cMZUuz0sH2k+CAhzmRA7mJLPAPluXAp1SbFb3X/IMhiiXb1JAHCaWbac7pIxhfQxYA5o9vg0pTSrBUKsiFaop44VBxqMMZ6YHh5robk0X0O/+fCH0gCxhfPnRCWjQP+mVNgbc/pRGhLwKlX6I1kBC0cWFOCvriAA7w1PzwAB3SiGoii1Fxxgb+71o4tX2I66fdm9xT6lJkKqKEbYBkMqKPmTM5wBq0OepG1aPWZOAKRMZnuoggJFH45SX4ggBLGStwCYTiUAI+P2QWKwdIyY+E1aMKmjNlcMi2ISciMWLwCCSLd3JKmH9YIINonb70JOYsGhXlFWOfZOWqlGThiDQlZMwJ0Ndu+l/HLUjUyaX2yChcTX2HpS002pOyUxcEFeN0gEp687I57BrJkgu5LzPvfjdir37tC/RC6czAtKmjDlVDBnI+w7ZPqQxaNwnpN1NUxW3nPXrEC1SFO+F0AgQEGNse6Tj6WTgRpLXtnIHnEKebmAhCi0YYWtQ63vJb74E8x1Igw8Y8YIQQZ+x8w7lBiwpLx16UOYHONbOQu3SHeRbCjq+ytOmyG/TCxm0d/2/mo33431zfnf/7ws7YRl9ZMyuyGVskiGf9FmxtbzgmR+dDJKu2bnTm0jyz+8x7Bo+MXcmFoWnG4n2hgSXDmAr9WiBMcOvAFYwrCiBgY7P9+Wu2C2f+tuK7RHETV4YgthCLY4lmFKa7FNho1WAPivImsFEjbsYFrLqzCf7QnCSoUrpZepZTaVd3ls+ZkrEOjjCCzQ9lKMiipnIzgoQgq6hST0WHuLCgRFuzHOSjp6kYHf5y444PkNhB6EJf6Ein/QPzzSpIgjM+WSo/X2KIjUFAVyjmIOuZlyzbEKxxYMc4yhV5fOpe7q8/bYjvklgskMUD8kKsLuSGadJuqT6cKPoqN9yzGNXu7uuFsKNHsehsHzPJHpQb8BwpRkj7WK6IJVQxr+OkTLmeilnUuXIqSC/xqfSDM/HiuecknYoxbP3kd9hKx2cehT4HObmhFbuF/xhQPZqbrpS5uelNU6NYZN2TNkKRl2vokH+L/AM+8WzeDwhO2YLtkdvol4yEHqtUzAkYoPphfnaK8sVz1K2UJDCElRcmlRdoS1HZge3PbM63x1Elex/K89VgjbVD6Z44dVhOsHwhBD07ZM9H5kEWnuNBWgwR/HpaB1wt7ZFcbkkTwkGXSSrBySbmc+rG4BZIO0sT2GWMR6hYn4HETUDkVUUKukVUhEiBGcaIgD+ItgAp1wUaMXkgq6iK9yDLabMu8hMb9QGznCbbV/1yFfK1qixji2krFbVf1vS6noptSdRPe1eYP7qZ9yTGO/COaJZjzjHDM0gcxLR07TWiPPQ+p5XmnqrnvDytwtiplaBzqq79fur8ZjqZE6Fv7zruveaLcfy/jZgkqhwOsKqZ8YlabyY4gFvuAxhTvXuZIXhQFKjBFrWEc6zdMtMfycleUfIyFQkTdqUQc6j/9sdvXr/58fXdH75988/f/tu/73PakpH7mKVk8VMZm2OTV26SdAVheyCw+z7ZrYtuuZxgO7kkVG76s1SM4bYo1iFWcZ/p5MDlGqN+mQzIgFgn/H2W6tsfP6kYw+OnmDF+3jiQrS1/jIqg/qRsiUD8cmaJ8edEacEYlQjD/Wken2D8BI9R7ahfdPwa7E/dz/B86YTrHB32S6kSjLvAOdhs8/LXbWfUzulmgdpC+ymHXakjp2S68c7IK8C4EM+2YoFjrmdxz2e8V3RWZuRLzG117FaihUdUGsMlNPRAdKOQspGagWFPn4AxJclSiYO4mASP+1wgRU55z+zuJZEtA0K1YR1gRqgDHYBUJ0EpYdgs3m6e2Fpcp4Jq+WoPGnsua3ePeRAv/X5Vtw8U5OmxgV10Z5KxMFA/WbgSxLNJaTDLXmW8sRC8UaBY9hEPUn0XZduigTQt2jcxP0nS8HUjnXYJnkCqAoFY/9xQ0ysPaPOmQi4/RKW6jIHOUZc3qpbo8/h87Z5b08z269ZDtq5wAoc+Ylcfs79hfKRQutbvDtUjMhsrxitFoW1khkgIlxbxVTADBPXsB6JR6XGFYaRdNRER2psl5P5UkoqTaXAvYXm27d5RLBsBj3DzwXCU11FBVYX8nisZ5mrXvQk5qhbOoNTMYQZLSQlVslLDzXD6/IcdWaiEk1blgCil6fT9CFOe5lLC8tyxIzGPDE3UqhUEsacNOc2woAt0pHRI3Jgq6PqWMNJKJ30Noy1UWxj+nSkzY8LJq5bquauWLO+AJzmUHN+vYHfFnHkD4ieLHS84xX0nUFLXPyJoe4arpacKS1l2ZL8UI564C1zP3bwo4S1OttyDS54iljnlc1k6uzG5J64XOWdR6rsv7/I5HsBHYxIZ55okNfLO7+ZSsK6m1Sj1jnBAuvcR5AaZ3xglF0oJzl2GhH3t8AaQbv6YeD6VUFm0fdrP3WM5C92m5oFUxc7RXSbzEplwflvaVTz9CfdeDdfVF0c572OQ41BPMKllN99a/CEDaMJTrkYZUHsSVEqMrXRL1YrCdLtpJv67sCJBDb7Lsgn5mgn85DpAElSV8pERqCeQBXKmzUK19QSikjsjd/E6BLhydouvcO8eIrQeOb4/SFcHdAUy8wLwhsLvu5nDj1tqu12c6XgkCYTSqWzW0wULrcVCvmmfjY443lBqDrqH/4uF2zn/h16tKqFQLH1Si7xei/nT48xRw42f4SGeAkq766NjrmG/l0Ysu++0cIRHBpPae6QwqgoVfPwM0guzaiXxwwaKhYQ6wG6Bja6OyH6EYsm8sPUVY969izNuArjj6X4LIj+SOR1aaQsOuEHExH7PydFhxm6Tcv7vfj2te8/TngfJueGggW+fQZEwbfxAmc1UWRtgB61ZoE8HDeglaxEbwJcb+cIar+07sJrFHjmwtlGwxDbJZeiZ23JDGfBUH6s4O96uiwAvmUqRD40F7oAk3BmKc60M7Flfg4SR5pHvnT3NOF33WNoNqB4kMIqy9ciJRjUnQUJcaxkJq8ww9QtzR/Id8UBsgDBM1ydESLEXS3vlcQh2bYaHSAIOr9qGbXH7nrw3r65jrI7AmCHh4AJY+cIFuw67QfYIoa/va3qRICJh3xapDXQYt3LiQvleT1yoXdfhrFNJChIIc0+Bhx33KGEJ5N65jkiLaiXhWwwbEDBnDibESvAezOPapQR4ys2LT2CFLdLzZroElCGi2b2OPg2HIG0lBV5SrcPZO1Pc4fQmuiEFFx+bwo5KguU+i6Feaz28m5QtSD64JxRvxy2Ipa0d5i1g4TC4w6YUZurQzpbsSno/DDEl6GCXOpw4hWBmlGJapsebykCzrVioNghetHyVYENsKGkrFXhJO5WKdm2qBKFSQLBEtjtY3MiMDoM2qEISXF8VJGCpgcMURbmHqMMjiQY6/qiAy+LImAbvSqmxulLKHEijgDpLXu+k0BwM5UBV51Co0i6zuutuhF4cqjtGYWtNIJXIFXp5tMpQhuoS0YjZzGeLfM0WHrhK6tzXR7vq9+skFIUjz/fJNLonb7IMtY75rqEbHxPIJkWDYHKDFF7uSgXdc0KFA95aFxoqVykqN4JLcKeFHs5uXYg48YPdjutjxqEjDGqNelb5nNxku0AWBGOdPIBhrlIqOfBwqPBCPyoNl+sF5lvdL+9CHhWR+krm6B/AEsIjyltf7ao/nJRVFj5bkhdXw08/3EWYshijFT1hNxc5oW7dDbYWkDxdLI7w8H9a3uoqBaW/SDjdsUiBebTEApEAhm8qFEvFAsrh6DnOJbzquoVuKG2EcVE3FQpQGllAUEejgJqZ0jkMIAjIoAFXL9sd7/COB5sdJ5IInzOHsmm4J54rp+5nm1aOU/W1k5clWtIPrIX2UDeoUQbimcoj0nVUfzxxefuZjKPceC2ccM0naqonLkli49dxkJ8vRXD/Wpl8SSNEBmk2sxe+Cz5AWw80wzlIgalblb+oZrtfFrYqEmT0e6N1b/HVsFWC6Llm92X5IR8sAYPAgtU9breLNRySIAzfUmE8yNjZMqx2JiKHtNr8TKi50pzq+J1GwLqx9wL4/5krClpMxk2dPJZiQiYY6QOUosQdGS/4S9KjY4Vm4kdBlDXyBRGOuHqRKOu4ZGSpFksb5iG7Bg5qpGjJScGWEzG/RIDhrDtiZiRQDmLz8AjK4RzbkslPaiIC0vgIYVmdJYHNgJLRTB6/nFE2WTa3OD+GMycU3jVTDMDQL84dJvNo+UZ3HX3EK7r9eSYgqKD9gyHTtzNrLhlByJjT9sQbHlQwu9FhNLROm4ATQe/SLRjtTs2uV3UtswVvJq2gCvlLpvDju/gWaXx0me8VGograsa0+SIbSC2oEDfMoLcMTUMD8o+7R4LbCpSpLRuV7W4NeY+8dAIVelveekm6mSNjRR4SaLMkyc/j96f/Bw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [STORE = _t, AMT = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"STORE", type text}, {"AMT", type text}})
in
    #"Changed Type"