// Fuera_Mes_FY2020_Agosto_1
let
    Source = DB2.Database("ieecdb2v1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="-- IBM DB2 - 2º REPLICA WCS - CAPTURAS ANTICIPADAS - FACTURADAS FUERA DEL MES - UTERQÜE - AGOSTO 2020 - 1#(lf)SELECT#(lf)#(tab)o.ORDERS_ID,#(lf)#(tab)VARCHAR_FORMAT(o.TIMEPLACED, 'DD/MM/YYYY HH24:MI:SS') AS FECHA_CREACION,#(lf)#(tab)s.DIRECTORY,   #(lf)#(tab)COALESCE(xt1.COD_TIENDA_AS400, xt2.COD_TIENDA_AS400) AS COD_TIENDA_AS400,#(lf)#(tab)pid.GATEWAY_FRIENDLY_NAME,  #(lf)#(tab)REPLACE(DECIMAL (pi.APPROVEDAMOUNT, 12, 2), '.', ',' ) AS AUTORIZADO,#(lf)#(tab)REPLACE(DECIMAL (pi.DEPOSITEDAMOUNT, 12, 2), '.', ',' ) AS CAPTURADO,  #(lf)#(tab)VARCHAR_FORMAT(pit.TIMECREATED, 'DD/MM/YYYY HH24:MI:SS') AS FECHA_CAPTURA,#(lf)#(tab)o.CURRENCY,#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN xi.FFM_TYPE_ID = 1 THEN 'Almacen' #(lf)#(tab)#(tab)WHEN xi.FFM_TYPE_ID = 2 THEN 'Tienda' #(lf)#(tab)END AS TIPO_ORIGEN_STOCK,#(lf)#(tab)xi.FFM_ID AS ID_ORIGEN_STOCK,#(lf)#(tab)sm.CODE AS METODO_ENVIO,#(lf)#(tab)COALESCE(f.FECHA_CREACION, fi.FECHA_HORA_CREACION) AS FECHA_FACTURA,#(lf)#(tab)pit.REFERENCENUMBER AS NUMERO_OPERACION#(lf)FROM UECOITX_SP1.ORDERS o  #(lf)INNER JOIN UECOITX_SP1.STORE s#(lf)#(tab)ON (s.STORE_ID = o.STOREENT_ID)#(lf)#(tab)#(tab)AND s.DIRECTORY LIKE 'Uterque%'  #(lf)#(tab)#(tab)#(tab)AND o.TIMEPLACED >= '2020-08-01 00:00:00'#(lf)#(tab)#(tab)#(tab)#(tab)AND o.TIMEPLACED < '2020-08-10 00:00:00'#(lf)#(tab)#(tab)#(tab)#(tab)#(tab)AND o.STATUS NOT IN ('X','J','N','PQ')  #(lf)INNER JOIN UECOITX_SP1.ORDERITEMS oi#(lf)#(tab)ON (o.ORDERS_ID = oi.ORDERS_ID) #(lf)INNER JOIN UECOITX_SP1.SHIPMODE sm#(lf)#(tab)ON (sm.SHIPMODE_ID = oi.SHIPMODE_ID) #(lf)INNER JOIN UECOITX_SP1.ADDRESS a #(lf)#(tab)ON (a.ADDRESS_ID = oi.ADDRESS_ID)  #(lf)INNER JOIN UECOITX_SP1.XORDERS_INFO xo #(lf)#(tab)ON (o.ORDERS_ID = xo.ORDERS_ID)  #(lf)INNER JOIN UECOITX_SP1.XORDERITEMS_INFO xi#(lf)#(tab)ON (o.ORDERS_ID = xi.ORDERS_ID) #(lf)LEFT JOIN UECOITX_SP1.XIMPUESTO_TIENDA_AS400 xt1#(lf)#(tab)ON (xt1.STORE_ID = s.STORE_ID)#(lf)#(tab)#(tab)AND xt1.STATEPROVABBR = a.STATE  #(lf)INNER JOIN UECOITX_SP1.XIMPUESTO_TIENDA_AS400 xt2#(lf)#(tab)ON (xt2.STORE_ID = s.STORE_ID) #(lf)#(tab)#(tab)AND xt2.STATEPROVABBR IS NULL  #(lf)INNER JOIN UECOITX_SP1.PPCPAYINST pi #(lf)#(tab)ON (o.ORDERS_ID = pi.ORDER_ID)#(lf)#(tab)#(tab)AND pi.DEPOSITEDAMOUNT <> 0  #(lf)INNER JOIN UECOITX_SP1.XPAYMENT_DESC pid#(lf)#(tab)ON (pid.PAYMENT_METHOD = pi.PAYMENTSYSTEMNAME)#(lf)#(tab)#(tab)AND pid.GATEWAY_FRIENDLY_NAME <> 'Dummy'#(lf)INNER JOIN UECOITX_SP1.PPCPAYMENT pip#(lf)#(tab)ON (pip.PPCPAYINST_ID = pi.PPCPAYINST_ID)  #(lf)INNER JOIN UECOITX_SP1.PPCPAYTRAN pit#(lf)#(tab)ON (pit.PPCPAYMENT_ID = pip.PPCPAYMENT_ID) #(lf)#(tab)#(tab)AND pit.TRANSACTIONTYPE = 1#(lf)#(tab)#(tab)#(tab)AND pit.TIMEUPDATED >= '2020-08-01 00:00:00'  #(lf)#(tab)#(tab)#(tab)#(tab)AND#(tab)pit.TIMEUPDATED < '2020-08-10 00:00:00'#(lf)LEFT JOIN UECOITX_SP1.XFACTURA_INTEGRACION fi#(lf)#(tab)ON (fi.ORDERS_ID = o.ORDERS_ID)  #(lf)LEFT JOIN UECOITX_SP1.XFACTURA f#(lf)#(tab)ON (f.ORDERS_ID = o.ORDERS_ID)#(lf)WHERE#(lf)#(tab)(fi.ORDERS_ID IS NOT NULL #(lf)#(tab)#(tab)AND pit.TIMEUPDATED < fi.FECHA_HORA_CREACION #(lf)#(tab)#(tab)#(tab)AND fi.RMA_ID IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)AND fi.FECHA_HORA_CREACION >= '2020-09-01 00:00:00')  #(lf)#(tab)OR (f.ORDERS_ID IS NULL#(lf)#(tab)#(tab)AND pit.TIMEUPDATED < f.FECHA_CREACION #(lf)#(tab)#(tab)#(tab)AND fi.RMA_ID IS NULL#(lf)#(tab)#(tab)#(tab)#(tab)AND f.FECHA_CREACION >= '2020-09-01 00:00:00')  #(lf)GROUP BY #(lf)#(tab)o.ORDERS_ID,#(lf)#(tab)o.TIMEPLACED, #(lf)#(tab)s.DIRECTORY,#(lf)#(tab)COALESCE(xt1.COD_TIENDA_AS400,xt2.COD_TIENDA_AS400),  #(lf)#(tab)pid.GATEWAY_FRIENDLY_NAME,#(lf)#(tab)pi.APPROVEDAMOUNT,#(lf)#(tab)pi.DEPOSITEDAMOUNT,#(lf)#(tab)pit.TIMECREATED,#(lf)#(tab)o.CURRENCY,#(lf)#(tab)xi.FFM_TYPE_ID,#(lf)#(tab)xi.FFM_ID,#(lf)#(tab)sm.CODE,#(lf)#(tab)COALESCE(f.FECHA_CREACION, fi.FECHA_HORA_CREACION),#(lf)#(tab)pit.REFERENCENUMBER#(lf)ORDER BY #(lf)#(tab)o.ORDERS_ID #(lf)WITH UR;"]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ORDERS_ID", type text}, {"FECHA_CREACION", type datetime}, {"AUTORIZADO", Currency.Type}, {"CAPTURADO", Currency.Type}, {"FECHA_CAPTURA", type datetime}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type",{"ORDERS_ID", "FECHA_CREACION", "FECHA_CAPTURA", "FECHA_FACTURA", "NUMERO_OPERACION", "AUTORIZADO", "CAPTURADO", "CURRENCY", "DIRECTORY", "TIPO_ORIGEN_STOCK", "ID_ORIGEN_STOCK", "COD_TIENDA_AS400", "GATEWAY_FRIENDLY_NAME", "METODO_ENVIO"}),
    #"Renamed Columns" = Table.RenameColumns(#"Reordered Columns",{{"ORDERS_ID", "Pedido"}, {"FECHA_CREACION", "Fecha Creación"}, {"FECHA_CAPTURA", "Fecha Captura"}, {"NUMERO_OPERACION", "Número Operación"}, {"AUTORIZADO", "Autorizado"}, {"CAPTURADO", "Capturado"}, {"CURRENCY", "Moneda"}, {"DIRECTORY", "Directorio"}, {"TIPO_ORIGEN_STOCK", "Tipo Origen Stock"}, {"ID_ORIGEN_STOCK", "ID Origen Stock"}, {"COD_TIENDA_AS400", "Tienda"}, {"GATEWAY_FRIENDLY_NAME", "Gateway"}, {"METODO_ENVIO", "Metodo Envío"}, {"FECHA_FACTURA", "Fecha Factura"}})
in
    #"Renamed Columns"