// Cronos_Ultimos_30_Dias
let
    Source = Oracle.Database("PTR", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - PTR - CRONOS - BERSHKA#(lf)SELECT#(lf)#(tab)a.cod_ped AS cod_ped,#(lf)#(tab)a.cod_ped_indom AS cod_ped_indom,#(lf)#(tab)plat.descripcion AS pais,#(lf)#(tab)plat.id_pais AS id_pais,#(lf)#(tab)MAX(a.provincia) AS provincia,#(lf)#(tab)MAX(a.cod_postal) AS codigo_postal,#(lf)#(tab)MAX(a.ciudad) AS ciudad,#(lf)#(tab)MAX(a.distrito) AS distrito,#(lf)#(tab)MAX(a.cod_tienda_destino) AS cod_tienda_destino,#(lf)#(tab)COALESCE(alm.nombre_almacen, TO_CHAR(a.id_loc_alm)) AS almacen,#(lf)#(tab)te.descripcion AS tipo_envio,#(lf)#(tab)es.descripcion AS estado,#(lf)#(tab)tr.descripcion AS transportista,#(lf)#(tab)--a.cod_t_operativa_alm AS cod_t_operativa_alm,#(lf)#(tab)--a.es_stk_integrado AS es_stk_integrado,#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN MIN(cod_t_operativa_alm) > 0 #(lf)#(tab)#(tab)#(tab)AND MAX(es_consolidado) = 0 #(lf)#(tab)#(tab)#(tab)#(tab)AND COUNT(DISTINCT cod_ped_indom) > 1 THEN 1 #(lf)#(tab)#(tab)ELSE 0 #(lf)#(tab)END AS es_roto,#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN MIN(cod_t_operativa_alm) = 0 THEN 1 #(lf)#(tab)#(tab)ELSE 0 #(lf)#(tab)END AS es_picking_transfer,#(lf)#(tab)MAX(es_stk_integrado) AS es_stock_integrado,#(lf)#(tab)MAX(es_instant_delivery) AS es_instant_delivery,#(lf)#(tab)0 AS es_preventa,#(lf)#(tab)CASE #(lf)#(tab)#(tab)WHEN MAX(es_cruzado) > 0 #(lf)#(tab)#(tab)#(tab)AND COUNT(DISTINCT cod_ped_indom) = 1 THEN 1 #(lf)#(tab)#(tab)ELSE 0 #(lf)#(tab)END AS es_cruzado,#(lf)#(tab)MAX(es_consolidado) AS es_consolidado,#(lf)#(tab)ee.diferencia_horaria,#(lf)#(tab)a.feho_local AS feho_pedido,#(lf)#(tab)a.feho_limite_entrg AS feho_limite_entrg,#(lf)#(tab)a.feho_limite_transpt AS feho_limite_transpt,#(lf)#(tab)a.feho_limite_expe AS feho_limite_expedicion,#(lf)#(tab)MAX(eped_aux.ori_fec_entrg_seleccionada) AS origen_cronos,#(lf)#(tab)MAX(        #(lf)#(tab)#(tab)COALESCE(#(lf)#(tab)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 23 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)#(tab)END,#(lf)#(tab)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 1 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)#(tab)END)#(lf)#(tab)#(tab)) AS max_delivery_date_by_cronos,#(lf)#(tab)MAX(        #(lf)#(tab)#(tab)COALESCE(#(lf)#(tab)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 22 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)#(tab)END,#(lf)#(tab)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 2 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)#(tab)END)#(lf)#(tab)#(tab)) AS min_delivery_date_by_cronos,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 3 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS opt_delivery_date_by_cronos,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 4 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS max_delivery_date_backup,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 5 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS min_delivery_date_backup,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 7 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS max_warehouse_date_by_cronos,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 8 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS est_delivery_date_by_cronos,#(lf)#(tab)MAX(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN eped_tfec.id_t_fec = 14 THEN eped_tfec.feho #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS recalc_delivery_date_by_cronos,#(lf)#(tab)a.feho_alm AS feho_alm,#(lf)#(tab)a.feho_empaquetado AS feho_empaquetado,#(lf)#(tab)a.feho_expe AS feho_expedicion,#(lf)#(tab)a.feho_intento_entrg AS feho_intento_entrg,#(lf)#(tab)a.feho_entrg_tnd AS feho_entrg_tnd,#(lf)#(tab)a.feho_entrg_punto_entrg AS feho_entrg_punto_entrg,#(lf)#(tab)a.feho_entrg AS feho_entrg,#(lf)#(tab)a.feho_entrg_transp AS feho_entrg_transp,#(lf)#(tab)a.feho_entrg_cliente AS feho_entrg_cliente,#(lf)#(tab)TRUNC(feho_expe) - TRUNC(feho_local) AS dias_exp,#(lf)#(tab)TRUNC(feho_expe) - TRUNC(feho_alm) AS dias_exp_alm,#(lf)#(tab)TRUNC(feho_entrg_transp) - TRUNC(feho_expe) AS dias_transp,#(lf)#(tab)a.intervalo_rev_ok AS intervalo_rev_ok,#(lf)#(tab)--a.intervalo_preparacion_ok AS intervalo_preparacion_ok,#(lf)#(tab)--a.intervalo_pend_recogida_ok AS intervalo_pend_recogida_ok,#(lf)#(tab)--a.intervalo_trans_ok AS intervalo_trans_ok,#(lf)#(tab)--a.intervalo_entrg_ok AS intervalo_entrg_ok,#(lf)/* #(tab)CASE #(lf)#(tab)#(tab)WHEN a.feho_entrg IS NULL THEN 0 #(lf)#(tab)#(tab)ELSE 1 #(lf)#(tab)END AS completado_ok, */#(lf)#(tab)/* CASE #(lf)#(tab)#(tab)WHEN SUM(intervalo_rev_ok) >=1 THEN ROUND(( CAST( MAX(feho_alm) AS DATE ) - CAST( MIN(feho_local) AS DATE ) ) * 24*60*60,4) #(lf)#(tab)#(tab)ELSE NULL #(lf)#(tab)END AS tiempo_retenido_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.intervalo_preparacion_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_empaquetado AS DATE) - CAST(feho_alm AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_empaquetado_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.intervalo_pend_recogida_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_expe AS DATE) - CAST(feho_empaquetado AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_muelle_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.interv_transpt_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg_transp AS DATE) - CAST(feho_expe AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_intento_entrg_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.interv_recogida_cliente_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg_cliente AS DATE) - CAST(coalesce(feho_entrg_punto_entrg, feho_entrg_tnd) AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_recogida_cliente_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.interv_intento_entrg_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg AS DATE) - CAST(feho_entrg_transp AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_entre_intento_entrg_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.intervalo_entrg_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg_cliente AS DATE) - CAST(feho_local AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_entrg_cliente_seg, */#(lf)#(tab)/* AVG(#(lf)#(tab)#(tab)CASE #(lf)#(tab)#(tab)#(tab)WHEN a.intervalo_entrg_ok = 1 #(lf)#(tab)#(tab)#(tab)#(tab)AND cod_t_operativa_alm <> 0 THEN (CAST(feho_entrg AS DATE) - CAST(feho_local AS DATE)) * 24*60*60 #(lf)#(tab)#(tab)#(tab)ELSE NULL #(lf)#(tab)#(tab)END#(lf)#(tab)#(tab)) AS tiempo_entrg_seg, */#(lf)#(tab)CAST( TRUNC(MAX(feho_entrg)) AS DATE ) - CAST( TRUNC(MIN(feho_local)) AS DATE ) AS dias_entrega,#(lf)#(tab)CAST( TRUNC(MAX(feho_entrg_transp)) AS DATE ) - CAST( TRUNC(MIN(feho_limite_entrg)) AS DATE ) AS dias_vs_compromiso,#(lf)#(tab)(CASE#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(feho_entrg_transp) <= TRUNC(feho_limite_entrg) THEN 'OK'#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(feho_entrg_transp) > TRUNC(feho_limite_entrg) THEN 'KO'#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(sysdate) > TRUNC(feho_limite_entrg) THEN 'Riesgo'#(lf)#(tab)#(tab)ELSE 'Dato no informado'#(lf)#(tab)END) AS exito_entrega,#(lf)#(tab)(CASE#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(feho_entrg_transp) <= TRUNC(feho_limite_transpt) THEN 'OK'#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(feho_entrg_transp) > TRUNC(feho_limite_transpt) THEN 'KO'#(lf)#(tab)#(tab)WHEN feho_entrg_transp IS NULL #(lf)#(tab)#(tab)#(tab)AND TRUNC(sysdate) > TRUNC(feho_limite_transpt) THEN 'Riesgo'#(lf)#(tab)#(tab)ELSE 'Dato no informado'#(lf)#(tab)END) AS exito_transporte,#(lf)#(tab)(CASE#(lf)#(tab)#(tab)WHEN feho_expe IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND feho_expe <= feho_limite_expe THEN 'OK'#(lf)#(tab)#(tab)WHEN feho_expe IS NOT NULL #(lf)#(tab)#(tab)#(tab)AND feho_expe > feho_limite_expe THEN 'KO'#(lf)#(tab)#(tab)WHEN feho_expe IS NULL #(lf)#(tab)#(tab)#(tab)AND sysdate > feho_limite_expe THEN 'Riesgo'#(lf)#(tab)#(tab)ELSE 'Dato no informado'#(lf)#(tab)END) AS exito_expedicion#(lf)#(tab)--MAX (a.totaltax) AS totaltax#(lf)FROM aap_drive.fact_prev_entrg a#(lf)INNER JOIN aap_drive.drive_plat plat#(lf)#(tab)ON a.id_plat = plat.id_plat#(lf)INNER JOIN cdrive.ma_entidad_ecommerce ee#(lf)  ON ee.id_localizacion = a.cod_tienda_destino#(lf)    AND ee.id_plataforma > 0 -- EXCLUIMOS MARKETPLACES#(lf)LEFT JOIN aap_drive.drive_almacen alm#(lf)#(tab)ON a.id_loc_alm = alm.id_almacen#(lf)LEFT JOIN aap_drive.drive_entrg_t_env_cis te#(lf)#(tab)ON a.cod_t_env = te.cod_t_env#(lf)#(tab)#(tab)AND te.id_cadena = a.id_cadena#(lf)LEFT JOIN aap_drive.drive_entrg_est_ped_cis es#(lf)#(tab)ON a.cod_est_ped = es.cod_est_ped#(lf)#(tab)#(tab)AND es.id_cadena = a.id_cadena#(lf)LEFT JOIN aap_drive.drive_entrg_transptta tr#(lf)#(tab)ON a.cod_transptta = tr.cod_transptta#(lf)#(tab)#(tab)AND tr.id_cadena = a.id_cadena#(lf)LEFT JOIN fnd_etiquetado.pedido eped#(lf)#(tab)ON eped.cod_ped_ori_wcs = a.cod_ped#(lf)LEFT JOIN fnd_etiquetado.pedido_auxiliar eped_aux#(lf)#(tab)ON eped.id_ped = eped_aux.id_ped#(lf)LEFT JOIN fnd_etiquetado.pedido_tipo_fecha eped_tfec#(lf)#(tab)ON eped.id_ped = eped_tfec.id_ped#(lf)WHERE #(lf)#(tab)a.feho_local BETWEEN (CURRENT_DATE - 30)#(lf)    AND (CURRENT_TIMESTAMP)#(lf)      AND a.cod_est_ped NOT IN (10, 11, 31) #(lf)        AND a.id_cadena = 4 -- BERSHKA#(lf)        --AND a.es_stk_integrado = 1#(lf)        --AND es.descripcion IN ('En oleada', 'Enviado al almacen', 'Recibido almacen', 'En picking', 'Empaquetado')#(lf)GROUP BY #(lf)#(tab)a.cod_ped,#(lf)#(tab)a.cod_ped_indom,#(lf)#(tab)plat.descripcion,#(lf)        plat.id_pais,#(lf)#(tab)COALESCE(alm.nombre_almacen, TO_CHAR(a.id_loc_alm)),#(lf)#(tab)te.descripcion,#(lf)#(tab)a.cod_est_ped,#(lf)#(tab)es.descripcion,#(lf)#(tab)a.cod_transptta,#(lf)#(tab)tr.descripcion,#(lf)#(tab)--a.cod_t_operativa_alm,#(lf)#(tab)--a.es_stk_integrado,#(lf)#(tab)a.es_instant_delivery,#(lf)#(tab)a.es_roto,#(lf)#(tab)a.es_cruzado,#(lf)#(tab)a.es_consolidado,#(lf)#(tab)ee.diferencia_horaria,#(lf)#(tab)a.feho_ped,#(lf)#(tab)a.fec_ped,#(lf)#(tab)a.feho_local,#(lf)#(tab)a.feho_limite_expe,#(lf)#(tab)a.feho_limite_entrg,#(lf)#(tab)a.feho_expe,#(lf)#(tab)a.feho_empaquetado,#(lf)#(tab)a.feho_alm,#(lf)#(tab)a.feho_entrg,#(lf)#(tab)a.feho_entrg_cliente,#(lf)#(tab)a.feho_entrg_transp,#(lf)#(tab)a.feho_intento_entrg,#(lf)#(tab)a.feho_entrg_tnd,#(lf)#(tab)a.feho_entrg_punto_entrg,#(lf)#(tab)a.feho_limite_transpt,#(lf)#(tab)a.intervalo_rev_ok#(lf)#(tab)--a.intervalo_preparacion_ok,#(lf)#(tab)--a.intervalo_pend_recogida_ok,#(lf)#(tab)--a.intervalo_trans_ok,#(lf)#(tab)--a.intervalo_entrg_ok#(lf)ORDER BY#(lf)#(tab)a.feho_local ASC", CommandTimeout=#duration(0, 4, 0, 0)]),
    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"COD_PED", type text}, {"COD_PED_INDOM", type text}, {"ID_PAIS", Int64.Type}, {"COD_TIENDA_DESTINO", type text}, {"ES_ROTO", Int64.Type}, {"ES_PICKING_TRANSFER", Int64.Type}, {"ES_STOCK_INTEGRADO", Int64.Type}, {"ES_INSTANT_DELIVERY", Int64.Type}, {"ES_PREVENTA", Int64.Type}, {"ES_CRUZADO", Int64.Type}, {"ES_CONSOLIDADO", Int64.Type}, {"DIFERENCIA_HORARIA", Int64.Type}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"COD_PED", "Pedido"}, {"COD_PED_INDOM", "Subpedido"}, {"PAIS", "Mercado"}, {"ID_PAIS", "ID Mercado"}, {"PROVINCIA", "Provincia"}, {"CODIGO_POSTAL", "Código Postal"}, {"CIUDAD", "Ciudad"}, {"DISTRITO", "Distrito"}, {"COD_TIENDA_DESTINO", "Código Tienda Destino"}, {"ALMACEN", "Almacén"}, {"TIPO_ENVIO", "Tipo Envío"}, {"ESTADO", "Estado Pedido"}, {"TRANSPORTISTA", "Courier"}}),
    #"Columnas reordenadas" = Table.ReorderColumns(#"Columnas con nombre cambiado",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "ES_ROTO", "ES_PICKING_TRANSFER", "ES_STOCK_INTEGRADO", "ES_INSTANT_DELIVERY", "ES_PREVENTA", "ES_CRUZADO", "ES_CONSOLIDADO", "FEHO_PEDIDO", "FEHO_LIMITE_ENTRG", "FEHO_LIMITE_TRANSPT", "FEHO_LIMITE_EXPEDICION", "ORIGEN_CRONOS", "MAX_DELIVERY_DATE_BY_CRONOS", "MIN_DELIVERY_DATE_BY_CRONOS", "OPT_DELIVERY_DATE_BY_CRONOS", "MAX_DELIVERY_DATE_BACKUP", "MIN_DELIVERY_DATE_BACKUP", "MAX_WAREHOUSE_DATE_BY_CRONOS", "EST_DELIVERY_DATE_BY_CRONOS", "RECALC_DELIVERY_DATE_BY_CRONOS", "FEHO_ALM", "FEHO_EMPAQUETADO", "FEHO_EXPEDICION", "FEHO_INTENTO_ENTRG", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Personalizada agregada" = Table.AddColumn(#"Columnas reordenadas", "Pedido Roto", each if [ES_ROTO] = 0 then "No" else "Sí"),
    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Pedido Roto", type text}}),
    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado1", "Pedido PAT", each if [ES_PICKING_TRANSFER] = 0 then "No" else "Sí"),
    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"Pedido PAT", type text}}),
    #"Personalizada agregada2" = Table.AddColumn(#"Tipo cambiado2", "Pedido SINT", each if [ES_STOCK_INTEGRADO] = 0 then "No" else "Sí"),
    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Personalizada agregada2",{{"Pedido SINT", type text}}),
    #"Personalizada agregada3" = Table.AddColumn(#"Tipo cambiado3", "Pedido Instant Delivery", each if [ES_INSTANT_DELIVERY] = 0 then "No" else "Sí"),
    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Personalizada agregada3",{{"Pedido Instant Delivery", type text}}),
    #"Personalizada agregada4" = Table.AddColumn(#"Tipo cambiado4", "Pedido Preventa", each if [ES_PREVENTA] = 0 then "No" else "Sí"),
    #"Tipo cambiado5" = Table.TransformColumnTypes(#"Personalizada agregada4",{{"Pedido Preventa", type text}}),
    #"Personalizada agregada5" = Table.AddColumn(#"Tipo cambiado5", "Pedido Cruzado", each if [ES_CRUZADO] = 0 then "No" else "Sí"),
    #"Tipo cambiado6" = Table.TransformColumnTypes(#"Personalizada agregada5",{{"Pedido Cruzado", type text}}),
    #"Personalizada agregada6" = Table.AddColumn(#"Tipo cambiado6", "Pedido Consolidado", each if [ES_CONSOLIDADO] = 0 then "No" else "Sí"),
    #"Tipo cambiado7" = Table.TransformColumnTypes(#"Personalizada agregada6",{{"Pedido Consolidado", type text}}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado7",{"ES_ROTO", "ES_PICKING_TRANSFER", "ES_STOCK_INTEGRADO", "ES_INSTANT_DELIVERY", "ES_PREVENTA", "ES_CRUZADO", "ES_CONSOLIDADO"}),
    #"Columnas reordenadas1" = Table.ReorderColumns(#"Columnas quitadas",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "FEHO_PEDIDO", "FEHO_LIMITE_ENTRG", "FEHO_LIMITE_TRANSPT", "FEHO_LIMITE_EXPEDICION", "ORIGEN_CRONOS", "MAX_DELIVERY_DATE_BY_CRONOS", "MIN_DELIVERY_DATE_BY_CRONOS", "OPT_DELIVERY_DATE_BY_CRONOS", "MAX_DELIVERY_DATE_BACKUP", "MIN_DELIVERY_DATE_BACKUP", "MAX_WAREHOUSE_DATE_BY_CRONOS", "EST_DELIVERY_DATE_BY_CRONOS", "RECALC_DELIVERY_DATE_BY_CRONOS", "FEHO_ALM", "FEHO_EMPAQUETADO", "FEHO_EXPEDICION", "FEHO_INTENTO_ENTRG", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION", "DIFERENCIA_HORARIA"}),
    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas reordenadas1",{{"FEHO_PEDIDO", "Fecha Hora Pedido"}}),
    #"Columna condicional agregada" = Table.AddColumn(#"Columnas con nombre cambiado1", "Fecha Hora Límite Entrega", each if [MAX_DELIVERY_DATE_BY_CRONOS] <> null then [MAX_DELIVERY_DATE_BY_CRONOS] else if [MAX_DELIVERY_DATE_BACKUP] <> null then [MAX_DELIVERY_DATE_BACKUP] else [FEHO_LIMITE_ENTRG]),
    #"Tipo cambiado8" = Table.TransformColumnTypes(#"Columna condicional agregada",{{"Fecha Hora Límite Entrega", type datetime}}),
    #"Columnas reordenadas2" = Table.ReorderColumns(#"Tipo cambiado8",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Fecha Hora Pedido", "Fecha Hora Límite Entrega", "FEHO_LIMITE_ENTRG", "FEHO_LIMITE_TRANSPT", "FEHO_LIMITE_EXPEDICION", "ORIGEN_CRONOS", "MAX_DELIVERY_DATE_BY_CRONOS", "MIN_DELIVERY_DATE_BY_CRONOS", "OPT_DELIVERY_DATE_BY_CRONOS", "MAX_DELIVERY_DATE_BACKUP", "MIN_DELIVERY_DATE_BACKUP", "MAX_WAREHOUSE_DATE_BY_CRONOS", "EST_DELIVERY_DATE_BY_CRONOS", "RECALC_DELIVERY_DATE_BY_CRONOS", "FEHO_ALM", "FEHO_EMPAQUETADO", "FEHO_EXPEDICION", "FEHO_INTENTO_ENTRG", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas quitadas1" = Table.RemoveColumns(#"Columnas reordenadas2",{"FEHO_LIMITE_ENTRG", "MAX_DELIVERY_DATE_BY_CRONOS", "MIN_DELIVERY_DATE_BY_CRONOS", "OPT_DELIVERY_DATE_BY_CRONOS", "MAX_DELIVERY_DATE_BACKUP", "MIN_DELIVERY_DATE_BACKUP"}),
    #"Columna condicional agregada1" = Table.AddColumn(#"Columnas quitadas1", "Fecha Hora Límite Expedición", each if [MAX_WAREHOUSE_DATE_BY_CRONOS] <> null then [MAX_WAREHOUSE_DATE_BY_CRONOS] else [FEHO_LIMITE_EXPEDICION]),
    #"Tipo cambiado9" = Table.TransformColumnTypes(#"Columna condicional agregada1",{{"Fecha Hora Límite Expedición", type datetime}}),
    #"Columnas reordenadas3" = Table.ReorderColumns(#"Tipo cambiado9",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Fecha Hora Pedido", "Fecha Hora Límite Expedición", "Fecha Hora Límite Entrega", "FEHO_LIMITE_TRANSPT", "FEHO_LIMITE_EXPEDICION", "ORIGEN_CRONOS", "MAX_WAREHOUSE_DATE_BY_CRONOS", "EST_DELIVERY_DATE_BY_CRONOS", "RECALC_DELIVERY_DATE_BY_CRONOS", "FEHO_ALM", "FEHO_EMPAQUETADO", "FEHO_EXPEDICION", "FEHO_INTENTO_ENTRG", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas quitadas2" = Table.RemoveColumns(#"Columnas reordenadas3",{"MAX_WAREHOUSE_DATE_BY_CRONOS", "EST_DELIVERY_DATE_BY_CRONOS", "RECALC_DELIVERY_DATE_BY_CRONOS", "FEHO_LIMITE_EXPEDICION"}),
    #"Columnas con nombre cambiado2" = Table.RenameColumns(#"Columnas quitadas2",{{"FEHO_LIMITE_TRANSPT", "Fecha Hora Límite Courier"}, {"ORIGEN_CRONOS", "Origen Cronos"}}),
    #"Columnas reordenadas4" = Table.ReorderColumns(#"Columnas con nombre cambiado2",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Límite Expedición", "Fecha Hora Límite Entrega", "Fecha Hora Límite Courier", "FEHO_ALM", "FEHO_EMPAQUETADO", "FEHO_EXPEDICION", "FEHO_INTENTO_ENTRG", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado3" = Table.RenameColumns(#"Columnas reordenadas4",{{"FEHO_ALM", "Fecha Hora Recepción Almacén"}}),
    #"Columnas reordenadas5" = Table.ReorderColumns(#"Columnas con nombre cambiado3",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Límite Expedición", "Fecha Hora Límite Entrega", "Fecha Hora Límite Courier", "FEHO_EMPAQUETADO", "FEHO_EXPEDICION", "FEHO_INTENTO_ENTRG", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado4" = Table.RenameColumns(#"Columnas reordenadas5",{{"FEHO_EMPAQUETADO", "Fecha Hora Packing"}}),
    #"Columnas reordenadas6" = Table.ReorderColumns(#"Columnas con nombre cambiado4",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Límite Expedición", "Fecha Hora Límite Entrega", "Fecha Hora Límite Courier", "FEHO_EXPEDICION", "FEHO_INTENTO_ENTRG", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado5" = Table.RenameColumns(#"Columnas reordenadas6",{{"FEHO_EXPEDICION", "Fecha Hora Expedición"}}),
    #"Columnas reordenadas7" = Table.ReorderColumns(#"Columnas con nombre cambiado5",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "FEHO_INTENTO_ENTRG", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado6" = Table.RenameColumns(#"Columnas reordenadas7",{{"FEHO_INTENTO_ENTRG", "Fecha Hora Intento Entrega"}}),
    #"Columnas reordenadas8" = Table.ReorderColumns(#"Columnas con nombre cambiado6",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Intento Entrega", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "FEHO_ENTRG_TND", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado7" = Table.RenameColumns(#"Columnas reordenadas8",{{"FEHO_ENTRG_TND", "Fecha Hora Entrega Tienda"}}),
    #"Columnas reordenadas9" = Table.ReorderColumns(#"Columnas con nombre cambiado7",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "FEHO_ENTRG_PUNTO_ENTRG", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado8" = Table.RenameColumns(#"Columnas reordenadas9",{{"FEHO_ENTRG_PUNTO_ENTRG", "Fecha Hora Entrega Punto Entrega"}}),
    #"Columnas reordenadas10" = Table.ReorderColumns(#"Columnas con nombre cambiado8",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "FEHO_ENTRG", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado9" = Table.RenameColumns(#"Columnas reordenadas10",{{"FEHO_ENTRG", "Fecha Hora Entrega"}}),
    #"Columnas reordenadas11" = Table.ReorderColumns(#"Columnas con nombre cambiado9",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "FEHO_ENTRG_TRANSP", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado10" = Table.RenameColumns(#"Columnas reordenadas11",{{"FEHO_ENTRG_TRANSP", "Fecha Hora Entrega Courier"}}),
    #"Columnas reordenadas12" = Table.ReorderColumns(#"Columnas con nombre cambiado10",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Entrega Courier", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "FEHO_ENTRG_CLIENTE", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Columnas con nombre cambiado11" = Table.RenameColumns(#"Columnas reordenadas12",{{"FEHO_ENTRG_CLIENTE", "Fecha Hora Entrega Cliente"}}),
    #"Columnas reordenadas13" = Table.ReorderColumns(#"Columnas con nombre cambiado11",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Entrega Courier", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Entrega", "Fecha Hora Entrega Cliente", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "DIAS_EXP", "DIAS_EXP_ALM", "DIAS_TRANSP", "INTERVALO_REV_OK", "DIAS_ENTREGA", "DIAS_VS_COMPROMISO", "EXITO_ENTREGA", "EXITO_TRANSPORTE", "EXITO_EXPEDICION"}),
    #"Tipo cambiado10" = Table.TransformColumnTypes(#"Columnas reordenadas13",{{"DIAS_EXP", Int64.Type}, {"DIAS_EXP_ALM", Int64.Type}, {"DIAS_TRANSP", Int64.Type}, {"INTERVALO_REV_OK", Int64.Type}, {"DIAS_ENTREGA", Int64.Type}, {"DIAS_VS_COMPROMISO", Int64.Type}}),
    #"Columnas con nombre cambiado12" = Table.RenameColumns(#"Tipo cambiado10",{{"DIAS_EXP", "Número Días Expedición"}, {"DIAS_EXP_ALM", "Número Días Expedición Almacén"}, {"DIAS_TRANSP", "Número Días Courier"}}),
    #"Personalizada agregada7" = Table.AddColumn(#"Columnas con nombre cambiado12", "Revisión Intervalo OK", each if [INTERVALO_REV_OK] = 0 then "No" else "Sí"),
    #"Tipo cambiado11" = Table.TransformColumnTypes(#"Personalizada agregada7",{{"Revisión Intervalo OK", type text}}),
    #"Columnas quitadas3" = Table.RemoveColumns(#"Tipo cambiado11",{"INTERVALO_REV_OK"}),
    #"Columnas con nombre cambiado13" = Table.RenameColumns(#"Columnas quitadas3",{{"DIAS_ENTREGA", "Número Días Entrega Cliente"}, {"DIAS_VS_COMPROMISO", "Número Días vs. Compromiso"}, {"EXITO_ENTREGA", "Estado Entrega"}, {"EXITO_TRANSPORTE", "Estado Courier"}, {"EXITO_EXPEDICION", "Estado Expedición"}}),
    #"Columnas reordenadas14" = Table.ReorderColumns(#"Columnas con nombre cambiado13",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Entrega Courier", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Entrega", "Fecha Hora Entrega Cliente", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "Número Días Expedición", "Número Días Expedición Almacén", "Número Días Courier", "Número Días Entrega Cliente", "Número Días vs. Compromiso", "Estado Expedición", "Estado Courier", "Estado Entrega", "Revisión Intervalo OK"}),
    #"Personalizada agregada8" = Table.AddColumn(#"Columnas reordenadas14", "Tiempo Total Expedición", each Duration.TotalDays([Fecha Hora Expedición] - [Fecha Hora Pedido])),
    #"Tipo cambiado12" = Table.TransformColumnTypes(#"Personalizada agregada8",{{"Tiempo Total Expedición", type number}}),
    Redondeado = Table.TransformColumns(#"Tipo cambiado12",{{"Tiempo Total Expedición", each Number.Round(_, 2), type number}}),
    #"Personalizada agregada9" = Table.AddColumn(Redondeado, "Tiempo Recepción", each Duration.TotalDays([Fecha Hora Recepción Almacén] - [Fecha Hora Pedido])),
    #"Tipo cambiado13" = Table.TransformColumnTypes(#"Personalizada agregada9",{{"Tiempo Recepción", type number}}),
    Redondeado1 = Table.TransformColumns(#"Tipo cambiado13",{{"Tiempo Recepción", each Number.Round(_, 2), type number}}),
    #"Personalizada agregada10" = Table.AddColumn(Redondeado1, "Tiempo Packing", each Duration.TotalDays([Fecha Hora Packing] - [Fecha Hora Recepción Almacén])),
    #"Tipo cambiado14" = Table.TransformColumnTypes(#"Personalizada agregada10",{{"Tiempo Packing", type number}}),
    Redondeado2 = Table.TransformColumns(#"Tipo cambiado14",{{"Tiempo Packing", each Number.Round(_, 2), type number}}),
    #"Personalizada agregada11" = Table.AddColumn(Redondeado2, "Tiempo Expedición", each Duration.TotalDays([Fecha Hora Expedición] - [Fecha Hora Packing])),
    #"Tipo cambiado15" = Table.TransformColumnTypes(#"Personalizada agregada11",{{"Tiempo Expedición", type number}}),
    Redondeado3 = Table.TransformColumns(#"Tipo cambiado15",{{"Tiempo Expedición", each Number.Round(_, 2), type number}}),
    #"Columnas reordenadas15" = Table.ReorderColumns(Redondeado3,{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Entrega Courier", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Entrega", "Fecha Hora Entrega Cliente", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "Tiempo Recepción", "Tiempo Packing", "Tiempo Expedición", "Tiempo Total Expedición", "Número Días Expedición", "Número Días Expedición Almacén", "Número Días Courier", "Número Días Entrega Cliente", "Número Días vs. Compromiso", "Estado Expedición", "Estado Courier", "Estado Entrega", "Revisión Intervalo OK"}),
    #"Personalizada agregada12" = Table.AddColumn(#"Columnas reordenadas15", "Análisis Entrega", each if [Número Días vs. Compromiso] <> null then if [Número Días vs. Compromiso] <= -1 then "Entregado antes de plazo" else if [Número Días vs. Compromiso] = 0 then "Entregado en plazo" else "Entregado fuera de plazo" else "Aún no entregado"),
    #"Tipo cambiado16" = Table.TransformColumnTypes(#"Personalizada agregada12",{{"Análisis Entrega", type text}}),
    #"Fecha insertada" = Table.AddColumn(#"Tipo cambiado16", "Fecha", each DateTime.Date([Fecha Hora Pedido]), type date),
    #"Hora insertada" = Table.AddColumn(#"Fecha insertada", "Hora", each DateTime.Time([Fecha Hora Pedido]), type time),
    #"Columnas reordenadas16" = Table.ReorderColumns(#"Hora insertada",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha", "Hora", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Entrega Courier", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Entrega", "Fecha Hora Entrega Cliente", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "Tiempo Recepción", "Tiempo Packing", "Tiempo Expedición", "Tiempo Total Expedición", "Número Días Expedición", "Número Días Expedición Almacén", "Número Días Courier", "Número Días Entrega Cliente", "Número Días vs. Compromiso", "Estado Expedición", "Estado Courier", "Estado Entrega", "Revisión Intervalo OK", "Análisis Entrega"}),
    #"Columnas con nombre cambiado14" = Table.RenameColumns(#"Columnas reordenadas16",{{"Fecha", "Fecha Pedido"}, {"Hora", "Hora Pedido"}}),
    #"Consultas combinadas" = Table.NestedJoin(#"Columnas con nombre cambiado14", {"Código Tienda Destino"}, Localizacion, {"Localización"}, "Localizacion", JoinKind.LeftOuter),
    #"Se expandió Localizacion" = Table.ExpandTableColumn(#"Consultas combinadas", "Localizacion", {"Descripción"}, {"Descripción"}),
    #"Columnas reordenadas17" = Table.ReorderColumns(#"Se expandió Localizacion",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Descripción", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Entrega Courier", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Entrega", "Fecha Hora Entrega Cliente", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "Tiempo Recepción", "Tiempo Packing", "Tiempo Expedición", "Tiempo Total Expedición", "Número Días Expedición", "Número Días Expedición Almacén", "Número Días Courier", "Número Días Entrega Cliente", "Número Días vs. Compromiso", "Estado Expedición", "Estado Courier", "Estado Entrega", "Revisión Intervalo OK", "Análisis Entrega", "DIFERENCIA_HORARIA"}),
    #"Columnas con nombre cambiado15" = Table.RenameColumns(#"Columnas reordenadas17",{{"Descripción", "Descripción Tienda Destino"}, {"DIFERENCIA_HORARIA", "Diferencia Horaria con Irlanda"}}),
    #"Columna condicional agregada2" = Table.AddColumn(#"Columnas con nombre cambiado15", "Análisis Expedición", each if [Fecha Hora Expedición] = null then "No expedido" else "Expedido"),
    #"Tipo cambiado17" = Table.TransformColumnTypes(#"Columna condicional agregada2",{{"Análisis Expedición", type text}}),
    #"Columnas reordenadas18" = Table.ReorderColumns(#"Tipo cambiado17",{"Pedido", "Subpedido", "ID Mercado", "Mercado", "Provincia", "Ciudad", "Distrito", "Código Postal", "Código Tienda Destino", "Descripción Tienda Destino", "Almacén", "Tipo Envío", "Estado Pedido", "Courier", "Pedido Roto", "Pedido PAT", "Pedido SINT", "Pedido Instant Delivery", "Pedido Preventa", "Pedido Cruzado", "Pedido Consolidado", "Origen Cronos", "Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Recepción Almacén", "Fecha Hora Packing", "Fecha Hora Expedición", "Fecha Hora Entrega Courier", "Fecha Hora Intento Entrega", "Fecha Hora Entrega Tienda", "Fecha Hora Entrega Punto Entrega", "Fecha Hora Entrega", "Fecha Hora Entrega Cliente", "Fecha Hora Límite Expedición", "Fecha Hora Límite Courier", "Fecha Hora Límite Entrega", "Tiempo Recepción", "Tiempo Packing", "Tiempo Expedición", "Tiempo Total Expedición", "Número Días Expedición", "Número Días Expedición Almacén", "Número Días Courier", "Número Días Entrega Cliente", "Número Días vs. Compromiso", "Estado Expedición", "Estado Courier", "Estado Entrega", "Revisión Intervalo OK", "Análisis Entrega", "Análisis Expedición", "Diferencia Horaria con Irlanda"}),
    #"Personalizada agregada13" = Table.AddColumn(#"Columnas reordenadas18", "Fecha Hora Actual España", each DateTime.LocalNow()),
    #"Tipo cambiado18" = Table.TransformColumnTypes(#"Personalizada agregada13",{{"Fecha Hora Actual España", type datetime}}),
    #"Personalizada agregada14" = Table.AddColumn(#"Tipo cambiado18", "Fecha Hora Actual Local", each [Fecha Hora Actual España] + #duration(0,[Diferencia Horaria con Irlanda] - 1,0,0)),
    #"Tipo cambiado19" = Table.TransformColumnTypes(#"Personalizada agregada14",{{"Fecha Hora Actual Local", type datetime}}),
    #"Consultas combinadas1" = Table.NestedJoin(#"Tipo cambiado19", {"Almacén"}, Localizacion, {"Localización"}, "Localizacion", JoinKind.LeftOuter),
    #"Se expandió Localizacion1" = Table.ExpandTableColumn(#"Consultas combinadas1", "Localizacion", {"Descripción"}, {"Descripción"}),
    #"Columna condicional agregada3" = Table.AddColumn(#"Se expandió Localizacion1", "Origen Stock", each if [Descripción] = null then [Almacén] else [Descripción]),
    #"Tipo cambiado20" = Table.TransformColumnTypes(#"Columna condicional agregada3",{{"Origen Stock", type text}}),
    #"Columnas quitadas4" = Table.RemoveColumns(#"Tipo cambiado20",{"Descripción"})
in
    #"Columnas quitadas4"