// Compras_Actuales_Usuarios_Nuevos_Primera_Vez_Con_Mobile_Desktop
let
    Origen = Table.NestedJoin(Usuarios_Compra_Despues_1_Setp_2019, {"Email", "Mercado", "Cadena"}, Usuarios_Nuevos_Primera_Vez_Con_Mobile_Desktop, {"Email", "Mercado", "Cadena"}, "Usuarios_Nuevos_Primera_Vez_Con_Mobile_Desktop", JoinKind.Inner),
    #"Se expandió Usuarios_Nuevos_Primera_Vez_Con_Mobile_Desktop" = Table.ExpandTableColumn(Origen, "Usuarios_Nuevos_Primera_Vez_Con_Mobile_Desktop", {"Cadena"}, {"Cadena.1"}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió Usuarios_Nuevos_Primera_Vez_Con_Mobile_Desktop",{"Cadena.1"})
in
    #"Columnas quitadas"