// Stock_Insuficiente_GIPI_Solo_Info_Pedido
let
    Source = DB2.Database("ieecdb2v3:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="-- IBM DB2 - GIPI IRLANDA - STOCK INSUFICIENTE - BERSHKA#(lf)SELECT #(lf)#(tab)p.COD_PEDIDO_WCS,#(lf)#(tab)ep.DESCRIPCION,#(lf)#(tab)tienda.nombre AS TIENDA_VIRTUAL,#(lf)#(tab)p.FECHA_HORA_PEDIDO AS FECHA_PEDIDO,#(lf)#(tab)pcom.COMENTARIO AS COMENTARIO,#(lf)#(tab)pac.FECHA_HORA_ACCION AS FECHA_INSUFICIENTE,#(lf)#(tab)pcom.FECHA_HORA_COMENTARIO AS FECHA_RESOLUCION_INSUFICIENTE#(lf)FROM GIPI_ITX.pedido p#(lf)INNER JOIN maestros.entidad_ecommerce tienda #(lf)#(tab)ON tienda.id_entidad_ecommerce = p.id_entidad_ecommerce#(lf)#(tab)#(tab)AND tienda.id_cadena = 4 -- BERSHKA#(lf)INNER JOIN GIPI_ITX.PEDIDO_ACCION pac#(lf)#(tab)ON pac.id_pedido = p.id_pedido #(lf)#(tab)#(tab)AND pac.id_accion = 82 -- PASÓ A INSUFICIENTE#(lf)INNER JOIN GIPI_ITX.pedido_comentario pcom #(lf)#(tab)ON pcom.id_Pedido = p.id_pedido#(lf)INNER JOIN GIPI_ITX.estado_pedido ep#(lf)#(tab)ON ep.ID_ESTADO_PEDIDO = p.ID_ESTADO_PEDIDO#(lf)WHERE #(lf)#(tab)pac.FECHA_HORA_ACCION >= CURRENT TIMESTAMP - 60 DAYS#(lf)#(tab)AND p.FECHA_HORA_PEDIDO >= CURRENT TIMESTAMP - 60 DAYS#(lf)#(tab)AND (pcom.comentario LIKE ('Se ha eliminado%') #(lf)#(tab)#(tab)OR pcom.COMENTARIO LIKE ('Pedido%') #(lf)#(tab)#(tab)#(tab)OR PCOM.COMENTARIO LIKE ('Articulo%'))#(lf)#(tab)AND pcom.COMENTARIO <> 'Pedido actualizado automáticamente' #(lf)#(tab)AND pcom.COMENTARIO <> 'Pedido unitario'#(lf)UNION#(lf)SELECT #(lf)#(tab)p.COD_PEDIDO_WCS,#(lf)#(tab)ep.DESCRIPCION,#(lf)#(tab)tienda.nombre AS TIENDA_VIRTUAL,#(lf)#(tab)p.FECHA_HORA_PEDIDO AS FECHA_PEDIDO,#(lf)#(tab)'CANCELACION MANUAL POR INSUFICIENTE' AS COMENTARIO,#(lf)#(tab)PAC.FECHA_HORA_ACCION AS FECHA_INSUFICIENTE,#(lf)#(tab)P.FECHA_MODIFICACION AS FECHAS_RESOLUCION_INSUFICIENTE #(lf)FROM GIPI_ITX.pedido p#(lf)INNER JOIN maestros.entidad_ecommerce tienda #(lf)#(tab)ON tienda.id_entidad_ecommerce = p.id_entidad_ecommerce #(lf)#(tab)#(tab)AND tienda.id_cadena = 4 -- BERSHKA#(lf)INNER JOIN GIPI_ITX.pedido_accion pac #(lf)#(tab)ON pac.id_pedido = p.id_pedido #(lf)#(tab)#(tab)AND pac.id_accion = 82 #(lf)#(tab)#(tab)#(tab)AND P.EN_COMPASS = 0 #(lf)#(tab)#(tab)#(tab)#(tab)AND ID_ESTADO_PEDIDO = 9#(lf)INNER JOIN GIPI_ITX.estado_pedido ep#(lf)#(tab)ON ep.ID_ESTADO_PEDIDO = p.ID_ESTADO_PEDIDO#(lf)WHERE #(lf)#(tab)pac.FECHA_HORA_ACCION >= CURRENT TIMESTAMP - 60 DAYS#(lf)#(tab)AND p.FECHA_HORA_PEDIDO >= CURRENT TIMESTAMP - 60 DAYS#(lf)WITH UR;"]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"COD_PEDIDO_WCS", type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"COD_PEDIDO_WCS", "Pedido"}, {"TIENDA_VIRTUAL", "Tienda Virtual"}, {"FECHA_PEDIDO", "Fecha Hora Pedido"}, {"COMENTARIO", "Comentario"}, {"FECHA_INSUFICIENTE", "Fecha Hora Stock Insuficiente"}, {"FECHA_RESOLUCION_INSUFICIENTE", "Fecha Hora Resolución Stock Insuficiente"}, {"DESCRIPCION", "Estado Pedido"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"Pedido", "Tienda Virtual", "Fecha Hora Pedido", "Fecha Hora Stock Insuficiente", "Fecha Hora Resolución Stock Insuficiente", "Comentario"}),
    #"Added Custom" = Table.AddColumn(#"Reordered Columns", "Subpedido Calculado", each if Text.Contains([Comentario], "eliminado del subpedido") then Text.Trim(Text.BetweenDelimiters([Comentario], "subpedido ", " por")) 
else if Text.Contains([Comentario], "Se ha eliminado de forma automática") then Text.Trim(Text.AfterDelimiter([Comentario], "subpedido "))
else null),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Subpedido Calculado", type text}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Partnumber Calculado", each if Text.Contains([Comentario], "eliminado del subpedido") then Text.Trim(Text.BetweenDelimiters([Comentario], "Articulo ", "-")) 
else if Text.Contains([Comentario], "Se ha eliminado de forma automática") then Text.Trim(Text.BetweenDelimiters([Comentario], "artículo ", "-"))
else null),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Partnumber Calculado", type text}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Key Pedido Partnumber", each if [Partnumber Calculado] = null then [Pedido] else [Pedido] & "-" & [Partnumber Calculado]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom2",{{"Key Pedido Partnumber", type text}}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Changed Type3",{"Key Pedido Partnumber", "Pedido", "Subpedido Calculado", "Partnumber Calculado", "Estado Pedido", "Tienda Virtual", "Fecha Hora Pedido", "Fecha Hora Stock Insuficiente", "Fecha Hora Resolución Stock Insuficiente", "Comentario"}),
    #"Inserted Date" = Table.AddColumn(#"Reordered Columns1", "Date", each DateTime.Date([Fecha Hora Pedido]), type date),
    #"Inserted Time" = Table.AddColumn(#"Inserted Date", "Time", each DateTime.Time([Fecha Hora Pedido]), type time),
    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Time",{{"Date", "Fecha Pedido"}, {"Time", "Hora Pedido"}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns1",{"Key Pedido Partnumber", "Pedido", "Subpedido Calculado", "Partnumber Calculado", "Tienda Virtual", "Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Stock Insuficiente", "Fecha Hora Resolución Stock Insuficiente", "Comentario"}),
    #"Inserted Date1" = Table.AddColumn(#"Reordered Columns2", "Date", each DateTime.Date([Fecha Hora Stock Insuficiente]), type date),
    #"Inserted Time1" = Table.AddColumn(#"Inserted Date1", "Time", each DateTime.Time([Fecha Hora Stock Insuficiente]), type time),
    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Time1",{{"Date", "Fecha Stock Insuficiente"}, {"Time", "Hora Stock Insuficiente"}}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Renamed Columns2",{"Key Pedido Partnumber", "Pedido", "Subpedido Calculado", "Partnumber Calculado", "Tienda Virtual", "Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Stock Insuficiente", "Fecha Stock Insuficiente", "Hora Stock Insuficiente", "Fecha Hora Resolución Stock Insuficiente", "Comentario"}),
    #"Inserted Date2" = Table.AddColumn(#"Reordered Columns3", "Date", each DateTime.Date([Fecha Hora Resolución Stock Insuficiente]), type date),
    #"Inserted Time2" = Table.AddColumn(#"Inserted Date2", "Time", each DateTime.Time([Fecha Hora Resolución Stock Insuficiente]), type time),
    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Time2",{{"Date", "Fecha Resolución Stock Insuficiente"}, {"Time", "Hora Resolución Stock Insuficiente"}}),
    #"Reordered Columns4" = Table.ReorderColumns(#"Renamed Columns3",{"Key Pedido Partnumber", "Pedido", "Subpedido Calculado", "Partnumber Calculado", "Tienda Virtual", "Fecha Hora Pedido", "Fecha Pedido", "Hora Pedido", "Fecha Hora Stock Insuficiente", "Fecha Stock Insuficiente", "Hora Stock Insuficiente", "Fecha Hora Resolución Stock Insuficiente", "Fecha Resolución Stock Insuficiente", "Hora Resolución Stock Insuficiente", "Comentario"}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Reordered Columns4", "Fecha Hora Stock Insuficiente", "Fecha Hora Stock Insuficiente - Copy"),
    #"Changed Type4" = Table.TransformColumnTypes(#"Duplicated Column",{{"Fecha Hora Stock Insuficiente - Copy", type text}}),
    #"Renamed Columns4" = Table.RenameColumns(#"Changed Type4",{{"Fecha Hora Stock Insuficiente - Copy", "Fecha Hora Stock Insuficiente - Texto"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns4", each [Comentario] = "CANCELACION MANUAL POR INSUFICIENTE" or Text.Contains([Comentario], "cancelado por gestion de stock insuficiente automático"))
in
    #"Filtered Rows"