// Bershka_Location_RFID
let
    Source = DB2.Database("axindb2tndg6v1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="#(tab)#(lf)#(tab)#(lf)#(tab)WITH ped AS#(lf)(#(lf)    SELECT#(lf)        pa.ID_PAIS,#(lf)        ci.ABREVIATURA_CADENA_ECOMMERCE AS CADENA,#(lf)        loc.ID_LOCALIZACION,#(lf)        loc.DESCRIPCION AS TIENDA,#(lf)        lp.id_linea_pedido,#(lf)        lp.partnumber,#(lf)        lp.cantidad_solicitada#(lf)    FROM ECLOG_CADENAS_TND.SUBPEDIDO s#(lf)    INNER JOIN ECLOG_CADENAS_TND.PEDIDO p#(lf)        ON p.ID_PEDIDO = s.ID_PEDIDO#(lf)            AND p.ID_TIPO_OPERATIVA_PEDIDO <>3#(lf)            AND S.FECHA_ALTA >= (CURRENT_DATE - 7 days)#(lf)            AND P.FECHA_ALTA >= (CURRENT_DATE - 7 days) #(lf)    INNER JOIN ECLOG_CADENAS_TND.GRUPO_DISTRIBUCION gd#(lf)        ON gd.ID_GRUPO_DISTRIBUCION = p.ID_GRUPO_DISTRIBUCION#(lf)    INNER JOIN ECLOG_CADENAS_TND.LOCALIZACION_GRUPO_DISTRIBUCION lgd#(lf)        ON lgd.ID_LOCALIZACION = s.ID_LOCALIZACION#(lf)    INNER JOIN MAESTROS.LOCALIZACION loc#(lf)        ON loc.ID_LOCALIZACION = lgd.ID_LOCALIZACION#(lf)    INNER JOIN MAESTROS.PAIS pa#(lf)        ON pa.ID_PAIS = gd.ID_PAIS#(lf)    INNER JOIN ECLOG_CADENAS_TND.CADENA_INFORMACION ci#(lf)        ON ci.ID_CADENA = gd.ID_CADENA#(lf)    INNER JOIN ECLOG_CADENAS_TND.LINEA_PEDIDO lp#(lf)        ON s.ID_SUBPEDIDO = lp.ID_SUBPEDIDO#(lf)    WHERE#(lf)        gd.ID_CADENA IN(4)--Bershka#(lf)        AND p.ID_ESTADO_PEDIDO <>32#(lf)        --and s.id_localizacion = 1965#(lf)),#(lf)consulta1 AS (#(lf)SELECT#(lf)        ped.ID_PAIS,#(lf)        ped.ID_LOCALIZACION,#(lf)        ped.TIENDA,#(lf)        lpeit.ID_ESTADO_INVENTARIO_TIENDA,#(lf)        CASE#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 72 THEN 'INTERNAL STOCKROOM'#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 82 THEN 'EXTERNAL STOCKROOM'#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 62 THEN 'SHOPFLOOR'#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 92 THEN 'VIRTUAL SHOP WINDOW'#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 400 THEN 'ADMINISTRATIVE STOCK'#(lf)            ELSE 'N/A'#(lf)        END AS UBICACION,#(lf)        SUM(lpeit.CANTIDAD) as UNIDADES_TEORICAS#(lf)    FROM ECLOG_CADENAS_TND.LINEA_PEDIDO_ESTADO_INVENTARIO_TIENDA lpeit#(lf)    JOIN ped#(lf)        ON lpeit.ID_LINEA_PEDIDO = ped.ID_LINEA_PEDIDO#(lf)    GROUP BY#(lf)        ped.ID_PAIS,#(lf)        ped.ID_LOCALIZACION,#(lf)        ped.TIENDA,#(lf)        lpeit.ID_ESTADO_INVENTARIO_TIENDA#(lf)),#(lf)consulta2 AS (#(lf)SELECT#(lf)        ped.ID_PAIS,#(lf)        ped.ID_LOCALIZACION,#(lf)        ped.TIENDA,#(lf)        lpr.ID_ESTADO_INVENTARIO_TIENDA,#(lf)        CASE#(lf)            WHEN lpr.ID_ESTADO_INVENTARIO_TIENDA = 72 THEN 'INTERNAL STOCKROOM'#(lf)            WHEN lpr.ID_ESTADO_INVENTARIO_TIENDA = 82 THEN 'EXTERNAL STOCKROOM'#(lf)            WHEN lpr.ID_ESTADO_INVENTARIO_TIENDA = 62 THEN 'SHOPFLOOR'#(lf)            WHEN lpr.ID_ESTADO_INVENTARIO_TIENDA = 92 THEN 'VIRTUAL SHOP WINDOW'#(lf)            --WHEN lpr.ID_ESTADO_INVENTARIO_TIENDA = -1 THEN 'OTRO'#(lf)            --WHEN lpr.ID_ESTADO_INVENTARIO_TIENDA IS NULL THEN 'OTRO2'#(lf)            --WHEN lpr.ID_ESTADO_INVENTARIO_TIENDA = 33 THEN 'OTRO3'#(lf)            --ELSE 'ADMINISTRATIVE STOCK'#(lf)        END AS UBICACION,#(lf)        SUM(1) as UNIDADES_REALES#(lf)    FROM  PED#(lf)    LEFT JOIN ECLOG_CADENAS_TND.LINEA_PEDIDO_RFID lpr#(lf)        ON lpr.ID_LINEA_PEDIDO = ped.ID_LINEA_PEDIDO  AND lpr.ID_ESTADO_INVENTARIO_TIENDA in (62,72,82,92)#(lf)    GROUP BY#(lf)        ped.ID_PAIS,#(lf)        ped.ID_LOCALIZACION,#(lf)        ped.TIENDA,#(lf)        lpr.ID_ESTADO_INVENTARIO_TIENDA#(lf))#(lf)SELECT#(lf)    consulta1.ID_PAIS,#(lf)    consulta1.ID_LOCALIZACION,#(lf)    consulta1.TIENDA,#(lf)    consulta1.UBICACION,#(lf)    consulta1.UNIDADES_TEORICAS AS UDS_TEORICA,#(lf)    consulta2.UNIDADES_REALES AS UDS_REAL#(lf)FROM consulta1#(lf)INNER JOIN consulta2#(lf)    ON consulta1.ID_LOCALIZACION = consulta2.ID_LOCALIZACION#(lf)        AND consulta1.UBICACION = consulta2.UBICACION#(lf)UNION#(lf)SELECT#(lf)        pa.ID_PAIS,#(lf)        loc.ID_LOCALIZACION,#(lf)        loc.DESCRIPCION AS TIENDA,#(lf)        --ci.ABREVIATURA_CADENA_ECOMMERCE AS CADENA,#(lf)        CASE#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 72 THEN 'INTERNAL STOCKROOM'#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 82 THEN 'EXTERNAL STOCKROOM'#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 62 THEN 'SHOPFLOOR'#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 92 THEN 'VIRTUAL SHOP WINDOW'#(lf)            WHEN lpeit.ID_ESTADO_INVENTARIO_TIENDA = 400 THEN 'ADMINISTRATIVE STOCK'#(lf)            ELSE 'N/A'#(lf)        END AS UBICACION,#(lf)        SUM(lp.cantidad_solicitada) as UDS_TEORICA,#(lf)        null as UDS_REAL#(lf)    FROM ECLOG_CADENAS_TND.SUBPEDIDO s#(lf)    INNER JOIN ECLOG_CADENAS_TND.PEDIDO p#(lf)        ON p.ID_PEDIDO = s.ID_PEDIDO#(lf)            AND p.ID_TIPO_OPERATIVA_PEDIDO <>3#(lf)            AND S.FECHA_ALTA >= (CURRENT_DATE - 7 days)#(lf)            AND P.FECHA_ALTA >= (CURRENT_DATE - 7 days)#(lf)    INNER JOIN ECLOG_CADENAS_TND.GRUPO_DISTRIBUCION gd#(lf)        ON gd.ID_GRUPO_DISTRIBUCION = p.ID_GRUPO_DISTRIBUCION#(lf)    INNER JOIN ECLOG_CADENAS_TND.LOCALIZACION_GRUPO_DISTRIBUCION lgd#(lf)        ON lgd.ID_LOCALIZACION = s.ID_LOCALIZACION#(lf)    INNER JOIN MAESTROS.LOCALIZACION loc#(lf)        ON loc.ID_LOCALIZACION = lgd.ID_LOCALIZACION#(lf)    INNER JOIN MAESTROS.PAIS pa#(lf)        ON pa.ID_PAIS = gd.ID_PAIS#(lf)    INNER JOIN ECLOG_CADENAS_TND.CADENA_INFORMACION ci#(lf)        ON ci.ID_CADENA = gd.ID_CADENA#(lf)    INNER JOIN ECLOG_CADENAS_TND.LINEA_PEDIDO lp#(lf)        ON s.ID_SUBPEDIDO = lp.ID_SUBPEDIDO#(lf)    INNER JOIN ECLOG_CADENAS_TND.LINEA_PEDIDO_ESTADO_INVENTARIO_TIENDA lpeit#(lf)           ON lpeit.ID_LINEA_PEDIDO = LP.ID_LINEA_PEDIDO AND lpeit.ID_ESTADO_INVENTARIO_TIENDA = 400#(lf)    WHERE#(lf)        gd.ID_CADENA IN(4)--Bershka#(lf)        AND p.ID_ESTADO_PEDIDO <>32 --and s.ID_LOCALIZACION = 1965#(lf)        group by #(lf)        pa.ID_PAIS,#(lf)        ci.ABREVIATURA_CADENA_ECOMMERCE,#(lf)        loc.ID_LOCALIZACION,#(lf)        loc.DESCRIPCION,#(lf)        lpeit.ID_ESTADO_INVENTARIO_TIENDA#(lf)        ORDER BY 1 asc, 2 asc, 4 asc#(lf)        WITH UR", CommandTimeout=#duration(0, 7, 0, 0)]),
   #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_PAIS", Int64.Type}, {"ID_LOCALIZACION", type text}}),
    #"Added Custom Store Location" = Table.AddColumn(#"Changed Type", "ID Store", each Text.PadStart([ID_LOCALIZACION], 5, "0"), type text),
    #"Added Custom Store Description" = Table.AddColumn(#"Added Custom Store Location", "Store Description", each [ID Store] & " - " & [TIENDA], type text),
    #"Added Custom ID Country-Store" = Table.AddColumn(#"Added Custom Store Description", "ID Country-Store", each Text.Combine({Text.From([ID_PAIS], "es-ES"), "-", [ID Store]}), type text),
    #"Added Conditional Column Ordenar Ubicaciones" = Table.AddColumn(#"Added Custom ID Country-Store", "Ordenar Ubicaciones", each if [UBICACION] = "SHOPFLOOR" then 1 else if [UBICACION] = "INTERNAL STOCKROOM" then 2 else if [UBICACION] = "EXTERNAL STOCKROOM" then 3 else if [UBICACION] = "VIRTUAL SHOP WINDOW" then 4 else if [UBICACION] = "ADMINISTRATIVE STOCK" then 5 else if [UBICACION] = "N/A" then 6 else null, Int64.Type),
    #"Merged Queries Countries" = Table.NestedJoin(#"Added Conditional Column Ordenar Ubicaciones", {"ID_PAIS"}, Countries, {"Country"}, "Countries", JoinKind.LeftOuter),
    #"Expanded Countries" = Table.ExpandTableColumn(#"Merged Queries Countries", "Countries", {"English Description"}, {"Market English"}),
    #"Removed Columns" = Table.RemoveColumns(#"Expanded Countries",{"ID_LOCALIZACION"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"ID_PAIS", "ID Country"}, {"TIENDA", "Store"}, {"UBICACION", "Ubicacion"}, {"UDS_TEORICA", "Teorico Unidades"},  {"UDS_REAL", "Real Unidades"}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"ID Country", "Market English", "ID Country-Store", "ID Store", "Store", "Store Description", "Ubicacion", "Ordenar Ubicaciones", "Teorico Unidades", "Real Unidades"})
in
    #"Reordered Columns"