// Market_Store
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - OMNICHANNEL - BERSHKA - SINT VERSION DRIVE - MARKET, STORE AND BRAND#(lf)SELECT #(lf)  DISTINCT #(lf)    dp.PAIS country,#(lf)    dp.PAIS_ISO ISO,#(lf)    dp.DESCRIPCION market,#(lf)    dp.DESCRIPCION_INGLES market_english,#(lf)    dl1.DESCRIPCION physical_store,#(lf)    dl1.DESCRIPCION_DB2,#(lf)    dl1.LOCALIZACION location#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)  ON dp.ID_PAIS = mf.ID_PAIS#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)  ON dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING#(lf)    AND dl1.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- PICKING EN TIENDA#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)  ON dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALMACEN#(lf)    AND dl2.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- EXPEDICIÓN DESDE TIENDA#(lf)WHERE#(lf)  mf.ID_FECHA_PLATAFORMA BETWEEN TO_DATE ('01/01/2020', 'DD/MM/YYYY')#(lf)    AND TO_DATE ('28/02/2022', 'DD/MM/YYYY')#(lf)  AND mf.ID_FECHA BETWEEN TO_DATE ('01/02/2020', 'DD/MM/YYYY') #(lf)    AND TO_DATE ('31/01/2022', 'DD/MM/YYYY')#(lf)  AND ((mf.ID_TIPO_MOVIMIENTO IN (72, 772) AND mf.ESTADO NOT IN ('X', 'N', 'PQ')) -- ORDER TRANSACTION#(lf)    OR mf.ID_TIPO_MOVIMIENTO IN (73, 808)) -- RETURN TRANSACTION#(lf)  AND mf.ID_CADENA = 5 -- BERSHKA    #(lf)  AND mf.REPOSICION = 0 -- DRIVE#(lf)  AND mf.ES_CAMBIO = 0 -- DRIVE#(lf)  AND mf.ID_SECCION > 0 -- DRIVE#(lf)  AND mf.ID_PAIS > 0 -- DRIVE#(lf)  AND dl1.LOCALIZACION > 0 -- QUITAMOS LOS ""NO TIENE""#(lf)ORDER BY #(lf)  dl1.LOCALIZACION ASC", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MARKET", type text}, {"COUNTRY", Int64.Type}, {"LOCATION", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",",","",Replacer.ReplaceText,{"MARKET", "MARKET_ENGLISH"}),
    #"Added Custom Store Description" = Table.AddColumn(#"Replaced Value", "Store Description", each if [PHYSICAL_STORE] = "NO TIENE" then "NO TIENE" else  Text.PadStart(Text.BeforeDelimiter([PHYSICAL_STORE], " -"), 5, "0") & " - " & Text.AfterDelimiter([PHYSICAL_STORE], "- "), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom Store Description",{"PHYSICAL_STORE"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"MARKET", "Market"}, {"COUNTRY", "Country"}, {"MARKET_ENGLISH", "Market English"}, {"LOCATION", "Location"}, {"DESCRIPCION_DB2", "Store Description Logistics"}}),
    #"Added Custom Market-Store" = Table.AddColumn(#"Renamed Columns", "Market - Store", each [Market English] & " - " & [Store Description], type text),
    #"Added Custom ID Store" = Table.AddColumn(#"Added Custom Market-Store", "ID Store", each if [Location] = "0" then "DOES NOT HAVE" else Text.PadStart([Location],5,"0"), type text),
    #"Inserted Merged Column ID Country-Store" = Table.AddColumn(#"Added Custom ID Store", "ID Country-Store", each Text.Combine({ Text.From([Country], "es-ES"),[ID Store]}, "-"), type text),
    #"Removed Columns1" = Table.RemoveColumns(#"Inserted Merged Column ID Country-Store",{"Location"}),
    #"Merged Queries Pack Store" = Table.NestedJoin(#"Removed Columns1", {"ID Store"}, Packing_Stores, {"ID Store"}, "Packing_Stores", JoinKind.LeftOuter),
    #"Expanded Pack Store" = Table.ExpandTableColumn(#"Merged Queries Pack Store", "Packing_Stores", {"Pack Store"}, {"Pack Store"}),
    #"Replaced Value Pack Store null" = Table.ReplaceValue(#"Expanded Pack Store", null,"NO PACK STORES",Replacer.ReplaceValue,{"Pack Store"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Replaced Value Pack Store null",{"ID Country-Store", "ISO", "Country", "Market", "Market English", "ID Store", "Store Description", "Store Description Logistics", "Market - Store", "Pack Store"})
in
    #"Reordered Columns"