// Bershka_Orders_Market_MICRO
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - PEDIDOS SINT - BERSHKA - MERCADO - FY2020, FY2022#(lf)SELECT#(lf)  mf.ID_FECHA,#(lf)  COUNT(DISTINCT mf.ID_PEDIDO_ECOMMERCE) pedidos,#(lf)  SUM(mf.UNIDADES) unidades,#(lf)  SUM(mf.IMPORTE) local_amount,#(lf)  SUM(ROUND (mf.IMPORTE * mf.CAMBIO_REFERENCIA, 2)) amount_euros,#(lf)  dp.DESCRIPCION_INGLES market_english,#(lf)  dp.PAIS#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)  ON dp.ID_PAIS = mf.ID_PAIS#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)  ON dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING#(lf)  AND dl1.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- PICKING EN TIENDA#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)  ON dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALMACEN#(lf)  AND dl2.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- EXPEDICIÓN DESDE TIENDA#(lf)WHERE#(lf)  mf.ID_FECHA_PLATAFORMA BETWEEN TO_DATE ('01/01/2020', 'DD/MM/YYYY')#(lf)    AND TO_DATE ('28/02/2022', 'DD/MM/YYYY')#(lf)  AND mf.ID_FECHA BETWEEN TO_DATE ('01/02/2020', 'DD/MM/YYYY') #(lf)    AND TO_DATE ('31/01/2022', 'DD/MM/YYYY')#(lf)  AND mf.ID_TIPO_MOVIMIENTO IN (72, 772) -- ORDER TRANSACTION#(lf)  AND mf.ESTADO NOT IN ('X', 'N', 'PQ') #(lf)  AND mf.ID_CADENA = 5 -- BERSHKA #(lf)  AND mf.REPOSICION = 0 -- DRIVE#(lf)  AND mf.ES_CAMBIO = 0 -- DRIVE#(lf)  AND mf.ID_SECCION > 0 -- DRIVE#(lf)  AND mf.ID_PAIS > 0 -- DRIVE#(lf)  AND dl1.LOCALIZACION > 0 -- QUITAMOS LOS ""NO TIENE""#(lf)GROUP BY#(lf)  mf.ID_FECHA,#(lf)  dp.PAIS,#(lf)  dp.DESCRIPCION_INGLES", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_FECHA", type date}, {"PEDIDOS", Int64.Type}, {"UNIDADES", Int64.Type}, {"PAIS", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"ID_FECHA", "Date"}, {"PEDIDOS", "Orders"}, {"UNIDADES", "Units"}, {"AMOUNT_EUROS", "Amount (€)"}, {"MARKET_ENGLISH", "Market English"},  {"LOCAL_AMOUNT", "Local Amount"}, {"PAIS", "ID Country"}}),
    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns",",","",Replacer.ReplaceText,{"Market English"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Replaced Value",{"Date", "ID Country", "Market English", "Orders", "Units", "Amount (€)", "Local Amount"})
in
    #"Reordered Columns"