// Zara_Packing_Stores
let
    Source = DB2.Database("axindb2tndg6v1:50000", "inditex", [HierarchicalNavigation=true, Implementation="IBM", Query="-- IBM DB2 - LOGISTICS TIENDA ENTORNO PRO - OMNICHANNEL - PACKING STORE - ZARA - SINT#(lf)select #(lf)    t.ID_TIENDA,#(lf)    t.NOMBRE_TIENDA,#(lf)    t.ID_CADENA#(lf)from ECLOG_ITX_TND.GRUPO_DISTRIBUCION as g#(lf)inner join ECLOG_ITX_TND.LOCALIZACION_GRUPO_DISTRIBUCION l #(lf)    on g.ID_GRUPO_DISTRIBUCION = l.ID_GRUPO_DISTRIBUCION#(lf)inner join MAESTROS.TIENDA t #(lf)    on l.ID_LOCALIZACION = t.ID_TIENDA #(lf)    and t.ID_TIPO_TIENDA = 13 -- PACKING STORE#(lf)where #(lf)    g.id_cadena in (1,16)#(lf)WITH UR", CommandTimeout=#duration(0, 12, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_TIENDA", type text}}),
    #"Added ID Store" = Table.AddColumn(#"Changed Type", "ID Store", each if [ID_TIENDA] = "0" then "DOES NOT HAVE" else Text.PadStart([ID_TIENDA],5,"0"), type text),
    #"Added Pack Store" = Table.AddColumn(#"Added ID Store", "Pack Store", each "PACK STORES", type text)
in
    #"Added Pack Store"