// Compras_Actuales_Usuarios_Nuevos_Primera_Vez_Con_APP
let
    Origen = Table.NestedJoin(Usuarios_Compra_Despues_1_Setp_2019, {"Email", "Mercado", "Cadena"}, Usuarios_Nuevos_Primera_Vez_Con_APP, {"Email", "Mercado", "Cadena"}, "Usuarios_Nuevos_Primera_Vez_Con_APP", JoinKind.Inner),
    #"Se expandió Usuarios_Nuevos_Primera_Vez_Con_APP" = Table.ExpandTableColumn(Origen, "Usuarios_Nuevos_Primera_Vez_Con_APP", {"Cadena"}, {"Cadena.1"}),
    #"Columnas quitadas" = Table.RemoveColumns(#"Se expandió Usuarios_Nuevos_Primera_Vez_Con_APP",{"Cadena.1"})
in
    #"Columnas quitadas"