// Num_Usuarios_Nuevos_Primera_Vez_Con_APP
let
    Source = Oracle.Database("axine1-scansrv.central.inditex.grp:11521/s_itxpro_mstrcorp", [HierarchicalNavigation=true, Query="-- PULL#(lf)-- CLIENTES QUE NUNCA HABÍAN COMPRADO ANTES Y QUE ENTRE EL 26 DE AGOSTO Y EL 1 DE SEPTIEMBRE COMPRARON POR PRIMERA VEZ HACIENDO USO DE LA APP (EXCLUIMOS IPOD Y MARKETPLACES)#(lf)WITH anterior AS#(lf)(#(lf)SELECT#(lf)  DISTINCT#(lf)    u.EMAIL, #(lf)    f.ID_PAIS, #(lf)    f.ID_CADENA#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM f#(lf)INNER JOIN DMECOMMERCE.DIM_USUARIO_ECOMM u  #(lf)  ON (u.ID_USUARIO_ECOMM = f.ID_USUARIO_ECOMM #(lf)    AND u.ID_PAIS = f.ID_PAIS)#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION l#(lf)  ON (l.ID_LOCALIZACION = f.ID_LOCALIZACION)#(lf)WHERE #(lf)  f.ID_FECHA_PLATAFORMA < TO_DATE('01-10-2019', 'DD-MM-YYYY')#(lf)      AND f.ID_FECHA < TO_DATE('26-08-2019', 'DD-MM-YYYY')#(lf)  AND f.ID_CADENA = 3 -- PULL#(lf)  AND f.ID_TIPO_MOVIMIENTO IN (72,772) #(lf)  AND f.ESTADO <> 'X'#(lf)  AND f.ID_TIPO_DISPOSITIVO <> 23 -- EXCLUIMOS IPOD#(lf)  AND l.ID_TIPO_TIENDA <> 6 -- EXCLUIMOS MARKETPLACES#(lf)),#(lf)ano_2019 AS #(lf)(#(lf)SELECT#(lf)  u.EMAIL, #(lf)  COUNT (DISTINCT f.ID_PEDIDO_ECOMMERCE) num_pedidos, #(lf)  f.ID_PAIS, #(lf)  f.ID_CADENA#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM f#(lf)INNER JOIN DMECOMMERCE.DIM_USUARIO_ECOMM u  #(lf)  ON (u.ID_USUARIO_ECOMM = f.ID_USUARIO_ECOMM #(lf)    AND u.ID_PAIS = f.ID_PAIS)#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION l#(lf)  ON (l.ID_LOCALIZACION = f.ID_LOCALIZACION)#(lf)WHERE#(lf)  f.ID_FECHA_PLATAFORMA > TO_DATE('01-08-2019', 'DD-MM-YYYY')#(lf)    AND f.ID_FECHA_PLATAFORMA < TO_DATE('01-10-2019', 'DD-MM-YYYY')#(lf)  AND f.ID_FECHA >= TO_DATE('26-08-2019', 'DD-MM-YYYY') #(lf)    AND f.ID_FECHA <= TO_DATE('01-09-2019', 'DD-MM-YYYY')#(lf)  AND f.ID_CADENA = 3 -- PULL#(lf)  AND f.ID_TIPO_MOVIMIENTO IN (72,772) #(lf)  AND f.ESTADO <> 'X'#(lf)  AND f.ID_TIPO_DISPOSITIVO <> 23 -- EXCLUIMOS IPOD#(lf)  AND l.ID_TIPO_TIENDA <> 6 -- EXCLUIMOS MARKETPLACES#(lf)  AND f.ID_TIPO_DISPOSITIVO IN (25, 26) -- APP IOS Y ANDROID#(lf)GROUP BY#(lf)  u.EMAIL, #(lf)  f.ID_PAIS, #(lf)  f.ID_CADENA#(lf))#(lf)SELECT#(lf)  COUNT (DISTINCT ano.EMAIL) num_clientes,#(lf)  SUM (ano.num_pedidos) num_pedidos,#(lf)  p.DESCRIPCION,#(lf)  c.CADENA#(lf)FROM#(lf)  ano_2019 ano#(lf)LEFT JOIN anterior ant#(lf)  ON (ano.EMAIL = ant.EMAIL#(lf)    AND ano.ID_PAIS = ant.ID_PAIS#(lf)      AND ano.ID_CADENA = ant.ID_CADENA)#(lf)INNER JOIN DMCOMERCIAL.DIM_CADENA c#(lf)  ON (c.ID_CADENA = ano.ID_CADENA)#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS p#(lf)  ON (p.ID_PAIS = ano.ID_PAIS)#(lf)WHERE#(lf)  ant.EMAIL is null#(lf)GROUP BY#(lf)  p.DESCRIPCION,#(lf)  c.CADENA#(lf)ORDER BY #(lf)  COUNT (DISTINCT ano.EMAIL) DESC"]),
    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"NUM_CLIENTES", Int64.Type}, {"NUM_PEDIDOS", Int64.Type}}),
    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"NUM_CLIENTES", "Número Clientes"}, {"NUM_PEDIDOS", "Número Pedidos"}, {"DESCRIPCION", "Mercado"}, {"CADENA", "Cadena"}})
in
    #"Columnas con nombre cambiado"