// Ipod_Returns
let
    Source = Table.Combine({Ipod_Returns_FY2021, Ipod_Returns_FY2020}),
    #"Added Custom" = Table.AddColumn(Source, "MoCaCo", each Text.PadStart([Modelo], 4, "0") & Text.PadStart([Calidad], 3, "0") & Text.PadStart([Color], 3, "0")),
    #"Replaced Value" = Table.ReplaceValue(#"Added Custom",null,"Sin información",Replacer.ReplaceValue,{"Country ISO"}),
    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"Sin información",Replacer.ReplaceValue,{"City"}),
    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",null,"Sin información",Replacer.ReplaceValue,{"Street"}),
    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2",",","",Replacer.ReplaceText,{"Market"}),
    #"Added Custom1" = Table.AddColumn(#"Replaced Value3", "Store", each Text.PadStart(Text.BeforeDelimiter([Physical Store], " -"), 5, "0") & " - " & Text.AfterDelimiter([Physical Store], "- ")),
    #"Changed Type" = Table.TransformColumnTypes(#"Added Custom1",{{"MoCaCo", type text}, {"Store", type text}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type", "Market - Store", each [Market] & " - " & [Store]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom2",{{"Market - Store", type text}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type1",{"Modelo", "Calidad", "Color", "Physical Store"}),
    #"Merged Columns" = Table.CombineColumns(#"Removed Columns",{"Ecommerce Payment Type", "Ipod Payment Type"},Combiner.CombineTextByDelimiter(" - ", QuoteStyle.None),"Ecommerce Payment Type - Ipod Payment Type"),
    #"Merged Queries" = Table.NestedJoin(#"Merged Columns",{"Ecommerce Payment Type - Ipod Payment Type"},Equivalences_Payment_Type,{"Ecommerce Payment Type - Ipod Payment Type"},"Equivalences_Payment_Type",JoinKind.LeftOuter),
    #"Expanded Equivalences_Payment_Type" = Table.ExpandTableColumn(#"Merged Queries", "Equivalences_Payment_Type", {"Payment Device", "Payment Type", "Payment Method"}, {"Payment Device", "Payment Type", "Payment Method"}),
    #"Removed Columns1" = Table.RemoveColumns(#"Expanded Equivalences_Payment_Type",{"Ecommerce Payment Type - Ipod Payment Type"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns1",{"Date", "Hour", "Minute", "Return Order Date", "Return Order Hour", "Ecommerce Order ID", "Ecommerce Return ID", "MoCaCo", "Units", "Local Credit Amount", "Credit Amount (€)", "Payment Method", "Payment Type", "Payment Device", "Chain ID", "Section ID", "Ecommerce Order Status", "Market", "Store", "Market - Store", "Country ISO", "City", "Street", "Postal Code", "Longitude", "Latitude"})
in
    #"Reordered Columns1"
