// Zara_Orders_Store_PAT_BF_LAST
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - PEDIDOS PAT - ZARA - TIENDA - LAST 11/11#(lf)SELECT#(lf)     mf.ID_FECHA,#(lf)    COUNT(DISTINCT mf.ID_PEDIDO_ECOMMERCE) pedidos,#(lf)    SUM(mf.UNIDADES) unidades,#(lf)    SUM(mf.IMPORTE) local_amount,#(lf)    SUM(ROUND (mf.IMPORTE * mf.CAMBIO_REFERENCIA, 2)) amount_euros,#(lf)#(tab)dp.DESCRIPCION_INGLES market_english,#(lf)    dl1.LOCALIZACION location,#(lf)    dp.PAIS Country,#(lf)    dl1.DESCRIPCION physical_store#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMECOMMERCE.DIM_ESTADO_PEDIDO_ECOMMERCE depe#(lf)    ON (depe.ID_ESTADO_PEDIDO_ECOMMERCE = mf.ID_ESTADO_PEDIDO_ECOMMERCE)#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)    ON (dp.ID_PAIS = mf.ID_PAIS)#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)    ON (dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING)#(lf)        AND (dl1.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121)) -- PICKING EN TIENDA#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)    ON (dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALMACEN)#(lf)        AND (dl2.ID_TIPO_LOC NOT IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121)) -- EXPEDICIÓN DESDE ALMACÉN#(lf)WHERE#(lf)#(tab)mf.ID_FECHA_PLATAFORMA BETWEEN TO_DATE ('01/10/2019', 'DD/MM/YYYY')#(lf)#(tab)#(tab)AND TO_DATE ('01/12/2019', 'DD/MM/YYYY')#(lf)#(tab)AND mf.ID_FECHA BETWEEN TO_DATE ('28/11/2019', 'DD/MM/YYYY') #(lf)#(tab)#(tab)AND TO_DATE ('29/11/2019', 'DD/MM/YYYY')#(lf)    AND mf.ID_TIPO_MOVIMIENTO IN (72, 772) -- ORDER TRANSACTION#(lf)    AND mf.ESTADO NOT IN ('X', 'M')#(lf)    AND mf.ID_CADENA IN (1, 2) -- ZARA, ZARA SUR#(lf)    AND mf.REPOSICION = 0 -- DRIVE#(lf)    AND mf.ES_CAMBIO = 0 -- EVITAR CARGAR CAMBIOS COMO SINT#(lf)    AND mf.ID_SECCION > 0 -- DRIVE#(lf)    AND mf.ID_PAIS > 0 -- DRIVE#(lf)    AND dp.PAIS IN (70 , 4 , 43 , 632 , 208 , 528 , 77 , 800 , 38 , 78 , 640 , 2 , 93 , 508 , 68 , 404 , 11 , 512 , 600 , 480 , 436 , 92 , 8 , 220 , 428 , 647 , 63 , 91 , 11 , 53 , 32 , 1 , 76 , 9 , 416 , 3 , 64 , 664 , 7 , 24 , 624 , 5 , 628 , 79 , 95 , 636 , 54 , 604 , 55 , 18 , 96 , 46 , 204 , 101 , 97 , 432 , 28 , 804 , 649 , 60 , 10 , 644 , 61 , 6 , 66 , 75 , 98 , 388 , 30 , 39 , 680 , 212 , 52 , 72 , 524 , 400)#(tab)#(lf)GROUP BY#(lf)    mf.ID_FECHA,#(lf)    dp.DESCRIPCION_INGLES,#(lf)    dl1.LOCALIZACION,#(lf)    dp.PAIS,#(lf)    dl1.DESCRIPCION", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_FECHA", type date}, {"PEDIDOS", Int64.Type}, {"UNIDADES", Int64.Type}, {"LOCATION", type text}, {"COUNTRY", Int64.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Operation Type", each "SINT+", type text)
in
    #"Added Custom"
