// China Status
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("dZbfT9tWFMf/FYsnKnVS1Zc9QzbwUpKJOlND2j4YFtk3CjeiyCLLU9OpdGyEFMZgKC0jGlRkCYyfghiRPNyg/iNcx/kvds5N4trX2hu59uecc8/5nq95/nwkEh95OHJ/fcRLa/e27Zys87enfGOVV26V0ZR5V6KGabGq8pTV6Dw7osokO4MjVjMsdv4A0IhJqD7y8iFG+mpMhRN+vMJbt90PRWW085qaVqeuaGanQg18fQwOCPxOU2MIjUcRWt2+txv8+o0yOt6pkEynTg14jTUQGk+TDBG/yRCKTMN5712J28sCipjsnBoLrOHDImYOjiRwArN1P5X5jS1KnGB2hrA96qtxwsoQnQaLnPwGi2y2768/CGzS+rxGjR+xPz5y0tLhMCfO/LCGOTf/dN/83Ic7RbrImn5Qp4uWBCX7Gd2DNv/72Nkuu+/+cc5u+Ko9zJ6HzqZgOnvUKDBbSbFGAW6+cFf3SskTfAH+KFhKihRMsmB54VPwkntxya92BxdC/K5kBa4DTE6qSx2DJ87ZOS9tC1AFZbCqv39qmsrtU8cRam7BmAeQPQtj9kPWbFoShvrtIJMH1WQoHYa+Q+jyyivv8xqR69NJuMAnqKdPO871v92VJv+l7lZXnc226HaSwLwMA1uuJNjhLGG1PKyCAd0+BIH1+63i1J+I0Y899aJOYdSb9V5rxzn9q19P53eSRa1mRNTAZUg2h+e6rB81Puie13JbvpIVulEUc/P3K85uH4qyoywu8BcoSrJEhlCpUKr7W7kPiSIX7+oBDAqU1RpNDsCDtg/Md0JgXprXFN7Nbd3y46IApwir5ii210dOET1HidyW2PeYs3Xe2z4MzYy9zs2DMP9/XjF9Ts/5ZxWPYb+W37obO7y871u2ODskSgyCgQQ2pS2Lg/xiMLRcdrhfyug8feDFFDt8XOT7ZV7ZDe5wHEvKg/UoqsWOwgscJ/hYh6ekQOTtnUaj7X3cAKGLrk2jX5ogdV/TpiGAqUvt1iJYUaXCrz4KUGONObDool8XGplD05BAYYCnp0MDhNeLVPY/zdRp2P40VXxifsWtRK8Gf97zqu1bNYKDYj2n1lAZvZ0/hpLSgKBBRQGmU1lRWrJf6RcOKg1xISwhPkP7NefiQFSZQAXjd8grMgH6zYiN8WpMPEOofOI0WyJXglXJUrCbCZ0syc1MYi5n66S7tdy9ueDvW/xk0yeNJGQd2MMzViNLzH5hPXr0+OtO5ZUkkiShfb/44SfDeiWrJCk8/qDtBoQH0Qs4gFCoAgaSQsyIfw/s9aH1zID1SN4zY9GQ+aTEBS8910vB6oUML2WmA2b38j8=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"State Code" = _t, #"State Chinese" = _t, #"State ISO" = _t]),
    #"Tipo cambiado" = Table.TransformColumnTypes(Source,{{"State Code", type text}, {"State Chinese", type text}, {"State ISO", type text}})
in
    #"Tipo cambiado"