// Market_Store
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - OMNICHANNEL - ZARA - SINT VERSION DRIVE - MARKET, STORE AND BRAND#(lf)SELECT DISTINCT #(lf)#(tab)dp.PAIS country,#(lf)    dp.PAIS_ISO ISO,#(lf)#(tab)dp.DESCRIPCION market,#(lf)#(tab)dp.DESCRIPCION_INGLES market_english,#(lf)#(tab)dl.DESCRIPCION physical_store,#(lf)        dl.DESCRIPCION_DB2 descripcion_db2,#(lf)#(tab)dl.LOCALIZACION,#(lf)#(tab)CASE#(lf)#(tab)#(tab)WHEN dl.ID_CADENA IN (1, 2) THEN 'ZARA'#(lf)#(tab)#(tab)ELSE 'KIDDY''S CLASS'#(lf)#(tab)END AS brand#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)#(tab)ON (dp.ID_PAIS = mf.ID_PAIS)#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl#(lf)#(tab)ON (dl.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING)#(lf)#(tab)#(tab)AND (dl.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121, 6)) -- SINT TRANSACTION#(lf)WHERE #(lf)#(tab)mf.ID_CADENA IN (1, 2) -- ZARA Y ZARA SUR (CON KIDDY'S CLASS INCLUIDAS EN ZARA)#(lf)#(tab)AND mf.ID_TIPO_MOVIMIENTO IN (72, 772) -- ORDER TRANSACTION#(lf)#(tab)AND mf.ESTADO NOT IN ('X', 'M') -- DRIVE #(lf)#(tab)AND mf.REPOSICION = 0 -- DRIVE#(lf)        AND mf.ES_CAMBIO = 0 -- EVITAR CARGAR CAMBIOS COMO SINT#(lf)#(tab)AND mf.ID_SECCION > 0 -- DRIVE#(lf)#(tab)AND mf.ID_PAIS > 0 -- DRIVE#(lf)        AND dl.LOCALIZACION > 0 -- QUITAMOS LOS ""NO TIENE""#(lf)ORDER BY #(lf)#(tab)dl.LOCALIZACION ASC"]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MARKET", type text}, {"LOCALIZACION", type text}, {"COUNTRY", Int64.Type}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",",","",Replacer.ReplaceText,{"MARKET", "MARKET_ENGLISH"}),
    #"Added Custom Store Description" = Table.AddColumn(#"Replaced Value", "Store Description", each if [PHYSICAL_STORE] = "NO TIENE" then "NO TIENE" else  Text.PadStart(Text.BeforeDelimiter([PHYSICAL_STORE], " -"), 5, "0") & " - " & Text.AfterDelimiter([PHYSICAL_STORE], "- "), type text),
    #"Extracted Text After Delimiter" = Table.TransformColumns(#"Added Custom Store Description", {{"PHYSICAL_STORE", each Text.AfterDelimiter(_, "- "), type text}}),
    #"Renamed Columns" = Table.RenameColumns(#"Extracted Text After Delimiter",{{"MARKET", "Market"}, {"COUNTRY", "Country"}, {"MARKET_ENGLISH", "Market English"}, {"LOCALIZACION", "Location"}, {"BRAND", "Brand"}, {"PHYSICAL_STORE", "Store Name"}, {"DESCRIPCION_DB2", "Store Description Logistics"}}),
    #"Added Custom Market-Store" = Table.AddColumn(#"Renamed Columns", "Market - Store", each [Market English] & " - " & [Store Description], type text),
    #"Added Custom Store Location" = Table.AddColumn(#"Added Custom Market-Store", "ID Store", each if [Location] = "0" then "DOES NOT HAVE" else Text.PadStart([Location],5,"0"), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom Store Location",{"Location"}),
    #"Merged Columns ID Country-Store" = Table.AddColumn(#"Removed Columns", "ID Country-Store", each Text.Combine({Text.From([Country], "es-ES"), "-", [ID Store]}), type text),
    #"Merged Queries Pack Store" = Table.NestedJoin(#"Merged Columns ID Country-Store", {"ID Store"}, Zara_Packing_Stores, {"ID Store"}, "Zara_Packing_Stores", JoinKind.LeftOuter),
    #"Expanded Pack Store" = Table.ExpandTableColumn(#"Merged Queries Pack Store", "Zara_Packing_Stores", {"Pack Store"}, {"Pack Store"}),
    #"Replaced Value Pack Store null" = Table.ReplaceValue(#"Expanded Pack Store", null,"NO PACK STORES",Replacer.ReplaceValue,{"Pack Store"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Replaced Value Pack Store null",{"ID Country-Store", "ISO", "Country", "Market", "Market English", "ID Store", "Store Name", "Store Description Logistics", "Store Description", "Market - Store", "Brand", "Pack Store"}),
    #"Filtered Rows" = Table.SelectRows(#"Reordered Columns", each ([#"Market - Store"] <> "FRANCE - 00160 - BCN-P. GRACIA" and [#"Market - Store"] <> "GERMANY - 06479 - MAD-SERRANO" and [#"Market - Store"] <> "FINLAND - 06659 - S.SEB-N.MERCADO") and ([ID Store] <> "06739" and [ID Store] <> "09323" and [ID Store] <> "09334" and [ID Store] <> "09335" and [ID Store] <> "09385" and [ID Store] <> "09467" and [ID Store] <> "09673" and [ID Store] <> "09677" and [ID Store] <> "09686" and [ID Store] <> "09740" and [ID Store] <> "09780" and [ID Store] <> "09799" and [ID Store] <> "10348" and [ID Store] <> "10349" and [ID Store] <> "10715" and [ID Store] <> "10800" and [ID Store] <> "11182" and [ID Store] <> "11185" and [ID Store] <> "11218" and [ID Store] <> "11221" and [ID Store] <> "11222" and [ID Store] <> "11245" and [ID Store] <> "11274" and [ID Store] <> "11458" and [ID Store] <> "11462" and [ID Store] <> "13027" and [ID Store] <> "13105" and [ID Store] <> "13108" and [ID Store] <> "13109" and [ID Store] <> "13110" and [ID Store] <> "13111" and [ID Store] <> "13112" and [ID Store] <> "13144" and [ID Store] <> "13154" and [ID Store] <> "13155" and [ID Store] <> "13400" and [ID Store] <> "13431" and [ID Store] <> "13434" and [ID Store] <> "14251" and [ID Store] <> "14374" and [ID Store] <> "14377"))
in
    #"Filtered Rows"