// Zara_Returns_Store_PAT_LASTMONTH
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - DEVOLUCIONES PAT - ZARA - TIENDA - LAST MONTH#(lf)SELECT#(lf)     mf.ID_FECHA,#(lf)    COUNT(DISTINCT mf.ID_PEDIDO_ECOMMERCE) devoluciones,#(lf)    SUM(mf.UNIDADES) unidades,#(lf)    SUM(mf.IMPORTE) local_amount,#(lf)    SUM(ROUND (mf.IMPORTE * mf.CAMBIO_REFERENCIA, 2)) amount_euros,#(lf)    dp.PAIS country,#(lf)#(tab)dp.DESCRIPCION_INGLES market_english,#(lf)    dl1.LOCALIZACION location,#(lf)    dl1.DESCRIPCION physical_store#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMECOMMERCE.DIM_ESTADO_PEDIDO_ECOMMERCE depe#(lf)    ON (depe.ID_ESTADO_PEDIDO_ECOMMERCE = mf.ID_ESTADO_PEDIDO_ECOMMERCE)#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)    ON (dp.ID_PAIS = mf.ID_PAIS)#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)    ON (dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING)#(lf)        AND (dl1.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121)) -- PICKING EN TIENDA#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)    ON (dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALMACEN)#(lf)        AND (dl2.ID_TIPO_LOC NOT IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121)) -- EXPEDICIÓN DESDE ALMACÉN#(lf)WHERE#(lf)#(tab)mf.ID_FECHA_PLATAFORMA BETWEEN ADD_MONTHS(CURRENT_DATE, -2)#(lf)#(tab)#(tab)AND ADD_MONTHS(CURRENT_DATE, 1)#(lf)#(tab)AND mf.ID_FECHA BETWEEN ADD_MONTHS(CURRENT_DATE, -1)#(lf)#(tab)#(tab)AND (CURRENT_DATE + 1)#(lf)    AND mf.ID_TIPO_MOVIMIENTO IN (73, 808) -- RETURN TRANSACTION#(lf)    AND mf.ID_CADENA IN (1, 2) -- ZARA, ZARA SUR#(lf)    AND mf.REPOSICION = 0 -- DRIVE#(lf)    AND mf.ES_CAMBIO = 0 -- EVITAR CARGAR CAMBIOS COMO SINT#(lf)    AND mf.ID_SECCION > 0 -- DRIVE#(lf)    AND mf.ID_PAIS > 0 -- DRIVE#(lf)GROUP BY#(lf)    mf.ID_FECHA,#(lf)    dp.DESCRIPCION_INGLES,#(lf)    dp.PAIS,#(lf)    dl1.LOCALIZACION,#(lf)    dl1.DESCRIPCION", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID_FECHA", type date}, {"DEVOLUCIONES", Int64.Type}, {"UNIDADES", Int64.Type}, {"LOCATION", type text}, {"COUNTRY", Int64.Type}}),
    #"Added Custom" = Table.AddColumn(#"Changed Type", "Operation Type", each "PAT", type text)
in
    #"Added Custom"