// Market_Store
let
    Source = Oracle.Database("EXAPRO_REP", [HierarchicalNavigation=true, Query="-- ORACLE EXADATA - DW ECOMMERCE - OMNICHANNEL - BERSHKA - SINT VERSION DRIVE - MARKET, STORE AND BRAND#(lf)SELECT #(lf)  DISTINCT #(lf)    dp.PAIS country,#(lf)    dp.PAIS_ISO ISO,#(lf)    dp.DESCRIPCION market,#(lf)    dp.DESCRIPCION_INGLES market_english,#(lf)    dl1.DESCRIPCION physical_store,#(lf)    dl1.DESCRIPCION_DB2,#(lf)    dl1.LOCALIZACION location#(lf)FROM DMCOMERCIAL.MIC_FACT_PEDIDO_DEVOL_ECOMM mf#(lf)INNER JOIN DMCOMERCIAL.DIM_PAIS dp#(lf)  ON dp.ID_PAIS = mf.ID_PAIS#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl1#(lf)  ON dl1.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALM_PICKING#(lf)    AND dl1.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- PICKING EN TIENDA#(lf)INNER JOIN DMCOMERCIAL.DIM_LOCALIZACION dl2#(lf)  ON dl2.ID_LOCALIZACION = mf.ID_LOCALIZACION_ALMACEN#(lf)    AND dl2.ID_TIPO_LOC IN (12, 13, 15, 16, 17, 18, 19, 20, 21, 81, 121) -- EXPEDICIÓN DESDE TIENDA#(lf)WHERE#(lf)  mf.ID_FECHA_PLATAFORMA BETWEEN TO_DATE ('01/01/2019', 'DD/MM/YYYY')#(lf)    AND TO_DATE ('28/02/2021', 'DD/MM/YYYY')#(lf)  AND mf.ID_FECHA BETWEEN TO_DATE ('01/02/2019', 'DD/MM/YYYY') #(lf)    AND TO_DATE ('31/01/2021', 'DD/MM/YYYY')#(lf)  AND ((mf.ID_TIPO_MOVIMIENTO IN (72, 772) AND mf.ESTADO NOT IN ('X', 'N', 'PQ')) -- ORDER TRANSACTION#(lf)    OR mf.ID_TIPO_MOVIMIENTO IN (73, 808)) -- RETURN TRANSACTION#(lf)  AND mf.ID_CADENA = 5 -- BERSHKA    #(lf)  AND mf.REPOSICION = 0 -- DRIVE#(lf)  AND mf.ES_CAMBIO = 0 -- DRIVE#(lf)  AND mf.ID_SECCION > 0 -- DRIVE#(lf)  AND mf.ID_PAIS > 0 -- DRIVE#(lf)  AND dl1.LOCALIZACION > 0 -- QUITAMOS LOS ""NO TIENE""#(lf)ORDER BY #(lf)  dl1.LOCALIZACION ASC", CommandTimeout=#duration(0, 7, 0, 0)]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"MARKET", type text}, {"COUNTRY", Int64.Type}, {"LOCATION", type text}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type",",","",Replacer.ReplaceText,{"MARKET", "MARKET_ENGLISH"}),
    #"Added Custom" = Table.AddColumn(#"Replaced Value", "Store Description", each if [PHYSICAL_STORE] = "NO TIENE" then "NO TIENE" else  Text.PadStart(Text.BeforeDelimiter([PHYSICAL_STORE], " -"), 5, "0") & " - " & Text.AfterDelimiter([PHYSICAL_STORE], "- "), type text),
    #"Removed Columns" = Table.RemoveColumns(#"Added Custom",{"PHYSICAL_STORE"}),
    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"MARKET", "Market"}, {"COUNTRY", "Country"}, {"MARKET_ENGLISH", "Market English"}, {"LOCATION", "Location"}, {"DESCRIPCION_DB2", "Store Description Logistics"}}),
    #"Added Custom1" = Table.AddColumn(#"Renamed Columns", "Market - Store", each [Market English] & " - " & [Store Description], type text),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Store Location", each if [Location] = "0" then "DOES NOT HAVE" else Text.PadStart([Location],5,"0"), type text),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Pack Store", each if Text.Contains([Store Description Logistics], "PACK STORE") then "PACK STORES" else "NO PACK STORES", type text),
    #"Inserted Merged Column" = Table.AddColumn(#"Added Custom3", "ID Country-Store", each Text.Combine({ Text.From([Country], "es-ES"),[Store Location]}, "-"), type text),
    #"Removed Columns1" = Table.RemoveColumns(#"Inserted Merged Column",{"Location"}),
    #"Reordered Columns" = Table.ReorderColumns(#"Removed Columns1",{"ID Country-Store", "Country", "Market", "Market English", "Store Location", "Store Description", "Store Description Logistics", "Pack Store", "Market - Store"}),
    #"Merged Queries" = Table.NestedJoin(#"Reordered Columns", {"Store Location"}, Store_Capacity, {"COD STORE"}, "Store Capacity", JoinKind.LeftOuter),
    #"Expanded {0}" = Table.ExpandTableColumn(#"Merged Queries", "Store Capacity", {"Capacity"}, {"Store Capacity"})
in
    #"Expanded {0}"